docs/getting-started/docker.md
This URL in the documentation didn't link to the actual file it seemed to be referencing and was instead linking you to a 404 page.
=> docs: fix link to config in docker guide

frontend/workflows/k8s/src/delete-pod.jsx
Our internal resolver deduces the clientset based on the user and clusters
passed. Coalescing this to `"undefined"` matches the HPA frontend as well.
=> k8s: null coalesce clientset on pod delete

docs/about/architecture.md, docs/about/what-is-clutch.md, docs/community.md
Fix some broken links found clicking around the docs. Trim whitespace from the
doc pages as well.
Fixes #54
=> docs: update some broken links

docs/_website/netlify.toml
Because the docs are generated, but not from a nested folder in _website, netlify never sees changes to the markdown.
This means that all builds that only modify markdown are cancelled.
Per the help community, here's one way of solving the problem:
https://community.netlify.com/t/builds-cancelled-for-a-new-branch-due-to-no-content-change/17169/2
CI.
=> docs: fix unnecessary build cancellation

frontend/packages/data-layout/src/manager.tsx
Remove default caching for the hydrator response of a data layout. This causes unexpected side-effects as the wizard component isn't unmounted between workflow cycles.
e.g. if requesting to terminate two ec2 instances back-to-back, the second termination request doesn't occur due to the data layout caching the response of the of the previous termination request.
**Current Behavior**
**With Fix**
Local testing.
=> data layout: remove default layout caching

Makefile, tools/compile-protos.sh, tools/frontend-gateway-linker.sh, tools/install-yarn.sh, tools/scaffolding/templates/gateway/Makefile
We were already downloading yarn as a js file in order to pin it.
Then we would call the system yarn which would read the yarnrc and then call into the downloaded yarn.
Instead of relying on system yarn, provide a script that calls the downloaded yarn directly.
Manual + CI.
Fixes #60
=> ci: execute yarn directly instead of from PATH

frontend/workflows/ec2/src/terminate-instance.tsx
Appends all available tags for the instance, as they are secondary information I opted to display them below our original data set.
Before
After
Local testing.
n/a
=> ec2: display tags during termination flow

tools/go.mod
Makes tools a module so it can be vendored with go modules tooling for custom gateways.
Manual
First step in addressing #88
=> ci: make tools its own module

.github/workflows/frontend.yml, frontend/package.json, frontend/packages/app/package.json, frontend/packages/core/package.json, frontend/packages/data-layout/package.json, frontend/packages/tools/package.json, frontend/packages/wizard/package.json, frontend/workflows/ec2/package.json, frontend/workflows/envoy/package.json, frontend/workflows/experimentation/package.json, frontend/workflows/k8s/package.json, frontend/workflows/kinesis/package.json, frontend/workflows/sourcecontrol/package.json, tools/scaffolding/templates/frontend/package.json, tools/scaffolding/templates/gateway/frontend/package.json, tools/scaffolding/templates/gateway/frontend/workflows/echo/package.json
Publish and consume beta versions of clutch packages/workflows.
This allows us to still maintain some correlation between the frontend and backend versioning while also allowing us to use semantic version resolution during installations.
=> ci: publish beta versions of frontend packages

frontend/packages/tools/workflow-registrar.js, tools/frontend-gateway-linker.sh, tools/scaffolding/templates/gateway/frontend/src/clutch.config.js
The workflow registrar script should use the root of the src directory containing the `clutch.config.js` file to determine which workflow packages are installed.
Local.
```bash
$ node workflow-registrar.js /Users/dschaller/go/src/github.com/lyft/clutch/frontend/packages/app/src
Registered ec2 workflow...
Registered envoy workflow...
Registered k8s workflow...
Generated Workflow imports!
```
Partially fixes #87
=> tools: fix cwd for workflow registrar to find installed workflows

backend/service/k8s/deployment.go, backend/service/k8s/hpa.go
This ensure that the k8s logic when mutating a resource has basic conflict retries as provided by upstream. Mutations of k8s objects happen very frequently this is important for the services reliability. We will use the default [retry policy](https://github.com/kubernetes/client-go/blob/3473491eeb2e22384b846a27f3dceb9aaa73dd76/util/retry/util.go#L26-L33).
Manual testing of both k8s endpoints on a local k8s cluster (v1.16.6).
n/a
=> k8s: RetryOnConflict for resource mutations

frontend/tsconfig.json, tools/scaffolding/templates/frontend/tsconfig.json
Target ES2018 for typescript package compilations. This removes relying on consumers to compile the packages.
Locally.
=> frontend: target ES2018 during typescript compilation

README.md
Fix link to code of conduct.
Manual
=> docs: fix code of conduct link in README

.github/workflows/scaffolding.yml
According to
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
this should work...
Follow up to #101
Not possible :cry:
=> ci: fix scaffolding SHA reference on main

.github/workflows/scaffolding.yml
Follow up to #140. This should correctly pass the fork owner instead of always passing `lyft`.
None.
=> ci: pass correct repo owner to scaffolding

.github/workflows/scaffolding.yml
Testing on forks is complicated. Tests are slow.
For now we will only run on main and fix after the fact. If frequent breakage becomes a problem we can do the work to get it running on each PR.
N/A
=> ci: only test scaffolding on main

backend/gateway/config.go, backend/gateway/config_test.go
Disable stack for warns when using pretty logger.
This is default behavior that is not desirable.
Unit.
=> gateway: disable stack for warns when using pretty logger

backend/service/k8s/clientset.go, backend/service/k8s/deployment.go, backend/service/k8s/hpa.go, backend/service/k8s/k8s.go, backend/service/k8s/pods.go
Currently if you deploy clutch to kubernetes without providing a `kubeconfig` file, the clutch kubernetes services does not configure it self for `InClusterConfig` if no other configuration is provided. This adds the ability to fall back to `InClusterConfig` when no other `kubeconfig` is available.
I also had to slightly modify the way we handle which k8s cluster clutch is currently operating on, normally this information is provided by the `kubeconfig`. But when using `InClusterConfig` there is currently no way to get a cluster identifier as reported upstream https://github.com/kubernetes/kubernetes/issues/44954. We also cant make use of `ClusterName` in `ObjectMeta` as it's [not currently being set](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L266-L27 …
=> kubernetes: fallback to InClusterConfig if no kubeconfig available

.github/workflows/api.yml, .github/workflows/frontend.yml, .github/workflows/scaffolding.yml
Use Node 14 instead of 12 in CI.
Should be marginally faster, also it's the current release.
Trying to fix
```
$ make frontend-verify
lint:packages
yarn run v1.22.4
$ npx sort-package-json package.json packages/**/package.json --check
npm ERR! cb.apply is not a function
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dhochman/.npm/_logs/2020-07-30T18_20_46_594Z-debug.log
Install for [ 'sort-package-json@latest' ] failed with code 1
error Command failed with exit code 1.
```
CI
=> ci: use node 14

frontend/packages/wizard/src/wizard.tsx
Fix an issue where updating step data would overwrite previously set data. E.g. if a custom submit handler was set via `setOnSubmit` and a subsequent call to `setIsLoading` occurred a wizard' step data would only contain the data from the subsequent `setIsLoading` call.
Found this issue when testing submissions of an editable metadata table with validation attached. Manually confirmed this works.
=> wizard: fix overwrite issue on update

.github/workflows/frontend.yml
Fix publishes on master to use correct version identifier.
=> ci: fix node version of publish job

.github/renovate.json
So close, e.g. https://github.com/lyft/clutch/pull/167
Renovate updates go.sum (unlike dependabot) but doesn't tidy, which we lint for.
This should make mergeable go updates with no additional steps a reality.
None. Read the docs.
=> ci: enable go mod tidy for renovate

frontend/packages/core/src/Table/metadata-table.tsx
Validating on load can be a bit jarring for fields without default values. Since validation will happen on submit it's ok to delay this.
=> metadata table: remove validation on load

tools/scaffolding/scaffolder.go
This fixes a `filepath.WalkFunc` that wasn't handling its incoming error.
https://golang.org/pkg/path/filepath/#WalkFunc
=> tools/scaffolding: fix walkfunc error

backend/module/chaos/experimentation/rtds/rtds.go
Improve the error message logged by the RTDS service when the experiment store service can't be found.
None
=> experimentation framework: improve error logging message

.github/renovate.json, .github/workflows/ci.yml
Adding some configuration options to renovatebot and a CI job to validate the file when it changes. The job is important since we won't know the if the configuration is bad until PRs fail to open.
- [`automergeLinters`](https://docs.renovatebot.com/presets-default/#automergelinters)
- [`combinePatchMinorReleases`](https://docs.renovatebot.com/presets-default/#combinepatchminorreleases)
- [`enableVulnerabilityAlerts`](https://docs.renovatebot.com/presets-default/#enablevulnerabilityalerts)
- [`preserveSemverRanges`](https://docs.renovatebot.com/presets-default/#preservesemverranges)
- [`rebaseStalePrs`](https://docs.renovatebot.com/presets-default/#rebasestaleprs)
- [`separateMajorReleases`](https://docs.renovatebot.com/presets-default/#separatemajorreleases)
- …
=> ci: customize renovatebot & add validate job

.github/renovate.json
This should prepend the renovate PRs with `housekeeping: `
=> ci: prepend dependency updates with housekeeping

.github/CODEOWNERS
=> ci: fix codeowners team name

frontend/packages/core/src/Resolver/fetch.tsx
Found this when testing the k8s example from #148. If the data does not contain results/partial failures we should fallback to an empty list.
=> resolver: handle empty results and failures gracefully

.github/renovate.json
This adds a few group presets to renovatebot
=> ci: add dependency groups to renovatebot

tools/scaffolding/scaffolder.go
Remove attempting to register new frontend workflows after scaffolding since we can't predict how the workflow will be consumed.
=> scaffolder: remove workflow registration upon completion

.github/renovate.json
Manual rebasing still possible. This prevents a long rebase chain when dealing with several housekeeping PRs.
Read the docs.
=> ci: have renovate rebase only on conflicts

backend/service/k8s/deployment.go, backend/service/k8s/deployment_test.go, backend/service/k8s/hpa.go, backend/service/k8s/hpa_test.go, backend/service/k8s/pods.go, backend/service/k8s/pods_test.go
We should defer to the k8s object `ClusterName` before falling back to what the clientset is configured for. We changed this behavior slightly in https://github.com/lyft/clutch/commit/ad118d0265aa4505f912da779f6edc12d74fce4d and this preserves the original intent but falling back to `cs.Cluster()` if `ClusterName` is not set.
=> k8s: use ClusterName if available

tools/scaffolding/templates/gateway/Makefile
The tuturial is built around trying to start a frontend on port 3000,
but the `frontend-dev` target that would start that isn't present
in the template directory that creates a scaffolding directory.
This adds that target
Add the `frontend-dev` target to the scaffolding `Makefile`.
Unfortunately, since it seems like by creating a commit in my local checkout of the clutch repo, I can't seem to completely create a new scaffold project to test this, but it looks like this is doing the right thing:
```spacey@bagpig:~/dvcs/github/clutch (add-scaffolding-frontend-dev-target)$ make scaffold-gateway
cd tools/scaffolding && go run scaffolder.go -m gateway -p 72c70a2
2020/08/03 22:37:25 Welcome!
*** Analyzing environment...
> GOPATH: /home/spacey/go
> User: spacey
*** Based on your environment, …
```
=> scaffolding: add frontend-dev make target

frontend/workflows/k8s/src/resize-hpa.jsx, frontend/workflows/k8s/src/tests/__snapshots__/resize-hpa.test.jsx.snap
Supporting the notes field on resize hpa conformation panel.
Locally against a local kubernetes cluster using this frontend configuration to test.
```
resizeHPA: {
trending: true,
componentProps: {
resolverType: "clutch.k8s.v1.HPA",
notes: [
{
severity: "info",
text: "This is a test note for resize hpa",
},
],
},
},
```
Also tested without and notes configured
```
resizeHPA: {
trending: true,
componentProps: {
resolverType: "clutch.k8s.v1.HPA",
},
},
```
=> workflow: support notes in resize-hpa

frontend/packages/app/src/clutch.config.js, frontend/workflows/ec2/src/terminate-instance.tsx, frontend/workflows/ec2/src/tests/__snapshots__/terminate-instance.test.jsx.snap
Add conformation notes for terminate instance workflow.
Tested locally against the mock backend.
With a note.
```
terminateInstance: {
trending: true,
componentProps: {
resolverType: "clutch.aws.ec2.v1.Instance",
notes: [
{
severity: "info",
text: "This is a test note for terminate instance.",
}, 
],
},
},
```
Without a note.
```
terminateInstance: {
trending: true,
componentProps: {
resolverType: "clutch.aws.ec2.v1.Instance",
},
},
```
=> workflow: notes for terminate instance

examples/kubernetes/README.md
The `clutch.yaml`url was not correct.
=> example: fix kubernetes clutch.yaml url

docs/_website/generator/go.mod, frontend/package.json
`s/clutch-sh/lyft/g` as it applies to repo owners.
=> core: fix outdated org paths

frontend/packages/core/src/Resolver/fetch.tsx
Show users error details when the error is not a `ClientError`.
=> resolver: display non-client errors

frontend/packages/app/cypress/integration/navigation_spec.js
Restructured E2E tests to consolidate the assertion of drawer links being displayed and hidden into one. Before this was causing random failures since there was a dependency between the two tests executing in the correct order.
Additionally, this scoped the menu expansion and collapse click to the icon to prevent drawer resizing from causing issues.
CI
=> ci: restructure e2e tests

backend/service/k8s/pods.go, backend/service/k8s/pods_test.go
Small part of the overall strategy to address #257, where the freeform search will never function.
This will at least use the default namespace for the clientset when the resolver passes in the empty namespace as sentinel value.
#257
=> k8s: always use clientset's derived namespace

tools/frontend-gateway-linker.sh
Fixes undesired behavior where using the linker in a project with an existing lockfile upgrades dependencies unintentionally.
=> tools: use destination lockfile in gateway linker if present

tools/scaffolding/scaffolder.go
The old message was confusing as it directed users to run a make target in the directory of the new workflow.
This improves the scaffolder by telling the user where the generated workflow is and points them to the configuration documentation since we aren't able to predict the destination's contents.
=> scaffolding: improve workflow completion message

.github/renovate.json
The AWS SDK is released almost everyday. This will limit updates to once per week.
Read the docs.
=> ci: limit aws sdk updates to weekly cadence

frontend/api/tsconfig.json, frontend/packages/core/tsconfig.json, frontend/packages/data-layout/tsconfig.json, frontend/packages/wizard/tsconfig.json, frontend/tsconfig.json, frontend/workflows/ec2/tsconfig.json, frontend/workflows/envoy/tsconfig.json, frontend/workflows/experimentation/tsconfig.json, frontend/workflows/k8s/tsconfig.json, frontend/workflows/kinesis/tsconfig.json, frontend/workflows/sourcecontrol/tsconfig.json
Pull exclude patterns to root TSConfig file to reduce duplication.
=> housekeeping: hoist tsconfig excludes

frontend/workflows/kinesis/package.json
Removes the clean call before building as it's not required.
=> kinesis: remove clean before build during compilation

backend/api/assets/v1/assets.pb.gw.go, backend/api/audit/v1/audit.pb.gw.go, backend/api/authn/v1/authn.pb.gw.go, backend/api/authz/v1/authz.pb.gw.go, backend/api/aws/ec2/v1/ec2.pb.gw.go, backend/api/aws/kinesis/v1/kinesis.pb.gw.go, backend/api/chaos/experimentation/v1/experimentation.pb.gw.go, backend/api/envoytriage/v1/envoytriage_api.pb.gw.go, backend/api/healthcheck/v1/healthcheck.pb.gw.go, backend/api/k8s/v1/k8s.pb.gw.go, backend/api/resolver/v1/resolver_api.pb.gw.go, backend/api/sourcecontrol/v1/sourcecontrol.pb.gw.go, backend/api/topology/v1/topology_api.pb.gw.go
Fixes API verification job failing on main due to #295.
CI.
=> api: regenerate for grpc-gateway v1.14.7

backend/resolver/resolver.go, backend/resolver/resolver_test.go
Fixes a bug where a schema used for two different `want`ed types would get duplicates of any dynamic options.
This is due to option extensions always returning the same object with same pointer. We clone the meta object so if it's ever modified in different contexts it doesn't happen twice.
The long term fix to avoid these issues, as well as fully realize the benefit of dynamic options, is to move dynamic option hydration to the request path in the resolver module.
Unit
=> resolver: fix duplicate options bug

Makefile, tools/scaffolding/templates/gateway/.gitignore, tools/scaffolding/templates/gateway/Makefile, tools/scaffolding/templates/gateway/backend/.air.toml
Removing the `make backend-watch` command and making this the default behavior of `make backend-dev`. This PR also adds the necessary configuration for live code reloading for a scaffolded gateway.
manual.
`make backend-dev` works as expected as well as `make dev`.
Generated a custom gateway and tested the `make backend-dev` command
```
➜  clutch-custom-gateway make backend-dev
REPO_ROOT=/Users/mcutalo/gocode/src/github.com/mcutalo/clutch-custom-gateway /usr/bin/env bash /Users/mcutalo/gocode/pkg/mod/github.com/lyft/clutch/tools@v0.0.0-20200814040600-37c4a3407e78/air.sh
info: Downloading air v1.12.3 to build environment
__    _   ___
/ /\  | | | |_)
/_/--\ |_| |_| \_ v1.12.3 // live reload for Go apps, with Go1.14.0
```
=> tooling: backend-dev will now live reload

api/sourcecontrol/github/v1/github.proto, backend/api/sourcecontrol/github/v1/github.pb.go, backend/api/sourcecontrol/github/v1/github.pb.validate.go, backend/go.mod, backend/go.sum, backend/mock/service/githubmock/githubmock.go, backend/service/github/github.go, backend/service/github/github_test.go, backend/service/github/iface.go, frontend/api/src/index.d.ts, frontend/api/src/index.js
Internally at Lyft, we're using clutch to display the status of some deployment pipelines. To do this, we need some additional functionality exposed in the github service to adequately compare commits.
Adding two methods to the github service.
`GetContents` is a wrapper around [Repositories.GetContents] (https://godoc.org/github.com/google/go-github/github#RepositoriesService.GetContents) and returns the contents of the file at the requested path. 
`CompareCommits` is a wrapper around [Repositories.CompareCommits] (https://godoc.org/github.com/google/go-github/github#RepositoriesService.CompareCommits) and indicates if a given sha comes before/after a reference sha. 
````
make backend-test
cd backend && go test -race -covermode=atomic ./...
?       github.com/lyft/clutch/backend  [no test …
```
=> github: add CompareCommits function to service

tools/compile-protos.sh
Ensure npm is installed when compiling protos (the protobufjs cli needs it) and throw an error if not.
Local + CI
Fixes #311
=> ci: check for npm in api compile script

backend/gateway/mux/mux.go, frontend/packages/core/src/network.ts
Delegate authentication handling to the client. The client will attempt to reload the current workflow, in turn triggering a credential refresh. To prevent infinite redirects we set a query param to denote that we have retried.
Ideally we prevent progression if the second authorization attempt fails. That will come in a follow up PR.
=> auth: reload client on authentication errors

frontend/packages/core/src/Input/text-field.tsx
Shrink the Input label if a placeholder is present to prevent overlapping text.
=> text-field: shrink label if placeholder set

backend/gateway/mux/mux.go, backend/module/authn/authn.go, frontend/packages/core/src/network.ts
At the moment, if the authentication token expires while a Clutch session is open any requests to the server will attempt to refresh this through a chain of redirects (`API endpoint` -> `/v1/authn/login` -> `Auth provider` -> `Clutch landing page`). However, some auth providers (such as Okta) will reject redirects that are initiated from a different origin (via the absence of a CORS policy). Okta intentionally does not support CORS on their authentication endpoints, asking instead that this be done from the server. Long term that is the best approach but Clutch does not currently have a datastore for this so this logic must be handled on the front-end.
This PR changes the authentication logic such that the authn module has two possible outcomes:
- If no `redirect_url` is specified (such …
=> auth: handle auth redirect on client

frontend/packages/app/public/index.html, tools/scaffolding/templates/gateway/frontend/public/index.html
Include credentials in manifest fetch. This prevents redirects if your domain sits behind an auth provider.
=> frontend: include credentials in manifest fetch

backend/gateway/gateway.go
Informational logging about which configuration file clutch is using.
> {"level":"info","ts":1597875368.2666712,"caller":"gateway/gateway.go:51","msg":"Using configuration","file":"clutch-config.yaml"}
With full filepath
>{"level":"info","ts":1597874265.58532,"caller":"gateway/gateway.go:51","msg":"Using configuration","file":"/Users/mcutalo/Desktop/clutch-config.yaml"}
local
=> core: log configuration file being used

backend/mock/service/githubmock/githubmock.go, backend/service/github/github.go, backend/service/github/github_test.go, backend/service/github/iface.go
Description
Adds the GitCommit method into the v3repositories interface and a service method to get commit details for a given repository.  
`make backend-test` :+1:
`make backend-verify` :+1:
`make backend` :+1:
In github.go, I've added a [Commit object](https://github.com/lyft/clutch/pull/313/files#diff-1b9746ee0afeded06f610fd4fb017a3fR296) exposing only the data that I'll need to access (files and their filenames), but the GetCommit method could just as easily return a [githubv3.RepositoryCommit](https://github.com/google/go-github/blob/master/github/repos_commits.go#L18) object. Not sure which is the preferable option in this case, but went with this for the time being. Let me know if you have a preference.
=> github: adding GetCommit method to service

frontend/packages/core/src/AppProvider/index.tsx, frontend/packages/core/src/AppProvider/workflow.tsx, frontend/workflows/ec2/src/index.tsx
Allow workflows to define private routes. This will prevent the route from being discoverable via the drawer and search bar while still allowing them to be registered on the application.
**note**: this supersedes the trending property and will hide trending workflows.
manual
=> frontend: allow workflow routes to be private

tools/frontend-gateway-linker.sh
Add `styled-components` and `@material-ui/styles` to the list of linked packages to avoid linking of both of these packages twice for when Clutch is set up to be a submodule of another git repository.
=> core: avoid duplicated of packages

backend/service/chaos/experimentation/experimentstore/experiment_store.go, backend/service/chaos/experimentation/experimentstore/experiment_store_test.go
It should be a "=" operator, not "==".
When we try to stop an experiment we receive the following error:
```
operator does not exist: bigint == unknown
```
=> experimentation: use "=" operator

.github/CODEOWNERS
While working on https://github.com/lyft/clutch/pull/366 I noticed that some of the generated JS files are outside of the scope of the directories that resilience owns even though the generated changes are due to change in `experimentation` specific code.
Adding `frontend/api/src/index.js` to the list of directories owner by resilience to allow us to make changes that result in the change in the generated code without a need for an 'external' approval.
=> ci: add codeowners to js/ts files

frontend/packages/core/src/Input/text-field.tsx
Call `onChange` function only when it's passed by the caller (user of a `TextField`).
=> core: call function only if it's available

frontend/packages/core/src/button.tsx, frontend/packages/core/src/index.tsx
Export `ButtonProps` so that they can be explicitly referenced from outside of `clutch-sh/core` package. We need this change to unblock here https://github.com/lyft/clutch/pull/366/files#diff-8c303b06f3497a4d200d1e7da707d884R24
=> core: export ButtonProps

backend/service/chaos/experimentation/experimentstore/expriment_run_details.go, frontend/workflows/experimentation/src/view-experiment-run.tsx
Changes:
- show one `End Time` and one `Scheduled End Time` fields instead of two `Scheduled End Time` fields
- populate `Scheduled End Time` field with the right value
- do not show `Cancel Experiment Run` button if experiment is in completed state
|-----|------|
| <img width="629" alt="Screen Shot 2020-09-10 at 11 37 17 AM" src="https://user-images.githubusercontent.com/4410346/92784934-d9cebe80-f35b-11ea-9ad8-724d54a4a79c.png"> | <img width="607" alt="Screen Shot 2020-09-10 at 11 44 40 AM" src="https://user-images.githubusercontent.com/4410346/92783919-0afabf00-f35b-11ea-8c63-51ff7dbe7c83.png"> |
=> experimentation: fix view experiment run details view

frontend/packages/core/src/AppLayout/header.tsx, frontend/packages/core/src/AppLayout/user.tsx
Persist theme using CSS instead of relying on inferred CSS via the global theme. This fixes an issue where Material UI would change the global styles and any styles that were inferred (e.g. `color="secondary"` when a select menu was opened) would update.
Manual
=> header: persist theme through global class overrides

frontend/packages/core/src/Input/select.tsx, frontend/packages/core/src/index.tsx
Add a select component to @clutch/core.
This is just a first pass at adding a basic select. In follow up PRs we can add validation and error messaging.
=> core: add new select component

.github/renovate.json
Adding dependencies for renovatebot to ignore:
@date-io/core - incompatible with material-table
babel-jest - react-scripts pins this
eslint - react-scripts pins this
jest - react-scripts pins this
=> ci: add ignored dependencies to renovatebot

frontend/packages/core/src/Feedback/note.tsx
This change adds a `children` parameter to the `NotePanel` frontend component.
This makes it possible to create a note panel that contains complex notes.
Manual testing using a private workflow.
=> frontend: add children param to NotePanel

backend/cmd/migrate/migrate.go
Export a run method so we can import everything in a custom gateway to avoid unknown Any types.
=> migrate: export Run method

backend/service/chaos/experimentation/experimentstore/experiment_store.go, backend/service/chaos/experimentation/experimentstore/experiment_store_test.go
What `scheduled_end_time` is supposed to be used for if we have start_time and end_time fields?
When a new experiment is created its `end_time` and `scheduled_end_time` fields are set to exactly the same value. If an experiment is manually stopped by a user - with the use of a stop button in the experiment details view - we stop the experiment by setting its `end_time` to the current time. For these cases, we can use scheduled_end_time field to see whether there is a difference between originally `scheduled_end_time` and the actually `end_time` to find experiments that were stopped manually.
Unit Tests
=> experimentation: set scheduled_end_time of created experiments

frontend/api/package.json, frontend/package.json, frontend/workflows/experimentation/package.json, frontend/workflows/k8s/package.json, frontend/workflows/serverexperimentation/package.json, frontend/yarn.lock
A few packages were missing dependencies:
- Moved protobufjs dependency from the root of the project to the API package
- Added history (needed as a peer dep to react-router-dom) to the experimentation package
- Added missing @clutch-sh/api package to k8s and server experimentation packages
=> housekeeping: fix dependencies in various packages

tools/frontend-gateway-linker.sh
Add `@material-ui/core` to linked packages to prevent projects importing Clutch as a submodule from overwriting components default styles.
=> tools: include @material-ui/core in linked packages for styling

frontend/packages/core/src/Table/metadata-table.tsx
material-table cannot render an object as a cell child. This should prevent users from accidentally passing in an object and having an error thrown.
https://github.com/mbrn/material-table/issues/1074
=> MetadataTable: stringify objects for TableCell data

frontend/packages/core/src/AppProvider/workflow.tsx
Make the Stack Trace modal text easier to read.
=> Stack Trace Viewer: set font color to text primary

tools/frontend-gateway-linker.sh
This will allow us to use a unified type system when consuming Clutch as a submodule.
Manual
=> tools: link types for gateways

frontend/packages/core/src/AppProvider/workflow.tsx
Allow a functional component with any props to be passed as a routes component. This is necessary for strict type checking.
manual
=> Workflow Config: allow any route component type

frontend/packages/core/src/Resolver/index.tsx
Automatically trim whitespace from any string values for resolver input.
From internal chat:
>UX suggestion - at least for the resize ASG workflow, any leading/trailing whitespace in the “search by name” form input leads to a “not found” error, which is something one can run into when copy/pasting ASG names around and fat-fingering selection. What about sanitizing the input somehow by trimming leading/trailing whitespace?
Manual
=> resolver: automatically trim whitespace from strings

frontend/packages/core/src/AppProvider/themes.tsx, frontend/packages/core/src/landing.tsx
Apply global styling to Typography and Links. The Typography font colors will now match the default text colors provided in the palette. This required a change to the landing cards as they relied on the Typography default primary color of white.
Manual
=> frontend: apply global Typography and Link styles

frontend/packages/core/src/error.tsx, frontend/packages/wizard/src/wizard.tsx
Cleanup global warnings when they are unmounted. This allows the warning to render multiple times from the same page. Prior behavior would only display the warning once until the wizard step was unmounted.
manual
=> wizard: cleanup global warnings on exit

.github/CODEOWNERS
Add `lyft/resilience` to owners  of subset of files from migrations directory to make it possible for resilience team to develop `experimentation` package without approvals from core Clutch maintainers.
N/A
=> ci: Add lyft/resilience to owners  of migrations directory

frontend/packages/core/src/Input/checkbox.tsx
Properly align checkbox panel children side by side.
manual
=> checkbox panel: align options side by side

frontend/workflows/experimentation/src/view-experiment-run.tsx
Do not go back to experiments list view after a user stops/cancels an experiment
| ----- | ------ |
|![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/4410346/94325909-b019b800-ff55-11ea-996f-629ff107aa29.gif)|![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/4410346/94325912-b60f9900-ff55-11ea-83b9-60b9cd62926a.gif)|
See attached GIFs.
=> experimentation: refresh view when experiment is stopped

frontend/workflows/experimentation/src/index.tsx, frontend/workflows/serverexperimentation/src/index.tsx
Use `chaos experimentation` name when displaying routes in the UI.
N/A
=> experimentation: small naming tweaks in configuration file

docs/development/feature.md
This PR adds an additional step to the Amiibo tutorial's documentation. It guides the user in updating the scaffolded index.tsx file by providing a sample file and highlighting the changed lines.  
To successfully register the Amiibo workflow, we also need to update the registration function to reflect the component name changed in previous tutorial steps.
Manually followed tutorial steps and confirmed that the workflow does not get registered until the registration function is also updated.
=> docs: add registration function step to Amiibo tutorial

api/config/gateway/v1/gateway.proto, backend/api/config/gateway/v1/gateway.pb.go, backend/api/config/gateway/v1/gateway.pb.validate.go, backend/gateway/gateway.go, backend/gateway/mux/mux.go, backend/gateway/mux/mux_test.go, backend/go.sum, backend/mock/service/awsmock/awsmock.go, backend/service/aws/aws.go, backend/service/aws/s3.go, frontend/api/src/index.d.ts, frontend/api/src/index.js
Add passthrough host support for frontend static assets. If the deployed version of clutch does not have the requested frontend assets on disk the passthrough host will be used to fetch the correct assets assuming they exist for the configured provider.
In a different PR we would have a more pretty failure mode, currently you simply get a white page.
Testing was performed internally at Lyft, forcing all static asset traffic to go through the passthrough host.
```
gateway:
assets:
s3:
region: us-east-1
bucket: clutch
key: static
```
Passthrough host support #471
=> core / frontend: passthrough host support

frontend/packages/core/package.json, frontend/packages/core/src/AppProvider/index.tsx, frontend/packages/core/src/AppProvider/themes.tsx, frontend/packages/core/src/tests/__snapshots__/not-found.test.tsx.snap, frontend/packages/core/src/tests/not-found.test.tsx, frontend/packages/tools/package.json, frontend/yarn.lock
By centralizing the theme providers we use it'll allow us to more easily swap them out. This also allows us to inject all theme providers in a single place (useful for storybook).
manual
=> core: add a Theme component

frontend/package.json
Currently react-scripts clears the contents of the terminal window when it builds and starts. This is particularly frustrating when the background process we spawn to run babel results in an error that gets thrown away. This change prevents react-scripts from clearing any information upon start.
manual
=> frontend: preserve terminal output when app starts

.github/renovate.json
Update renovatebot config to group docusaurus dependency updates.
=> ci: use docusaurus monorepo group in renovatebot

frontend/packages/core/src/Input/checkbox.tsx, frontend/packages/core/src/Input/stories/checkbox.stories.tsx
The checkbox panel splits the options list into 2 in order to present the as siblings. If the list is an odd number the result of the first list ends up being a float which rounds to the nearest whole number and drops an option.
This PR also:
- fixes the checkbox panel heading alignment and color
- add a story for the Checkbox Panel
=> ui: fix checkbox panel

backend/service/topology/cache.go, backend/service/topology/cache_test.go, backend/service/topology/topology.go
Implements some of the basic caching functionality needed to make progress on the Topology API #30. 
I did think about making this functionality public, however for consistency across services they should implement the standardized interface to populate cache by implementing the [CacheableTopology](https://github.com/lyft/clutch/pull/362/files#diff-a352069dcb53d7f4a25245319d355ea8R39-R48) interface.
Manual with https://github.com/lyft/clutch/pull/362 test implementation. 
This PR makes progress on the Topology API story #30
=> topology: cache Set/Delete operations

backend/gateway/gateway.go, backend/module/chaos/experimentation/api/experimentation.go, backend/module/chaos/serverexperimentation/rtds/rtds.go
Include the name of the components thats being registered as the stats `SubScope`.
n/a
=> core: gateway initialize stats SubScope with component name

backend/cmd/migrate/migrate.go
Currently, migrate script errors out if there are no changes
Tested by manually running the migration script 
Output before change 
```
2020-10-07T22:46:41.090Z	INFO	migrate/migrate.go:85	using database	{"hostInfo": "clutch_admin@<db_url>:5432"}
2020-10-07T22:46:41.147Z	INFO	migrate/migrate.go:129	applying migrations	{"migrationDir": "<path_to_migration_files>"}
2020-10-07T22:46:41.151Z	FATAL	migrate/migrate.go:132	failed running migrations	{"error": "no change"}
exit status 1
```
Output after change 
```
2020-10-07T22:44:14.955Z	INFO	migrate/migrate.go:85	using database	{"hostInfo": "clutch_admin@<db_url>:5432"}
2020-10-07T22:44:14.997Z	INFO	migrate/migrate.go:129	applying migrations	{"migrationDir": "<path_to_migration_files>"}
```
Fixes #[528](https://github.com/lyft/clutch/issues/528)
=> migrate: dont error if there are no changes to apply

frontend/packages/core/src/Input/stories/text-field.stories.tsx, frontend/packages/core/src/Input/text-field.tsx
Fix Text Field component to prevent any [input type that has a placeholder](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Form_%3Cinput%3E_types) from being obscured by a label.
manual & added story
=> text field: fix date types with labels

backend/module/chaos/experimentation/api/experimentation.go, backend/module/chaos/serverexperimentation/rtds/rtds.go, backend/module/chaos/serverexperimentation/rtds/rtds_cache.go, backend/service/chaos/experimentation/experimentstore/storer.go, backend/service/chaos/experimentation/experimentstore/storer_test.go
I read a little bit about Go and apparently `-er` is the default choice when it comes to the names of interfaces in Go.
* https://stackoverflow.com/questions/38842457/interface-naming-convention-golang
* https://golang.org/doc/effective_go.html#interface-names
=> experimentation: rename ExperimentStore to Storer

backend/module/chaos/serverexperimentation/rtds/rtds_cache.go
While performing a periodic RTDS cache refresh, [GetExperiments call](https://github.com/lyft/clutch/blob/7974eeb457c478eb431b76f557843c27becdf917/backend/module/chaos/serverexperimentation/rtds/rtds_cache.go#L115) gets all the server experiments from DB. Currently, if this call fails, we do nothing. 
Going forward, we will disable all the active server experiments if DB call fails as a safety mechanism
=> experimentation: RTDS to disable fault if GetExperiments call to DB fails

docs/_website/docusaurus.config.js
Add a note on the Algolia DocSearch key, since it was brought up as a potential exposure.
=> docs: add security notice for algolia key

backend/module/chaos/experimentation/api/experimentation.go
The existing error message implies there is a misconfiguration of the service when in reality the store being misconfigured or missing entirely is the real issue.
Manual
=> chaos: fix missing store error message

backend/gateway/gateway.go, backend/gateway/log/log.go, backend/gateway/log/log_test.go, backend/go.sum, backend/middleware/audit/audit.go, backend/service/audit/sql.go, backend/service/auditsink/logger/logger.go
Spent awhile trying to figure out how to add a hook in the logger to automatically intercept Any fields containing proto messages and fixing them automatically. I think it's possible but couldn't get it to work.
For now this PR introduces a custom field that logs correctly. I also went through and replaced any existing improper usages of zap.Any. Will have to rely on code review for now to ensure people use the correct field.
Unit
=> core: log protos with custom field

frontend/packages/core/package.json, frontend/yarn.lock
Fix peer dependency warning:
```bash
warning "workspace-aggregator-977e82fb-7a53-4ac2-a88c-e890adb9e94d > @clutch-sh/core > @hookform/resolvers@1.0.0" has incorrect peer dependency "react-hook-form@>=6.6.0".
```
N/A
=> housekeeping: fix react hook form peer dependency warning

frontend/packages/core/src/button.stories.tsx, frontend/packages/core/src/button.tsx, frontend/packages/core/src/stories/button.stories.tsx, frontend/tsconfig.json
PR adds a story for a button, with two variant types: default and destructive
(Update: removed `color` prop and added `disabled`, `startIcon` in recent commits)
Locally
And ran through one of the workflows with Button components
=> storybook: add button story for default and destructive variant

backend/service/audit/storage/local/localstore.go
CI found the tests for this hanging before being killed. Isolated it to a
comparison for the `RequestEvent` returned after an update. The tests were
relying on `map` iteration order during `range` being the same as insertion
order. That's not the case!
This changes that by changing the underlying storage because a map indexed by an
integer has mostly the same interface as a slice. Verified locally with `go test
-count 1000000 ./service/audit/storage/local`.
Still unsure why the tests are hanging on an equality assertion, but that's an
upstream fix and making this green/reducing dev flake comes first.
=> audit: localstorage simplification

frontend/packages/core/src/Input/select.tsx, frontend/packages/core/src/Input/stories/select.stories.tsx
Add new story for the Select component. This also includes various style fixes and cleanup to Select in order to prevent the label from overlaying on top of the select window when the specified width < label text length.
manual
=> storybook: add select story & add CSS fixes

frontend/workflows/envoy/src/server-info.tsx
Explicitly include certain server information fields in the Envoy Remote Triage workflow.
Manual
=> remote triage: filter out unknown data

backend/clutch-config.yaml, backend/service/topology/cache.go
Expire topology cache that is older than 2 hours.
Tested locally by reducing the expiry time to 60 seconds.
This PR makes progress on the Topology API #30 issue.
=> topology: cache expiry

backend/clutch-config.yaml, backend/service/aws/aws.go, backend/service/aws/cache.go, backend/service/aws/cache_test.go, backend/service/k8s/cache.go
Topology caching for AWS. Currently we will cache all AWS objects that clutch can operate on, this includes ASG's, EC2 Instances and Kinesis Streams.
Also cleaned up a few spelling mistakes in this pr.
Unit \ Locally.
This PR makes progress on the Topology API #30 issue.
=> aws: topology caching for aws resources

docs/advanced/security-auditing.md
Updating to correct key name: https://github.com/lyft/clutch/blob/d0d808ed0c6a5798d991be00eac19fb96a0dc301/api/config/service/audit/v1/audit.proto#L52
=> docs: fix key name for in-memory audit config

backend/gateway/config.go, backend/gateway/gateway.go, backend/gateway/meta/meta.go, backend/gateway/meta/meta_test.go, backend/middleware/audit/audit.go, backend/middleware/authz/authz.go
After moving to grpc-gateway v2, we can now start moving to the v2 protobuf Go APIs detailed at https://blog.golang.org/protobuf-apiv2
Unit
=> core: start moving to v2 golang protobuf apis

.github/CODEOWNERS
Add resilience as owners of of `/api/config/module/chaos` directory
N/A
=> ci: add resilience as owners

frontend/packages/core/src/Resolver/index.tsx, frontend/packages/core/src/error.tsx, frontend/packages/core/src/stories/error.stories.tsx
Add Error stories.
Also, updated interface (and consumers) of Error for consistency. `retry` -> `onRetry`.
manual
=> storybook: add error stories

frontend/packages/core/src/Feedback/index.tsx, frontend/packages/core/src/Feedback/stories/warning.stories.tsx, frontend/packages/core/src/Feedback/warning.tsx, frontend/packages/core/src/error.tsx, frontend/packages/core/src/index.tsx
- Add `Warning` story.
- Extracted the `Warning` component into its own file within the feedback folder.
- Fixed a bug where `onClose` was being called twice when warnings were dismissed.
manual with story
=> storybook: add warning story

.github/workflows/api.yml, .github/workflows/ci.yml, .github/workflows/frontend.yml, .github/workflows/scaffolding.yml
Latest renovate requires `>=14.15.0`, causing main branch to :x:
=> ci: setup-node action v2 beta with latest version

backend/gateway/meta/meta.go, backend/gateway/meta/meta_test.go
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4667ab5]
goroutine 46 [running]:
github.com/lyft/clutch/backend/gateway/meta.GetAction(0x6b7af17, 0x2a, 0x0)
/Users/mjang/src/go/src/github.com/lyft/clutch-private/backend/vendor/github.com/lyft/clutch/backend/gateway/meta/meta.go:55 +0x135
```
Unit
=> gateway: fix GetAction panic when no annotation is present

backend/service/k8s/cache.go, backend/service/k8s/cachelessinformer.go, backend/service/k8s/lightweightinformer.go, backend/service/k8s/lightweightinformer_test.go
The motivation of this change is too reduce the memory footprint of the Kubernetes topology caching logic. A major contributor to the memory consumption was the informers cache store which we do not utilize for the Kubernetes topology caching functionality. 
This PR introduces a new type of an informer which sets to reduce the informer cache size by substituting the incoming kubernetes objects with smaller lightweight ones.
During internal testing with large scale Kubernetes deployments we easily saw 15Gb+ of memory usage, when switching to utilize this new `LightweightInfomer` we saw memory usage drop about ~65%.
I pulled out my description from the comments in the code for the reader convenience.
----
The LightweightInformer is an informer thats optimized for memory usage with …
=> k8s: utilize lightweightinformer for topology caching

frontend/packages/core/src/icon.tsx, frontend/packages/core/src/stories/status.stories.tsx, frontend/packages/core/src/stories/trending-up.stories.tsx
Add icon stories for `Status` and `TrendingupIcon`. This also removes the exposed material props of the trending up icon.
manual with stories.
=> storybook: add icon stories

frontend/packages/core/src/panel.tsx, frontend/packages/core/src/stories/panel.stories.tsx
Add ExpansionPanel story. Includes a fix when passing in a expanded flag to only be the default and not the permanent.
manual with story
=> storybook: add expansion panel story

frontend/workflows/serverexperimentation/package.json, frontend/workflows/serverexperimentation/src/dialog.tsx, frontend/workflows/serverexperimentation/src/form-content.tsx, frontend/workflows/serverexperimentation/src/form-page.tsx, frontend/workflows/serverexperimentation/src/start-experiment.tsx
- Combine all steps of start-experiment flow (3 of them currently) into one step.
- Add a modal dialog that asks for the confirmation when a user clicks a button that's supposed to start an experiment.
- Move a user to experiment details view when a new experiment is created.
| ------ | ------ |
|![ezgif com-gif-maker (20)](https://user-images.githubusercontent.com/4410346/98143383-e106da00-1e7d-11eb-83bf-5dfab68f6f76.gif)|![ezgif com-gif-maker (21)](https://user-images.githubusercontent.com/4410346/98143656-37741880-1e7e-11eb-8999-c35696dcfdf4.gif)|
Created and start a few server experiments with the use of new UI.
=> serverexperimentation: combine all steps of start-experiment into one step

frontend/workflows/experimentation/src/core/page-layout.tsx, frontend/workflows/experimentation/src/index.tsx, frontend/workflows/experimentation/src/list-experiments.tsx, frontend/workflows/experimentation/src/view-experiment-run.tsx, frontend/workflows/experimentation/tsconfig.json, frontend/workflows/serverexperimentation/package.json, frontend/workflows/serverexperimentation/src/start-experiment.tsx, frontend/workflows/serverexperimentation/tsconfig.json
Use the same page layout with a heading positioned in the top-left corner in all of the screens that are implemented as part of `experimentation` and `serverexperimentation` packages.
| ----- | ----- |
|<img width="1144" alt="Screen Shot 2020-11-04 at 7 16 28 PM" src="https://user-images.githubusercontent.com/4410346/98193818-e4788080-1ed2-11eb-8d09-b231f42808c8.png">|<img width="1139" alt="Screen Shot 2020-11-04 at 6 54 54 PM" src="https://user-images.githubusercontent.com/4410346/98193849-ef331580-1ed2-11eb-9a8e-52eece52f271.png">|
|<img width="1135" alt="Screen Shot 2020-11-04 at 7 16 36 PM" src="https://user-images.githubusercontent.com/4410346/98193865-f823e700-1ed2-11eb-93c3-8880adeeaf11.png">|<img width="1140" alt="Screen Shot 2020-11-04 at 7 17 54 PM" …
=> experimentation: consistent page layout

frontend/packages/core/src/AppLayout/user.tsx
jwt-decode released v3.1.1 this morning which included [type support](https://github.com/auth0/jwt-decode/commit/c9eaa4f880bb3638eddc631371010f7022436b10). `jwtDecode` now returns unknown and therefore fails typescript builds.
This defines the expected token props we rely on.
manually built
=> frontend: add types for JWT Token

frontend/netlify/netlify.toml
Fixes the [component website](https://clutch-components.netlify.app/) that can't load at the moment since Storybook loads it's content in an iframe.
=> storybook: remove iframe deny header

api/config/service/k8s/v1/k8s.proto, backend/api/config/service/k8s/v1/k8s.pb.go, backend/service/k8s/clientset.go
Add additional config documentation. Also make the code a little easier to read, wrap error conditions for easier location of error origin.
Result of Slack thread https://lyftoss.slack.com/archives/C015UJ6LED9/p1604370159024700:
```
2020-11-03T02:07:29.406Z	INFO	k8s/clientset.go:86	no kubeconfig was found, falling back to InClusterConfig	{"serviceName": "clutch.service.k8s"}
2020-11-03T02:07:29.406Z	FATAL	gateway/gateway.go:109	service instantiation failed	{"serviceName": "clutch.service.k8s", "error": "open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory"}
github.com/lyft/clutch/backend/gateway.RunWithConfig
/go/src/github.com/lyft/clutch/backend/gateway/gateway.go:109
github.com/lyft/clutch/backend/gateway.Run …
```
=> k8s: improve docs and error handling

frontend/workflows/serverexperimentation/src/form-fields.tsx, frontend/workflows/serverexperimentation/src/start-experiment.tsx
- Fix an issue that made all server experiments to inject faults on upstream, even if an upstream cluster was an external cluster.
- Add default values for `faultInjectionCluster` and `faultType` to make it easier to reason about the state of start experimentation screen.
Manual testing.
=> experimentation: fix the selection of FaultInjectionCluster

frontend/packages/core/src/AppProvider/themes.tsx
The built-in transitions for MUI components are largely incompatible with V2 components and require a lot of extra work to get right. We will disable transitions globally for MUI components in UI V2.
Theme props from https://material-ui.com/getting-started/faq/#how-can-i-disable-transitions-globally
=> ui v2: disable transitions

frontend/packages/core/package.json, frontend/workflows/experimentation/package.json, frontend/workflows/k8s/package.json, frontend/workflows/serverexperimentation/package.json, frontend/workflows/sourcecontrol/package.json, frontend/yarn.lock
We need to bump yup to v0.31.0 (from v0.30.0 that was introduced in https://github.com/lyft/clutch/pull/692). The bug that was introduced in v0.30.0 and breaks form validation in server-experimentation package (and possibly other places). It was fixed in https://github.com/jquense/yup/issues/1122.
| Before | After | 
| ----- | ------ |
| ![ezgif com-gif-maker (27)](https://user-images.githubusercontent.com/4410346/100124683-d3b38e80-2e30-11eb-863f-81d2773675e9.gif) | ![ezgif com-gif-maker (28)](https://user-images.githubusercontent.com/4410346/100124712-db733300-2e30-11eb-8d1e-5cdee724e4a2.gif) |
=> core: bump yup to v0.31.0

frontend/packages/core/src/Input/radio-group.tsx
Make it possible to disable `RadioGroup`.
See attached GIF.
=> core: add disabled property to RadioGroup

backend/cmd/migrate/migrate.go, backend/cmd/migrate/migrate_test.go, backend/cmd/migrate/testdata/clutch-config-test.yaml
Refactoring the db migration tool to make it easier to implement the `down` migration, the behavior is exactly the same.
unit / local.
Starting with an empty db
```
clutch=# \dt
Did not find any relations.
```
```
➜ go run migrate.go -c ./testdata/clutch-config-test.yaml
2020-11-18T16:08:32.334-0800	INFO	migrate/migrate.go:90	using database	{"hostInfo": "clutch@0.0.0.0:5432"}
2020-11-18T16:08:32.335-0800	WARN	migrate/migrate.go:92	migration has the potential to cause irrevocable data loss, verify host information above
*** Continue with migration? [y/N] y
2020-11-18T16:08:48.355-0800	INFO	migrate/migrate.go:134	applying migrations	{"migrationDir": "/Users/mcutalo/gocode/src/github.com/lyft/clutch/backend/cmd/migrate/migrations"}
2020-11-18T16:08:48.361-0800	INFO	migrate/migrate.go:43 …
```
=> tools: refactor db migration logic

backend/mock/service/githubmock/githubmock.go, backend/service/github/github.go
Add base name parameter to the Github `CreatePullRequest` function to replace hardcoded value. This enables clients to pass alternate names for the target base branch when creating pull requests. Primary purpose is to enable name convention swap from `master` to `main` while still supporting legacy repositories.
Local manual testing against two different repos with different base branch names.
Fixes [issue #724](https://github.com/lyft/clutch/issues/724)
=> github: add base name parameter for CreatePullRequest function

frontend/packages/core/src/Resolver/index.tsx, frontend/packages/core/src/horizontal-rule.tsx, frontend/packages/core/src/stories/horizontal-rule.stories.tsx
Adds a horizontal rule that accepts children for display in the middle. 
Storybook
=> ui v2: horizontal rule

frontend/packages/core/src/Input/radio-group.tsx, frontend/packages/core/src/Input/radio.tsx, frontend/packages/core/src/Input/stories/radio.stories.tsx
Add new radio button component and update radio group to use it.
storybook
=> ui v2: radio button

frontend/packages/core/src/Input/select.tsx, frontend/packages/core/src/Input/stories/select.stories.tsx, frontend/packages/core/src/index.tsx
Implement the v2 Figma designs.
Storybook.
=> ui v2: select

frontend/packages/core/src/Table/index.tsx, frontend/packages/core/src/Table/metadata-table.tsx, frontend/packages/core/src/Table/stories/metadata-table.stories.tsx, frontend/packages/core/src/index.tsx, frontend/workflows/envoy/src/server-info.tsx
Restyle metadata table.
storybook
=> ui v2: restyle metadata table

frontend/packages/core/src/button.tsx
Color and padding fixes
Storybook.
=> ui v2: button style updates

frontend/packages/core/src/accordion.tsx, frontend/packages/core/src/stories/accordion.stories.tsx
=> ui v2: accordion

frontend/packages/core/src/Input/checkbox.tsx, frontend/packages/core/src/Input/stories/checkbox-panel.stories.tsx, frontend/packages/core/src/Input/stories/checkbox.stories.tsx, frontend/packages/core/src/index.tsx
PR
* adds new designs for the checkbox component
* adds checkbox story
design is restyling the checkbox, so for now, added the design for what's highlighted in the dotted border. 
storybook
=> ui v2: checkbox

frontend/packages/core/src/accordion.tsx, frontend/packages/core/src/stories/accordion-group.stories.tsx, frontend/packages/core/src/stories/accordion.stories.tsx
Add a mutually exclusive expanded accordion group.
Storybook.
=> ui v2: accordion group

frontend/packages/core/src/Input/text-field.tsx, frontend/packages/core/src/button.tsx, frontend/packages/core/src/dialog.tsx, frontend/packages/core/src/index.tsx, frontend/packages/core/src/stories/dialog.stories.tsx, frontend/workflows/serverexperimentation/src/start-experiment.tsx
=> ui v2: restyle dialog component

backend/service/k8s/cache.go, backend/service/k8s/lightweightinformer.go, backend/service/k8s/lightweightinformer_test.go
For large Kubernetes deployments reacting to all informer events can put a lot of load on the datastore, the motivation behind this change is to reduce load.
Currently we handle all updates to pods for the topology caching but we dont currently need that level of granularity, requirements can change in the future and we can think about making these configuration options if use cases arise.
This was tested locally.
=> k8s: option to receive informer updates

frontend/packages/core/src/AppLayout/stories/header.stories.tsx, frontend/packages/core/src/AppLayout/stories/searchfield.stories.tsx, frontend/packages/core/src/AppLayout/stories/user-information.stories.tsx
PR updates:
* header story to add workflow data so that Design can better test the components
* searchfield story's background to match what it'd look like on the header
Storybook
=> ui v2: update AppLayout stories

frontend/packages/core/src/accordion.tsx
if `defaultExpanded` was true, the value would always be true so the accordion would never collapse. `useControlled` properly manages the state without the need for the OR to set the initial val.
Storybook.
=> ui v2: fix accordion bug

backend/service/k8s/cache.go, backend/service/k8s/lightweightinformer.go, backend/service/k8s/lightweightinformer_test.go
Disabling Resync for the LightweightInformer, as it does not provide any value. In additionally it was causing `lightweightCacheObject` objects to be passed through the topology pipeline throwing warnings like the one below.
Resyncing compares whats currently in the DeltaFIFO queue and what currently resides in cache, if the queue does not have an item that cache has, it will requeue it so the informer has a chance to reprocess that item. Resync is of no value here as `lightweightCacheObject` _never_ reside in the DeltaFIFO queue as that queue is only populated from the ListAndWatch Streams coming from the kube api. By resyncing we force items in cache to end up in the queue which ultimately produce the warning below.
> {"level":"warn","ts":1607102729.4194083,"caller":"k8s/cache.go:149","m …
=> k8s: LightweightInformer disable resync

frontend/packages/core/src/Input/stories/text-field.stories.tsx, frontend/packages/core/src/Input/text-field.tsx
Add support to text fields for end adornment
In dev app and storybook
=> ui v2: add end adornment support to text fields

docs/configuration.md
Reported in Slack: https://lyftoss.slack.com/archives/C015UJ6LED9/p1607788759067900.
> (1) session_secret appears at the same level as oidc, but the code has it one level above (and c&p fails because of that), is that an oversight or am I missing something?
Docs render.
=> docs: fix authn config example

frontend/packages/core/src/AppLayout/search.tsx
PR fixes 2 bugs for the header searchfield component:
(1) The [result component](https://github.com/lyft/clutch/blob/main/frontend/packages/core/src/AppLayout/search.tsx#L90) has the onClick event to navigate to a workflow. The issue was that its Grid did not match the parent height (see gif). So if you did not click exactly within the result Grid, you were not navigated to a workflow.
Solution: Have the result Grid inherit the height of its parent (autocomplete option container)
(2) If you chose a workflow by pressing the enter/return key, the header search bar would remain open. The expected behavior is for the searchbar to collapse back to the search icon when a result option is selected, like the mouse click behavior.
Solution: Add a `onKeyDown` event to update the `open` state
Local …
=> ui v2: fix searchfield bugs

frontend/packages/core/src/AppLayout/stories/user-information.stories.tsx, frontend/packages/core/src/AppLayout/user.tsx
PR:
* updates header & menu avatar
* follows up on todo for adding interface for rendering menu items
Storybook
Storybook, local app
=> ui v2: update UserInformation component

frontend/packages/app/src/clutch.config.js, frontend/packages/core/src/Input/select.tsx, frontend/packages/core/src/Resolver/index.tsx, frontend/packages/core/src/Resolver/input.tsx, frontend/packages/core/src/Table/metadata-table.tsx, frontend/packages/core/src/accordion.tsx, frontend/packages/core/src/button.tsx, frontend/packages/core/src/confirmation.tsx, frontend/packages/core/src/index.tsx, frontend/packages/wizard/package.json, frontend/packages/wizard/src/step.tsx, frontend/packages/wizard/src/wizard.tsx, frontend/workflows/ec2/src/index.tsx, frontend/workflows/ec2/src/terminate-instance.tsx
Restyle the terminate instance workflow.
This doesn't include all the final touches. This is just the major style changes. There are still a few minor things to fix along the way include:
- The accordion group has a top border that is rendering when it's a child
- The metadata keys on the confirmation page need to converted to either hard coded strings or normalized
- Fix breakpoints for responsive devices
manually
=> ui v2: restyle terminate instance

frontend/packages/core/src/Input/stories/toggle.stories.tsx, frontend/packages/core/src/Input/toggle.tsx
Add switches component. 
Due to https://github.com/strothj/react-docgen-typescript-loader/issues/113 the filename cannot be switch.
storybook
=> ui v2: switches

frontend/packages/core/src/Input/toggle.tsx, frontend/packages/core/src/button.tsx, frontend/packages/core/src/stories/button-group.stories.tsx, frontend/packages/wizard/src/wizard.tsx, frontend/workflows/ec2/src/reboot-instance.tsx, frontend/workflows/ec2/src/resize-asg.tsx, frontend/workflows/ec2/src/terminate-instance.tsx, frontend/workflows/envoy/src/remote-triage.tsx, frontend/workflows/experimentation/src/list-experiments.tsx, frontend/workflows/experimentation/src/view-experiment-run.tsx, frontend/workflows/k8s/src/delete-pod.tsx, frontend/workflows/k8s/src/resize-hpa.tsx, frontend/workflows/kinesis/src/update-shard-count.tsx, frontend/workflows/serverexperimentation/src/start-experiment.tsx
Update button group to take `Button` as children instead of using a prop.
Manual and storybook
=> ui v2: button group

frontend/packages/core/src/Resolver/input.tsx, frontend/packages/core/src/accordion.tsx, frontend/workflows/k8s/src/delete-pod.tsx
Restyle delete pod workflow
Manual
=> ui v2: restyle delete pod workflow

backend/module/chaos/serverexperimentation/rtds/rtds_cache.go
Small change to alter the log level as it can produce a lot of logs in a large deployment as we have seen internally.
Unit.
=> experimentation: tune rtds removing faults log level

backend/middleware/middleware_test.go
Demonstrate and ensure the proper use of a super wildcard `**` on the resource matcher.
It is a test.
=> middleware: resource matcher tests with super wildcard

frontend/packages/core/src/Resolver/input.tsx, frontend/packages/core/src/Table/metadata-table.tsx, frontend/packages/core/src/Table/stories/metadata-table.stories.tsx, frontend/packages/core/src/accordion.tsx, frontend/workflows/ec2/src/resize-asg.tsx, frontend/workflows/ec2/src/terminate-instance.tsx, frontend/workflows/k8s/src/delete-pod.tsx, frontend/workflows/k8s/src/resize-hpa.tsx
PR
* adds style updates made in https://github.com/lyft/clutch/pull/781 to the resize workflows (EC2 & K8S)
* updates MutableRow to have disabled text field and icon
* updates EC2 term instance confirmation page to use `useDataLayout.displayValue`
* adds MutableRow story
Resize ASG
Resize HPA
Locally
=> ui v2: restyle resize workflows

frontend/packages/core/src/Resolver/fetch.tsx, frontend/packages/core/src/Resolver/index.tsx
Allow workflows to specify optional Resolver prop to override the API proto used to resolve schema type lookups and response objects against.
Manual
Fixes #
=> frontend: allow override of resolver api package

frontend/packages/app/src/index.css, frontend/packages/core/src/Resolver/index.tsx, frontend/packages/core/src/Resolver/input.tsx, frontend/packages/core/src/dialog.tsx, frontend/packages/core/src/error.tsx, frontend/packages/core/src/horizontal-rule.tsx, frontend/packages/core/src/loading.tsx, frontend/packages/core/src/stepper.tsx, frontend/packages/wizard/src/wizard.tsx
Moving the QueryResolver < form > element into the child similar to the SchemaResolver.
Had to change some margin rules around. Need to add it back.
Also significant changes to stepper to fix alignment by recombining labels and icons.
dev
=> ui v2: resolver refactor and other polish

frontend/packages/core/src/AppLayout/search.tsx
The error was coming from here:
https://github.com/lyft/clutch/blob/UIV2/frontend/packages/core/src/AppLayout/search.tsx#L136
Since we toggle between rendering the search icon or search bar, we need to add a null check for `searchRef.current`. Otherwise, once the search bar is collapsed, the `handleKeyPress` will still allow the `\` to focus the input field which isn't rendered.
Open to other suggestions for fixing the bug! 
Steps to reproduce bug on ui v2 master:
* open searchbar
* click into it
* close out of the searchbar
* press `/` key
=> ui v2: fix header searchfield bug

frontend/packages/core/src/stories/tab.stories.tsx, frontend/packages/core/src/stories/tabs.stories.tsx, frontend/packages/core/src/tab.tsx
Introduce tab & tabs components
Storybook
=> ui v2: tabs

frontend/packages/core/src/AppLayout/drawer.tsx
Implement stop gap solution to prevent text overflow on drawer. Following up on longer term solution with design [here](https://lyftoss.slack.com/archives/C015UJ6LED9/p1608581951140400)
**Before**
**After**
manual
Fixes #
=> ui v2: trim long group headings

frontend/packages/core/src/stories/tabs.stories.tsx, frontend/packages/core/src/tab.tsx
Support tab content as children within a `Tab` component.
Additional changes include:
- css fixes for tab labels (figma uses roboto medium)
- remove text transform from tab
- move onto experimental TabContent, TabList, and TabPanel to make maintaining tabs state easier
- remove onChange prop from tabs since we maintain state internally now. Decided to move this state within the component because I cannot think or a reason that consumers of this component would need to know when these changes occur.
Storybook and manual
=> ui v2: support content within tabs

frontend/packages/core/src/Table/stories/table.stories.tsx, frontend/packages/core/src/Table/table.tsx
Restyle table
**note**: the header row has background color but it is not visible in the gif below.
Storybook
=> ui v2: table

frontend/packages/core/src/Input/stories/radio-group.stories.tsx
Minor change to move the radio group story into the correct directory
=> ui v2: fix radio group story location

frontend/packages/core/src/AppLayout/drawer.tsx
Trimmed headings don't match when attempting to open their content. This fixes that.
manual
=> ui v2: fix drawer panel opening

frontend/packages/core/src/dialog.tsx
Fix layout spacing of Dialog heading to left and right justify content.
**current**
**after PR**
manual
=> ui v2: fix layout spacing of dialog heading

frontend/packages/core/src/Input/radio-group.tsx
Remove max width prop from radio group since it shouldn't be needed.
=> ui v2: remove max width from radio group

frontend/packages/core/src/button.tsx, frontend/packages/core/src/stories/button-group.stories.tsx
There may be times when we want the button group border to be below the buttons (e.g. if the buttons are a heading to something as in the photo below)
manual and story
=> ui v2: allow button group border movement

frontend/packages/wizard/src/step.tsx
Use margin over padding for wizard steps to prevent misaligning children
manual
=> ui v2: use margin for wizard steps

frontend/packages/core/src/button.tsx
Minor style updates and interface changes to clipboard button.
Storybook and manual
=> ui v2: clipboard button

frontend/packages/core/src/stepper.tsx, frontend/packages/core/src/stories/stepper.stories.tsx
Fix stepper error behavior to show a steps error when it happens instead of on the next step.
=> ui v2: fix stepper failed step index

frontend/packages/core/src/Contexts/wizard-context.tsx, frontend/packages/wizard/src/step.tsx, frontend/packages/wizard/src/wizard.tsx
Propagate errors from step to wizard in order to correctly display error icon on the stepper and to display a reset button.
manual
=> ui v2: add wizard step error handling

frontend/packages/core/src/tab.tsx
Restrict TabPanel width to 100% of its parent. This prevents tab panel content from growing beyond the parent and overflowing.
manual
=> ui v2: restrict tab panel width to 100%

frontend/packages/core/src/Feedback/alert.tsx
Ensure alert message uses 100% of the available width.
manual
=> ui v2: alert message should be 100% width

frontend/packages/app/src/index.css, frontend/packages/core/src/Input/text-field.tsx
Define css applied to inputs when autofill occurs.
This also updates the TextField input color to match the figma designs
manual
=> ui v2: remove input styling from webkit autofill

frontend/packages/core/src/Resolver/hydrator.tsx
Fixes warning in console where the resolver hydrator maps elements and select is missing a key
locally
=> ui v2: add key to Resolver hydrator select element

tools/kind.sh
This PR adds a service resource in the kind script to enable local dev testing with service objects
Local Testing:
```
Creating fake resources in clutch-local k8s cluster
Error from server (AlreadyExists): namespaces "envoy-staging" already exists
Error from server (AlreadyExists): deployments.apps "envoy" already exists
Error from server (AlreadyExists): horizontalpodautoscalers.autoscaling "envoy" already exists
service/envoy exposed
Error from server (AlreadyExists): namespaces "envoy-production" already exists
Error from server (AlreadyExists): deployments.apps "envoy" already exists
Error from server (AlreadyExists): horizontalpodautoscalers.autoscaling "envoy" already exists
service/envoy exposed
```
=> K8s: add a k8s service resource to kind script

frontend/workflows/ec2/src/reboot-instance.tsx, frontend/workflows/ec2/src/resize-asg.tsx, frontend/workflows/ec2/src/terminate-instance.tsx, frontend/workflows/k8s/src/delete-pod.tsx, frontend/workflows/k8s/src/resize-hpa.tsx
Addresses bug bash action items:
* adds note panels to workflows that had the notes as plain text
* splits up the annotations and labels into their own accordions
* updates stepper titles
Locally
=> ui V2: add note panel, split metadata

frontend/packages/core/src/Input/text-field.tsx
Change background color of text fields to be white instead of transparent.
Local
=> ui v2: text field white background

frontend/packages/core/src/Table/metadata-table.tsx
Address bug bash item:
* text field validations in the metadata table were not rendering correctly
before
now
longer errors
default
Locally
=> ui v2: metadata input validation bug

frontend/packages/core/src/Feedback/alert.tsx, frontend/packages/core/src/Feedback/note.tsx
Update Note and NotePanel to use new alert component. Fix max width of alerts and overflow.
manual
=> ui v2: use new alert for note panel and fix layout max width

frontend/packages/core/src/card.tsx
Removes uppercasing of card headers to match the sidebar grouping titles
* addresses K8S -> K8s bug bash item
Locally
=> ui v2: fix capitalization on cards

frontend/packages/core/src/accordion.tsx
Fixes issue when accordion overflows its parent container, which happens when there are long strings of text that do not have an acceptable break (ie space, hyphen).
before
now
Locally and checked stories to make sure it didn't break other functionality/designs
=> ui V2: fix accordion overflow

frontend/packages/core/src/Input/text-field.tsx
Address bug bash action item
* updates the text field icon button to be blue
Locally
=> ui v2: change textfield icon button color

frontend/workflows/ec2/src/resize-asg.tsx, frontend/workflows/k8s/src/resize-hpa.tsx
add validation to resize workflows such that the max value does not go below the min value
manual
=> ui v2: validate max sizes are greater than min in resize workflows

frontend/packages/core/src/button.tsx
Reduce button group margin
manual
=> ui v2: reduce button group margin

frontend/packages/core/src/Input/select.tsx
Enforce Select background is white.
manual
=> ui v2: select background should be white

docs/development/feature.md
Removing duplicated highlight in docs as outlined in #449 
N/A
Fixes #449
=> docs: remove duplicate highlight in code snippet

backend/module/resolver/resolver.go, backend/module/resolver/response.go, backend/module/resolver/response_test.go
Create a common response object so we get common error handling, truncation of extra results, etc.
Before there was a bug where Search properly removed partial failures with a limit met but Resolve did not.
Moving the code to a common object will ensure both calls are handled the same way.
Unit, manual.
=> resolver: use common response object

frontend/packages/core/src/Feedback/warning.tsx
invoke onClose before the snackbar exits. This allows for the wizard to reset warnings after they have been dismissed.
manaul
=> ui v2: warning invoke onClose before exiting

frontend/package.json, tools/scaffolding/templates/gateway/frontend/package.json
This prevents previously compiled assets from taking precedence when running the frontend dev server.
manual
=> frontend: clean assets before running dev server

frontend/workflows/ec2/src/resize-asg.tsx, frontend/workflows/k8s/src/resize-hpa.tsx
This PR contains two changes:
- Modify both resize hpa and asg workflows to allow max sizes to equal min
- Fix k8s validation to properly block on errors
manual
=> resize workflows: fix max number & k8s submission validation

.github/workflows/api.yml, .github/workflows/backend.yml, .github/workflows/scaffolding.yml
Updating CI to use the latest version of go (1.15.6)
=> CI: update go version to 1.15.6

tools/kind.sh
Add a cronjob resource to the kind script to test newly added cronjob APIs
https://github.com/lyft/clutch/pull/793
Local spin up of k8s cluster
```
Creating fake resources in clutch-local k8s cluster
Error from server (AlreadyExists): namespaces "envoy-staging" already exists
namespace/cron-staging created
...
cronjob.batch/cron-test created
namespace/cron-production created
...
cronjob.batch/cron-test created
$ kubectl get all -n cron-staging
NAME                             READY   STATUS      RESTARTS   AGE
pod/cron-test-1610557380-czc2n   0/1     Completed   0          24s
NAME                             COMPLETIONS   DURATION   AGE
job.batch/cron-test-1610557380   1/1           6s         24s
NAME                      SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE …
```
=> k8s: add cronjob to kind script

frontend/packages/core/src/Table/metadata-table.tsx
Resolving these warnings raised. The MutableRow Grid had props that can only be set if the `container` prop was set.
Locally
=> frontend: Fix metadata-table grid props

backend/middleware/timeouts/timeouts.go, backend/middleware/timeouts/timeouts_test.go
The race technically still exists and is unavoidable without some really unnecessary synchronization, so I had to boost the timeouts on the test. However **when the race occurs there will no longer be a panic**, instead it will just return the value.
If we make boost configurable we could create a brute force test to try and hit the race to ensure no panic ever occurs as a counter-test for that scenario. But with boost fixed at 50ms it would take too much unnecessary test time to do that.
CI + manual `-count 1000` several times
=> middleware: fix timeout race panic

frontend/packages/core/src/AppLayout/search.tsx
A bug bash fix
* PR adds the `autofocus` prop to the textfield component so that it's already focused when the search bar is open.
https://material-ui.com/api/text-field/#textfield-api
Locally
=> frontend: autofocus input element in header search bar

frontend/packages/tools/.eslintrc.js
Allow nested "extraneous imports" for tools' eslintrc
Local, CI.
=> frontend: allow eslintrc extra import wildcard

frontend/packages/core/src/Resolver/input.tsx
Fix an issue in `SchemaResolver` where initial field values would be overwritten by default data.
manual
=> frontend: fix resolver schema data race condition

frontend/package.json
Testing out build times without parallel lerna commands. In theory TSC dependencies need to be built in order anyways so this appears to be a micro-optimization but consumes a large amount of resources. 
CI
=> frontend: remove parallel flag from compilations

frontend/packages/core/src/AppProvider/workflow.tsx, frontend/packages/core/src/dialog.tsx, frontend/packages/core/src/stories/dialog.stories.tsx, frontend/workflows/serverexperimentation/src/start-experiment.tsx, frontend/workflows/serverexperimentation/src/tests/__snapshots__/start-experiment.test.tsx.snap
Fix a bug with the  closing behavior of the Dialog frontend component: Closing the modal via ESC, the X button, or clicking the backdrop got the the modal stuck in an OFF state and unable to appear again.
The component now accepts an optional `onClose` callback. This callback can be used to set the `open` prop passed into `Dialog`. If this callback exists, the component will rely on the `open` prop alone to show/hide. Otherwise, the old functionality is preserved where the component will use its own internal `isOpen` state.  Warning: With the latter use case, closing the dialog with the Escape key, clicking on the backdrop, or using the "X" button will cause the modal to be stuck in the off state.
https://github.com/lyft/clutch/pull/674
https://github.com/lyft/clutch/pull/823
Storybook
=> frontend: fix dialog closing behavior

docs/_website/docusaurus.config.js, docs/_website/src/theme/Navbar/index.js, docs/development/frontend.md
Adds links to component website in clutch.sh header and on frontend development page.
=> docs: add component library links

backend/cmd/migrate/README.md, backend/cmd/migrate/migrate.go
Allows federated migrations, in a different directory, on different schemas. See linked issue for more details.
```
$ go run migrate.go -namespace foo -migrationDir migrations -c ../../../examples/postgres-config/clutch-config.yaml 
2021-01-27T13:53:07.885-0600    INFO    migrate/migrate.go:129  using migration table   {"migrationTable": "schema_migrations_foo"}
2021-01-27T13:53:07.887-0600    INFO    migrate/migrate.go:147  using migration directory       {"migrationDir": "migrations"}
2021-01-27T13:53:07.887-0600    INFO    migrate/migrate.go:97   using database  {"hostInfo": "clutch@localhost:5432"}
2021-01-27T13:53:07.887-0600    WARN    migrate/migrate.go:99   migration has the potential to cause irrevocable data loss, verify information above
*** Continue with migration? [y/N]
``` …
=> db: enhance migrate tooling to allow federated migrations

frontend/packages/data-layout/src/manager.tsx
`Missing depedency for data layout` => `Missing dependency for data layout`
=> typo fix in data-layout

backend/resolver/k8s/k8s.go
Remove the IP address resolver for the pod deletion URL
Tested locally to ensure the IP address resolver does not show up
=> resolver: remove k8s IP address resolver for Pod

docs/_website/src/theme/BlogPostItem/index.js
Fixes
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `BlogPostItem`. See https://fb.me/react-warning-keys for more information.
``
=> docs: fix key warning rendering blog authors

.github/workflows/license_review.yml, tools/license-finder/config/license_dependency_decisions.yml
License check is failing in PRs.
```
Dependencies that need approval:
github.com/DATA-DOG/go-sqlmock, v1.5.0, unknown
Error: Process completed with exit code 1.
```
CI.
=> ci: add go-sqlmock license

tools/air.sh
```bash
> make backend-dev
tools/air.sh
__    _   ___  
/ /\  | | | |_) 
/_/--\ |_| |_| \_ 1.15.1 // live reload for Go apps, with Go 1.15.5
.
.
.
.
.
failed to watching lyft/clutch/backend/service/chaos/experimentation/experimentstore, error: too many open files
```
Relates to https://github.com/cosmtrek/air/issues/32 which is due to the underlying issue https://github.com/fsnotify/fsnotify/issues/129
locally
=> tools: increase FD limit on OSX for air

frontend/packages/core/src/AppLayout/drawer.tsx
Use css to handle overflow of drawer titles and set height to fit the content given we allow wrapping spaces
manual
=> frontend: fix drawer title overflow

frontend/packages/core/src/Table/table.tsx, frontend/packages/core/src/dialog.tsx
- Added onClick handler to TableRow
- Changed max-width of Dialog Paper to fit-content and added min-width: 600px
Needed for some extra flexibility in styling and functionality
Locally
=> frontend: Add onClick handler to TableRow and Change max-width of Dialog

frontend/packages/core/src/accordion.tsx
Use margin to offset accordion detail children instead of padding as this is less intrusive on the children's layout. With padding set you could have an element with a border that is now offset by 8px. This fixes that use case.
manual
=> frontend: fix accordion detail children layout

frontend/packages/data-layout/src/layout.tsx
Fix bug where previous error state would be presented when a workflow was retried.
manual
=> data layout: reset error state on load

frontend/packages/data-layout/src/state.tsx, frontend/packages/data-layout/src/tests/state.test.tsx
This fixes a bug where existing data set on a data layout will be overwritten when a hydrate response returns.
manually
Fixes #152
=> frontend: fix data-layout data preservation after hydration

backend/gateway/log/log.go, backend/gateway/log/log_test.go
PR adds a new error log handler that can (1) unpack a gRPC error and return the Status or (2) return the original error.
Unit tests
Locally
**examples**
1) a conventional error
```
ERROR   k8s/job.go:33   error deleting Job      {"serviceName": "clutch.service.k8s", "error": "jobs.batch \"foo\" not found"}
```
2) a gRPC error
```
ERROR   k8s/job.go:35   error deleting Job      {"serviceName": "clutch.service.k8s", "error": {"code":5,"message":"Job not found"}}
```
3) a gRPC error showing the extra details that had been appended to the Status
```
ERROR   k8s/job.go:36   error deleting Job      {"serviceName": "clutch.service.k8s", "error": {"code":5,"message":"Job not found","details":[{"@type":"type.googleapis.com/google.rpc.ResourceInfo","resourceType":"Job","description":"foo not …
```
=> gateway: error log handler

backend/module/chaos/serverexperimentation/xds/xds_cache.go, backend/module/chaos/serverexperimentation/xds/xds_cache_test.go
Currently, RTDS updates runtime on the downstream cluster when it's supposed to update on the upstream cluster and vice versa. This bug prevents from running fault injection tests. This PR fixes it along with some improved logging. 
Locally performed testing
Fixes #
=> serverexperimentation: fix fault injection bug

frontend/workflows/serverexperimentation/src/start-experiment.tsx, frontend/workflows/serverexperimentation/src/tests/__snapshots__/experiment-details.test.tsx.snap
The `upstreamClusterType` was no longer being updated when selecting one of the values from the radio group. This fixes the bug, and I have some ideas on how to refactor our React code to follow paradigms to prevent this kind of logic leak.
When migrating our fields, we didn't update the property name passed into the onChange() prop function in the <RadioGroup> component.
Tested locally by verifying state in <ExperimentDetail> before & after.
=> Fix incorrect name attached to cluster radio group props

frontend/packages/data-layout/src/state.tsx, frontend/packages/data-layout/src/tests/state.test.tsx
Update data-layout to only merge existing data and new data when the types are the same.
added tests
=> frontend: data-layout only merge data of same types on hydration end

frontend/packages/core/src/Input/text-field.tsx
When select an item from the list of auto complete options, we were not triggering the `onChange` handler which is necessary to propagate the value of the selected item up to the consumer of the component.
locally
=> frontend: autocomplete propagate onChange event

backend/mock/service/githubmock/githubmock.go, backend/service/github/github.go, backend/service/github/github_test.go, backend/service/github/iface.go
Add functions to github service to be consumed by the sourcecontrol module for listing out a users available organizations.
CI
=> backend: add organization functions to github service

frontend/packages/core/src/Resolver/input.tsx
Currently if the user empties out their search query, the frontend will still trigger a query for an empty string `""`. The resolver autocomplete api requires the `search` field be at least one byte which produces a 400 error.
eg:
```{"code":3,"message":"invalid AutocompleteRequest.Search: value length must be at least 1 bytes","details":[]}```
locally
=> frontend: autocomplete dont query on empty string

backend/gateway/core.go, backend/module/chaos/redisexperimentation/redis_experimentation.go
Create a module class for redis experimentation to transform [RedisFaultConfig experiment configs](https://github.com/lyft/clutch/pull/1020) to a consumable format for the frontend list and detail UIs. 
Test locally with frontend to make sure that Redis faults are returned.
=> chaos: serve up information on redis experimentation in list/detail view

backend/service/topology/cache.go, backend/service/topology/cache_test.go, backend/service/topology/topology.go
We keep a separate database connection just for the topology cache advisory locks which are utilized when performing leader election. If there is any interruption to the database such a failover we were unable to reconnect and start operating normally again.
```
INFO	gateway/gateway.go:57	using configuration	{"file": "clutch-config.yaml"}
INFO	gateway/gateway.go:106	registering service	{"serviceName": "clutch.service.db.postgres"}
INFO	gateway/gateway.go:106	registering service	{"serviceName": "clutch.service.envoyadmin"}
INFO	gateway/gateway.go:106	registering service	{"serviceName": "clutch.service.topology"}
INFO	topology/topology.go:90	Topology caching is enabled	{"serviceName": "clutch.service.topology"}
INFO	gateway/gateway.go:168	registering middleware	{"moduleName": …
```
=> topology: cache to retry db connection

backend/mock/service/topologymock/topologymock.go, backend/resolver/aws/aws.go, backend/resolver/aws/aws_test.go, backend/resolver/k8s/k8s.go, backend/service/topology/topology.go
Adds basic autocomplete to all kubernetes workflows. This also includes a small refactor to abstract some of the boilerplate of the topology search request away.
Locally.
This makes progress on issues #921 and #30.
=> resolver: kubernetes autocomplete

backend/module/k8s/job.go, backend/service/k8s/clientset.go, backend/service/k8s/configmap.go, backend/service/k8s/cronjob.go, backend/service/k8s/deployment.go, backend/service/k8s/hpa.go, backend/service/k8s/pods.go, backend/service/k8s/service.go, backend/service/k8s/statefulset.go
Replaces all uses of `fmt.Errorf` and `errors.New` in the `k8s` service and module with their proper gRPC status and code.
This will ensure accurate metrics and sensible error information is displayed to the user.
Manual audit.
=> k8s: always return a gRPC status

.github/workflows/stale.yaml
Close stale PRs after a week of inactivity unless they have the `on hold` label. This will make it easier to see what PRs are active at a glance.
Can perform manual run in dry run mode after merge.
=> ci: stale bot

backend/service/k8s/cache.go, backend/service/k8s/lightweightinformer.go, backend/service/k8s/lightweightinformer_test.go
Upstream Kubernetes does not populate the `ClusterName` on the [ObjectMeta](https://github.com/kubernetes/apimachinery/blob/2456ebdaba229616fab2161a615148884b46644b/pkg/apis/meta/v1/types.go#L266-L270), this is useful information that we can utilize and we can easily populate this information before writing the object to cache.
This is also required to complete autocomplete for kubernetes workflows as we are now utilizing the proto patterns defied in resource as the structure for a workflows query input https://github.com/lyft/clutch/blob/a2e4ac8644837a1260b39c7c7c2e20cac465c85c/api/k8s/v1/k8s.proto#L406
here is an example of one, but all kubernetes resources do and should require `cluster` in their pattern.
You can now see the `cluster` field is now populated
```
clutch=# select …
```
=> kubernetes: add cluster info to all cached resources

backend/cmd/migrate/migrations/000008_topology_cache_add_composite_key.down.sql, backend/cmd/migrate/migrations/000008_topology_cache_add_composite_key.up.sql, backend/service/topology/cache.go
The unique identifier of `id` is not enough to uniquely identify a resource in kubernetes. Even if we are using the protos object pattern for example deployment. https://github.com/lyft/clutch/blob/a2e4ac8644837a1260b39c7c7c2e20cac465c85c/api/k8s/v1/k8s.proto#L406
This lacks information about which is resource type the `id` belongs to. In Kubernetes it's a common pattern to name primitives the same. For example a deployment and HPA can both be named `clutch`.
This change makes a composite key on `id` and the `resolver_type_url` which allows the cache to have duplicated `id` names for different resource types.
As an example we have many deployments and HPA's named the same, with this change this is how the data now looks.
```
clutch=# select id, resolver_type_url from topology_cache;
id …
```
=> topology: alter table add composite primary key

.github/workflows/scaffolding.yml, tools/scaffolding/templates/gateway/Makefile, tools/scaffolding/templates/gateway/backend/tools.go, tools/scaffolding/templates/gateway/frontend/package.json
Fixes scaffolding compatibility with go 1.16, which changed the default for `go` commands from `-mod=mod` to `-mod=readonly`.
Local, CI on main only.
=> tools: fix scaffolding compat with go 1.16

.github/workflows/docker.yml
Uses cached layers from the registry.
CI, only runs on main.
=> ci: use cache for docker build

backend/go.mod, backend/service/aws/aws.go, backend/service/aws/aws_test.go, backend/service/aws/error.go, backend/service/aws/error_test.go, backend/service/k8s/k8s.go
Extract the code and relevant message from AWS SDK errors rather than returning the stringified error with all of the information as an unknown error.
**Before:**
- **`Code 2 (UNKNOWN)`**
- `{"code": 2, "message": "operation error S3: GetObject, https response error StatusCode: 403, RequestID: DSFEFFCCWE7, HostID: O5ErieRNfwEFWEJFIWJEFIWJEFWCJJCCJCJCIWJECICJWEOCWECJW3ZHDCrc=, api error InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records."}`
**After:**
- **`Code 7 (PERMISSION_DENIED)`**
- `{"code": 7, "message":"InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records."}`
Unit and manual integration.
=> aws: error converter and interceptor

frontend/packages/core/src/landing.tsx
Fixes the welcome title on the landing page which is currently missing a space.
manual
=> frontend: fix welcome title on landing page

backend/resolver/aws/asg.go, backend/resolver/aws/aws.go, backend/resolver/aws/instances.go, backend/resolver/aws/kinesis.go, backend/service/aws/aws.go, backend/service/aws/aws_test.go, backend/service/aws/kinesis.go, backend/service/aws/kinesis_test.go, backend/service/aws/s3.go
Replace instances of  `fmt.Errorf` and `errors.New` that occur in the RPC path with `status.Error`.
Unit, audit.
=> aws: replace simple errors with grpc status

backend/resolver/k8s/k8s.go
Switch out plain errors for gRPC status in the K8s resolver. None of these should have much impact honestly.
Audit, CI.
=> k8s: improve resolver errors

backend/service/topology/cache.go
Emit a stat for the queue depth of the topology channel for each service that implements it. This will be useful to keep track of back pressure which we can alarm on.
```
counter	{"name": "clutch.gateway.start", "value": 1, "tags": {}, "type": "counter"}
gauge	{"name": "clutch.service.topology.cache.object_channel.queue_depth", "value": 0, "tags": {"service":"clutch.service.k8s"}, "type": "gauge"}
counter	{"name": "clutch.service.topology.cache.expire.success", "value": 1, "tags": {}, "type": "counter"}
gauge	{"name": "clutch.service.topology.cache.object_channel.queue_depth", "value": 1054, "tags": {"service":"clutch.service.aws"}, "type": "gauge"}
counter	{"name": "clutch.service.topology.cache.set.success", "value": 158, "tags": {}, "type": "counter"}
gauge	{"name": …
```
=> topology: emit channel queue depth

tools/scaffolding/scaffolder.go, tools/scaffolding/templates/gateway/api/echo/v1/echo.proto
Add a function to replace special characters, that are unsupported in proto3 identifiers. Use that function during scaffolding to sanitize repository owner / organization names.
Tested locally.
Fixes #289
=> tools: sanitize proto3 package names

backend/gateway/config.go, backend/gateway/config_test.go, backend/service/auditsink/slack/slack.go, backend/service/auditsink/slack/slack_test.go
PR adds logic to parse audit event metadata based on what's requested for the custom slack message. A separate PR https://github.com/lyft/clutch/pull/1089 updates the slack config to allow users to specify this custom slack message.
**Examples**:
**(1) Custom slack message for ResizeHPA wants metadata from the API request**
```
"*Min size*: [[.Request.sizing.min]]\n*Max size*: [[.Request.sizing.max]]"
```
slack message [preview](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22%60UNKNOWN%60%20performed%20%60ResizeHPA%60%20via%20%60clutch.k8s.v1.K8sAPI%60%20using%20Clutch%20on%20resource(s)%3A%5Cn-%20kind-clutch-local%2Fenvoy-staging%2Fenvoy%20(%60clutch.k8s.v1.HPA%60)%5Cn*Min%20size*%3A%201%5Cn*Max%20size*%3A%202%22%7D)
```
`UNKNOWN` performed `ResizeHPA` via …
```
=> slacksink: Add transformer to parse custom slack msg and audit event metadata

backend/service/aws/cache.go, backend/service/aws/cache_test.go, backend/service/k8s/cache.go, backend/service/k8s/meta.go, backend/service/k8s/meta_test.go, backend/service/topology/cache.go, backend/service/topology/topology.go
Performs a full re-list for all watched resources types by the Kubernetes cache. This works in tandem with the LightweightInformer to keep the cache as fresh as possible while also keeping items in cache that may not see many updates. This is similar to upstream's informer's resync while still keeping the benefit to overall memory footprint and actually pulling fresh data from the api servers.
For example some Kubernetes resources dont see frequent enough updates which in-turn does not emit an informer event. If updates to these resources are so infrequent they can be cleaned up by the topology cache which removes stale items.
In order to thread through the TopologyCache TTL to the kubernetes cache I changed the Interface for `CacheableTopology` which could be useful for other services of …
=> kubernetes: cache to re-list resources hourly

frontend/packages/core/src/Network/errors.ts, frontend/packages/core/src/Network/index.ts, frontend/packages/core/src/Network/tests/errors.test.ts
Add type guard helpers for relevant network detail types. At the moment we only care about determining Help and Clutch details.
Unit
=> frontend: add network helpers

tools/compile-protos.sh
Adds a missing argument to the call to the protoc buf linter plugin. This only affects custom gateways' linting. Without this arg the custom gateway is unable to locate the core APIs from Clutch when linting.
Manual.
=> tools: add protobuf lint missing include path

backend/internal/test/integration/helper/testserver/testserver.go
Move the call to Listen() outside of the goroutine so we know the listener is open before the function returns. This prevents a race where the caller may hit the socket before it's listening.
Unit test, ran many times.
=> backend: ensure listener is up in testserver

docs/advanced/security-auditing.md
Add `audit` middleware to example config in [Security Auditing](https://clutch.sh/docs/advanced/security-auditing/#example-config) to head off possible oversight by folks new to the project.
Validated with local markdown preview.
Fixes #
=> docs: add middleware to example config in Security Auditing

backend/service/auditsink/slack/slack.go, backend/service/auditsink/slack/slack_test.go
lyft/clutch#1089
lyft/clutch#1093
Custom slack messages can now be provided in the clutch-config and then parsed by FormatCustomText. The custom slack message will be appended to the default message for a richer slack audit. If there are any errors in parsing the custom slack message, the default message will be returned
Added unit tests
=> slacksink: enable richer slack audits

frontend/packages/core/src/stories/tabs.stories.tsx, frontend/packages/core/src/tab.tsx
Adds support for the variant prop in the Tab component. This allows for full width tabs.
stories & manual
=> frontend: support tab variants

frontend/packages/core/src/Input/form.tsx
Inherit form width from parent components to prevent resizing any of the form children.
manual
=> frontend: inherit width in form component

frontend/packages/data-layout/src/manager.tsx, frontend/packages/data-layout/src/state.tsx, frontend/packages/wizard/src/wizard.tsx
Clear data layout when restarting workflows.
manual
=> frontend: reset data layout data on restart

frontend/workflows/experimentation/src/core/page-layout.tsx, frontend/workflows/experimentation/src/list-experiments.tsx, frontend/workflows/experimentation/src/tests/__snapshots__/list-experiments.test.tsx.snap, frontend/workflows/experimentation/src/tests/__snapshots__/view-experiment-run.test.tsx.snap, frontend/workflows/experimentation/src/view-experiment-run.tsx, frontend/workflows/serverexperimentation/src/start-experiment.tsx
Modify the base experimentation components and experimentation workflows to use the new ClutchError object for richer error messages.
manual
=> experimentation: use ClutchErrors for richer error info

frontend/packages/core/src/Feedback/index.tsx, frontend/packages/core/src/Input/radio-group.tsx, frontend/packages/core/src/Input/stories/radio-group.stories.tsx, frontend/packages/core/src/index.tsx, frontend/packages/data-layout/src/index.tsx, frontend/packages/data-layout/src/manager.tsx, frontend/packages/wizard/src/index.tsx, frontend/tsconfig.json, frontend/workflows/experimentation/src/list-experiments.tsx, frontend/workflows/experimentation/src/list-view.tsx, frontend/workflows/serverexperimentation/src/form-fields.tsx, frontend/workflows/serverexperimentation/src/start-experiment.tsx, frontend/workflows/serverexperimentation/src/tests/experiment-details.test.tsx
Enforce [isolated modules](https://www.typescriptlang.org/tsconfig#isolatedModules) as this is required by both esbuild and react-scripts.
manual
=> frontend: enforce isolated modules

frontend/packages/core/src/AppProvider/workflow.tsx
Swap out custom dialog for the new Code component when rendering error details (usually the stack trace) from a workflow failing to load.
manual
=> frontend: use Code component for workflow error details

backend/module/resolver/response.go, backend/module/resolver/response_test.go, backend/resolver/aws/aws.go, backend/resolver/fanouthandler.go, backend/resolver/fanouthandler_test.go, backend/resolver/k8s/k8s.go, backend/resolver/resolver.go, backend/resolver/resolver_test.go
We need to migrate away from deprecated APIs before upgrading to the next wave of golang proto modules or we'll start failing lint for use of deprecated functions.
Unit, local.
=> resolver: remove use of deprecated proto APIs

.github/workflows/frontend.yml, tools/frontend-e2e.sh
Modify the frontend-e2e script to:
- wait until backend has successfully started
- limit both frontend and backend startup window to 30 seconds before failing
manual
=> ci: ensure backend & frontend start in e2e test

frontend/packages/core/src/Table/stories/table.stories.tsx, frontend/packages/core/src/Table/table.tsx
The children being mapped will have a null value instead of undefined. This fixes the default cell value not appearing issue.
Also added a check to make sure that we only attempt to use the default cell value if it's set since the prop is optional.
added stories
=> frontend: fix default table cell value in TableRow

docs/advanced/security-auditing.md
PR adds docs on
* general overview of slack sink and an example config
* info on how to create a custom slack message and an example config
Deploy preview link: https://deploy-preview-1168--clutch-preview.netlify.app/docs/advanced/security-auditing#sinks
=> docs: add info on slack sink and custom slack overrides

backend/mock/service/authnmock/storage.go, backend/service/authn/oidc.go, backend/service/authn/oidc_test.go
Supports token revocation by checking the token storage to see if the token is still valid.
We expect tokens to be present in the store unless they have been revoked, so
checking for existence here is sufficient for revocation purposes.
No mechanism to actually revoke the token is added, just the logic for failing verification
when the token is revoked. 
Added unit test coverage
#1116
=> oidc: check token store for token revocation

frontend/packages/core/src/stories/tab.stories.tsx, frontend/packages/core/src/tab.tsx
Add `startAdornment` prop to Tab component.
=> frontend: add startAdornment to Tab

backend/service/authn/storage.go, backend/service/authn/storage_test.go
Previously an error would occur if a credential did not have a refresh token, causing exchange or other token read/write operations to fail.
Unit
Fixes #1177
=> authn: allow empty refresh tokens in database

backend/internal/test/integration/helper/envoytest/envoy.go, backend/module/chaos/serverexperimentation/xds/xds_integration_test.go
Adds a test helper that blocks until Envoy is able to re-establish its xDS stream.
This should help de-flake individual test runs and avoid having to account for the
exponential backoff in other test assertions.
=> xds: add helper that ensures Envoy is connected to the control plane

backend/module/chaos/serverexperimentation/xds/xds_cache.go, backend/module/chaos/serverexperimentation/xds/xds_cache_test.go
Emitting stats when faults are injects and removed. This will help us set alarms when faults are on longer than expected. 
Fixes #
=> experimentation: Adding stats for active faults

frontend/packages/core/src/Feedback/error/index.tsx
…m parent
This prevents any parent from injecting padding/margin into the error component and messing up the alignment of components.
manual
=> frontend: enclose error to prevent spacing injection from parent

frontend/packages/wizard/src/step.tsx
Fill the container width with the error.
Before
After
=> wizard: error fills width

frontend/packages/core/src/Network/errors.ts
Translate the gRPC code into text for the error components status text.
manual
=> frontend: use grpc code as status text in errors

backend/service/authn/oidc.go, backend/service/authn/oidc_test.go
Adds the write part of the token revocation logic introduced in #1157
=> oidc: check token store when validating tokens

frontend/packages/wizard/src/wizard.tsx
Adds a width prop to the wizard component.
Before
After
Manual, build.
=> wizard: add width prop

frontend/packages/core/src/AppLayout/drawer.tsx
Sort workflow groups when displayed in the drawer menu.
manual
=> frontend: sort workflow groups

frontend/packages/core/src/Resolver/hydrator.tsx
Add sorting functionality back to resolver advanced selects originally introduced in #1240.
manual
=> Hydrator advanced option sort

backend/middleware/authn/authn.go, backend/middleware/authz/authz.go, backend/middleware/authz/authz_test.go, backend/service/authn/authn.go
Be explicit about the authn methods that are always open and move the list to a common palce.
CI
=> authnz: explicitly list allowed authn methods

frontend/packages/core/src/AppLayout/drawer.tsx
Use new popper component in app layout drawer. This is a net zero change since the behavior remains the same.
manual
=> frontend: use popper component in drawer

backend/gateway/mux/mux.go, backend/gateway/mux/mux_test.go
Background:
By default, http request headers are passed to gRPC context via the [DefaultHeaderMatcher](https://github.com/grpc-ecosystem/grpc-gateway/blob/519e7f45f48e3e378e3341d076579f3ce52aa717/runtime/mux.go#L63-L74) rule. If the request headers don't meet certain preconditions, they are dropped.
Solution:
PR adds a custom header rule so that `X-` request headers are forwarded (and prefixed with `grpcgateway`). All other headers will be checked by the DefaultHeaderMatcher rule.
Use case for this change: 
For the slackbot work, we need to [verify](https://api.slack.com/authentication/verifying-requests-from-slack#verifying-requests-from-slack-using-signing-secrets__a-recipe-for-security__step-by-step-walk-through-for-validating-a-request) a request came from Slack by certain `X-` …
=> mux: forward X- headers

backend/service/topology/cache.go, backend/service/topology/cache_test.go
It was possible to batch insert multiple entries of the same item which is not possible with postgres and results in the error below. With this PR I changed the `batchInserts` to a map which removes the possibility for duplicates while also updating the cache with the latest entry assuming that items coming over the channel are received in chronological order which I think its safe to assume for a single resource.
> {"level":"error","ts":1617985716.6457253,"caller":"topology/cache.go:135","msg":"Error setting cache","serviceName":"clutch.service.topology","error":"pq: ON CONFLICT DO UPDATE command cannot affect row a second time","stacktrace":"github.com/lyft/clutch/backend/service/topology.(*client).processTopologyObjectChannel\n\t/code/clutch-private/clutch/backend/service/topology/cache …
=> topology cache: deduplicate batch inserts

frontend/packages/core/src/AppProvider/workflow.tsx
Fixes the format of the default error message for workflows
manual
=> frontend: fix spacing in workflow default error message

backend/service/k8s/cache.go
Previously I was closing `s.topologyObjectChan` for every cluster that I was watching which resulted in the error below. Moved the channel close up so its not invoked more than once.
```
panic: close of closed channel
goroutine 221 [running]:
github.com/lyft/clutch/backend/service/k8s.(*svc).startInformers(0xc000070440, 0x46e0ff8, 0xc000070bc0, 0xc00131d1f0, 0x8, 0x4712d48, 0xc001715170, 0x68c61714000)
/code/clutch-private/clutch/backend/service/k8s/cache.go:94 +0x868
created by github.com/lyft/clutch/backend/service/k8s.(*svc).StartTopologyCaching
/code/clutch-private/clutch/backend/service/k8s/cache.go:45 +0x1af
```
Locally.
```
INFO	topology/topology.go:107	Caught shutdown signal, shutting down topology caching and releasing advisory lock	{"serviceName": "clutch.service.topology"}
INFO …
```
=> k8s cache: fix cache panic on shutdown

frontend/workflows/ec2/src/resize-asg.tsx
Fix validation of desired size field within resize ASG workflow to set a max less than or equal to the max size field.
manual
=> frontend: limit resize asg desired size to max

frontend/packages/wizard/src/wizard.tsx
If there was an optional step e.g.
```jsx
{fooStepEnabled && <FooStep />}
<BarStep />
```
one of the children would be null.
Calling toArray removes null children per https://github.com/facebook/react/issues/4867#issuecomment-413975155
Demo: https://codesandbox.io/s/nice-northcutt-mu0kk?file=/src/App.js
Manual, CI.
=> wizard: call toArray on steps to filter nulls

backend/mock/service/authnmock/oidcprovider.go, backend/module/authn/authn.go, backend/service/authn/authn.go, backend/service/authn/oidc.go, backend/service/authn/oidc_test.go, backend/service/authn/storage.go
Third-party token reads can now take place through the provider so they can be refreshed if needed.
TODO
=> authn: read tokens through the provider for refresh

backend/service/chaos/experimentation/terminator/terminator.go
`terminator` is a service, not a module.
unit
=> experimentation: rename module to service

tools/scaffolding/templates/frontend/package.json
Update the frontend workflow scaffolding to use esbuild and enforce a min node version of 14
manual
=> tools: update workflow frontend scaffolding

frontend/package.json, frontend/packages/core/package.json, frontend/packages/core/src/AppLayout/feedback.tsx, frontend/packages/core/src/AppProvider/themes.tsx, frontend/packages/core/src/Feedback/hint.tsx, frontend/packages/core/src/Feedback/warning.tsx, frontend/packages/core/src/Input/radio-group.tsx, frontend/packages/core/src/not-found.tsx, frontend/packages/core/src/panel.tsx, frontend/packages/core/src/tests/__snapshots__/not-found.test.tsx.snap, frontend/packages/tools/package.json, frontend/yarn.lock, tools/frontend-gateway-linker.sh
Remove styled-components dependency now that we are fully using emotion.
CI
=> frontend: remove styled components

tools/frontend-gateway-linker.sh
Add esbuild to LINKED_PACKAGES under frontend-gateway-linker.sh to fix a build issue I was having
manual
=> tools: add esbuild to gateway fe linker

frontend/packages/core/src/Network/index.ts, frontend/packages/core/src/Network/tests/index.test.ts
Adds tests for the success interceptor on the network client.
Also removes the code and message set on the response data in the auth case as they won't be propagated due to the throw logic.
included
=> frontend: add network tests for success interceptor

frontend/packages/wizard/src/state.tsx
If a workflow attempts to use `onBack` on the first step we should not update the index.
manul
=> frontend: prevent wizard regressing past the first step

frontend/packages/core/src/Resolver/index.tsx, frontend/packages/core/src/Resolver/input.tsx
It would be convenient to have the ability to turn off autocomplete at the workflow rather than just the schema level.
Once this PR is in then we can pass a prop via the config file to the ResolverChild to turn off autocomplete for a given workflow.
Fixes #
=> frontend: resolver - add prop to override / disable autocomplete at the workflow level

Makefile, backend/internal/test/integration/xds/.gitignore, backend/internal/test/integration/xds/do_integration_test.sh, backend/internal/test/integration/xds/docker-compose.yaml, backend/internal/test/integration/xds/envoy.Dockerfile, backend/internal/test/integration/xds/testrunner.Dockerfile
Cuts down the time to run integration tests in several ways:
1) build the Go binaries on the host system, allowing for reuse of cached artifacts (build, go mod, etc.)
2) use smaller Docker containers. We go from needing to pull golang and envoyproxy/envoy to pulling alpine and envoyproxy/envoy-alpine, which results in substantially shorter download times
3) set the grace period of the envoy container to 0, this issues a KILL immediately instead of waiting for up to 10s for envoy to handle a TERM
=> experimentation: speed up integration testing

frontend/packages/data-layout/src/state.tsx, frontend/packages/data-layout/src/tests/state.test.tsx
In case of a conflict at the time of wizard state merge, make new data override the old data.
Manual testing (went through some wizard flows and verified that they work)
=> datalayout: make new data take precedence over old data

frontend/workflows/serverexperimentation/src/index.tsx
To be more explicit and avoid any confusion with the name Experimentation, this PR adds Chaos before Experimentation in Server experiments.
Fixes #
=> experimentation: Adding `Chaos` in server experimentation UI

backend/mock/service/k8smock/k8smock.go
Add some more test values to the k8s mock for listing config maps.  Note this will break clutch-private tests temporarily when it is merged. 
tests still pass since this doesn't affect anything.
Fixes #
=> k8s: add values to ListConfigMaps mock

backend/service/chaos/experimentation/experimentstore/experiment_run.go, backend/service/chaos/experimentation/experimentstore/experiment_run_test.go, backend/service/chaos/experimentation/experimentstore/experiment_test.go
1. Display `termination reason` when an experiment is `canceled` or `completed`. Previously we were displaying the termination reason only for `canceled` experiment but this did not cover the case when an experiment was started without a specified end date and terminated by automated experiment termination later on (in this case, the final status of terminated experiment was `completed`.
2. Fix experiment status computation for corner case when current time equal to start time. Previously experiments like that returned `completed` status, after the changes they return `running` status.
Unit tests and manual testing.
=> experimentation: display termination reason

backend/gateway/meta/meta.go, backend/gateway/meta/meta_test.go
PR adds a helper for converting a custom type to a Value type. This is useful as [structpb.NewValue](https://pkg.go.dev/google.golang.org/protobuf/types/known/structpb#NewValue) supports a limited set of types. More details here: https://github.com/golang/protobuf/issues/1302#issuecomment-805453221
unit test
=> meta: add helper to convert custom types to a Value type

frontend/packages/data-layout/src/layout.tsx
It is useful to be able to not hydrate by default when calling useDataLayout(k).  
Tested for my use case and it works.  This is important if we have tables where we want to switch views on data and don't want to call hydrate everytime we switch tabs.
Fixes #
=> data-layout: add flag to enable or disable hydration on useDataLayout()

.github/CODEOWNERS
New rule should ensure that Resilience is the owner of `redisexperimentation` frontend module/package that's being added to Clutch here https://github.com/lyft/clutch/pull/1427.
N/A
=> ci: make resilience owners of redisexperimentation

frontend/packages/core/src/AppLayout/drawer.tsx, frontend/packages/core/src/popper.tsx
Move hard-coded ID out of popper and allow it to be passed in as a prop
manual
=> frontend: allow for configurable popper id

backend/resolver/core/core.go
Adding `Project` to the core resolver, currently this enables autocomplete for this resource.
Locally.
```
curl --location --request POST 'http://localhost:8080/v1/resolver/autocomplete' \
--header 'Content-Type: application/json' \
--data-raw '{
"want": "type.googleapis.com/clutch.core.project.v1.Project",
"search": "clutch"
}'
{"results":[{"id":"clutch","label":""}]}
```
=> resolver: add project to core resolver

frontend/package.json, frontend/packages/app/src/clutch.config.js, frontend/workflows/k8s/package.json, frontend/workflows/k8s/src/index.tsx, frontend/workflows/k8s/src/k8s-dash-header.tsx, frontend/workflows/k8s/src/k8s-dash-search.tsx, frontend/workflows/k8s/src/k8s-dashboard.tsx, frontend/workflows/k8s/src/pods-table.tsx, frontend/yarn.lock
This PR adds a new workflow for the Kubernetes Dashboard which serves as an overview of all the Kubernetes resources running in the cluster. This PR adds a Pods list table which displays pods in a given namespace in a clientset and allows the user to perform a delete operation on a pod from the dashboard
Local 
- Add more resource tables to this dashboard. Tables for Deployments, CronJobs, StatefulSets and Jobs coming soon!
=> k8s: add Kubernetes Dashboard workflow

.vscode/settings.json, api/.vscode/settings.json, tools/compile-protos.sh
This allows proto paths to resolve correctly when opening code from the root directory or via workspaces
Note these paths must be at the root of the project for those who open vscode at the root and within the workspace for those who use vscode workspaces.
manual
=> tools: add vscode settings for proto paths

frontend/workflows/k8s/src/deployments-table.tsx, frontend/workflows/k8s/src/k8s-dashboard.tsx
This PR adds a new Deployments table to the Kubernetes Dashboard which displays a list of deployments and its meta data. The data displayed per deployment maps to the output of `kubectl get deployment`
local
- Add ability to delete deployments in deployment table
- Add age field to the deployment table
=> k8s: add deployments table to Kubernetes dashboard

backend/service/chaos/experimentation/experimentstore/storer.go, backend/service/chaos/experimentation/experimentstore/storer_test.go
`==` is not a valid comparison operator. Use `=` instead.
Manual
=> experimentation: use correct = operator

frontend/workflows/k8s/src/deployments-table.tsx, frontend/workflows/k8s/src/pods-table.tsx
This PR adds an AGE column to the deployments table which displays the amount of time that the application has been running.
local:
=> frontend: add age column to deployments table

frontend/workflows/k8s/src/crons-table.tsx, frontend/workflows/k8s/src/k8s-dashboard.tsx
This PR adds a cronjob overview table to the kubernetes dashboard where users can view a list of cronjobs running per namespace along with some metadata.
Local:
=> frontend: add cronjob table to kubernetes dashboard

frontend/workflows/k8s/src/k8s-dashboard.tsx, frontend/workflows/k8s/src/stateful-sets-table.tsx
This PR adds a stateful sets table to the Kubernetes dashboard which lists the stateful sets in a given namespace
local
- Add current replicas, desired replicas, age, etc as columns in this table
=> frontend: add stateful set table to kubernetes dashboard

frontend/packages/data-layout/.eslintrc.js, frontend/packages/data-layout/package.json, frontend/packages/data-layout/src/manager.tsx, frontend/packages/data-layout/src/tests/manager.test.tsx, frontend/yarn.lock
Changes the initial state dict to come from a function so each key's initial state cannot end up sharing the same reference to another key's initial state.
Manual & unit test.
=> datalayout: avoid shared ref to data object in initial state

frontend/packages/core/src/Input/select.tsx, frontend/packages/core/src/Input/tests/select.test.tsx
Add a lower bound on default option index.
manual and unit
=> frontend: set lower bound on select default index

frontend/workflows/k8s/src/stateful-sets-table.tsx
This PR adds the desired replicas, available replicas & updated replicas to the stateful sets table
local
=> frontend: add more fields to stateful table

backend/service/audit/setup.go
Unlocking the events lock before the sink(s) occur as this could take sometime, this is because at this point the audit table has already been updated other works are now safe to pick up items from the audit table.
Also increase the deadline to 30 seconds to give more time for the sink write.
> {"level":"error","ts":1623447335.3891637,"caller":"sql/sql.go:202","msg":"Unable to perform an advisory unlock","serviceName":"clutch.service.audit","error":"context deadline exceeded","stacktrace":"github.com/lyft/clutch/backend/service/audit/storage/sql.(*client).ReleaseLock\n\t/code/clutch-private/clutch/backend/service/audit/storage/sql/sql.go:202\ngithub.com/lyft/clutch/backend/service/audit.(*client).poll\n\t/code/clutch-private/clutch/backend/service/audit/setup.go:183"}
=> audit: tune deadline and unlock before sink occurs

frontend/workflows/projectSelector/src/hello-world.tsx
Previously, for each new custom project added to the list, an API call is made to retrieve that project even if the project already exists in the list. 
PR checks if the project has already been added in the state to avoid making an unnecessary API call.
before
after
=> project selector: don't add project that already exists

frontend/workflows/projectSelector/src/hello-world.tsx
Display the total number of checked projects per group.
Manual
=> project selector: display total checked per group

frontend/workflows/projectSelector/src/hello-world.tsx
PR adds initial styling to the project selector sidebar. Left some TODOs to address later.
before
after
=> project selector: sidebar styling

frontend/workflows/projectSelector/.eslintrc.js, frontend/workflows/projectSelector/src/hello-world.tsx, frontend/workflows/projectSelector/src/project-group.tsx, frontend/workflows/projectSelector/src/selector-reducer.tsx
PR moves the selectorReducer and ProjectGroup component into their own file.
We could do more organization later (like create a types file for the various state/action types & create a helpers files for shared functions across the components).
manual
=> project selector: reorganize file

frontend/packages/app/src/clutch.config.js, frontend/workflows/k8s/src/describe-pod.tsx, frontend/workflows/k8s/src/index.tsx, frontend/workflows/k8s/src/pods-table.tsx
This PR adds a new K8s workflow: Describe Pod, which provides pod details like containers in the pod, state, node IP, events etc
This PR also adds a `Details` link the K8s dashboard that routes users to the Describe Pod workflow automatically.
Local:
- Possibly make the pod name in the K8s dashboard clickable so it links to the Describe Pod workflow directly
=> frontend: add describe pod workflow to k8s dashboard

frontend/packages/tools/workflow-registrar.js
This will allow users to override the expected config file name when utilizing the workflow registrar script.
manual
=> frontend: allow config file override for workflow registrar script

docs/blog/2021-06-16-tailor-your-slack-audit-sink-messages.md
Adds new blog post on the richer slack audit feature.
locally & deploy preview: https://deploy-preview-1515--clutch-preview.netlify.app/blog/2021/06/16/tailor-your-slack-audit-sink-messages
=> docs: richer slack audit blog post

backend/module/featureflag/featureflag.go, backend/module/featureflag/featureflag_test.go
Handle use case where feature flags are enabled in the clutch config with no flags.
manual
=> backend: fix feature flags empty config handling

docs/_website/src/theme/BlogPostItem/index.tsx
Only show share button on full blog pages. At the moment truncated blogs will show a share button for each blog on the root blog page which uses the windows current URL. This change removes the share and fixes that bug.
manual
=> docs: only show share button on individual blog pages

docs/_website/src/components/Share/index.tsx, docs/blog/2020-07-22-announcing-clutch.md, docs/blog/2021-02-01-frontend-asset-passthrough.md, docs/blog/2021-04-05-great-design-is-transparent.md, docs/blog/2021-06-16-tailor-your-slack-audit-sink-messages.md
Add support for twitter handle attribution when sharing blog posts via twitter
manual
=> docs: add support for blog authors twitter handles

tools/frontend-e2e.sh
Will hopefully fix the timeout for server start on main. Guessing it's resource contention.
CI.
=> ci: start e2e backend separate from frontend

frontend/packages/core/src/Contexts/wizard-context.tsx, frontend/packages/wizard/src/wizard.tsx, frontend/workflows/ec2/src/reboot-instance.tsx, frontend/workflows/ec2/src/resize-asg.tsx, frontend/workflows/ec2/src/terminate-instance.tsx, frontend/workflows/k8s/src/delete-pod.tsx, frontend/workflows/k8s/src/resize-hpa.tsx, frontend/workflows/kinesis/src/update-shard-count.tsx
Add ability to navigate back to origin of workflows when one is set. This is useful for workflows that depend on other workflows (e.g. k8s dashboard -> delete pod) when either navigating backward or restarting the workflow users should be directed back to the place they started.
manual
=> frontend: support origin navigation in workflows

.github/workflows/frontend.yml
I think this should help e2e tests pass more consistently. The build currently flakes because the mock server build takes longer than 30s sometimes. By using a newer and consistent version of go and referencing the mock build's cache first, it should speed things up.
CI.
=> ci: fix e2e test flakiness

frontend/workflows/projectSelector/src/selector-reducer.tsx
Same as https://github.com/lyft/clutch/pull/1571 but closed b/c commit history issues after I merged the feature branch into main
Background
The flow only makes an API call if we don't have data on a project & on each API request we store data on the project and its upstreams/downstreams. So previously, if you added an upstream/downstream as a custom project, we weren't updating the state with its own upstreams/downstreams.
Solution
PR updates the `add_project` state to check if we have project data on a project and if so, we update the state with its upstreams/downstreams.
Locally with real API data
=> project selector: update "add_project" state to check project data cache

docs/about/roadmap.md
Edited docs by removing advanced fault injection from the roadmap section since its now available
=> docs: Removing Fault Injection from the roadmap

frontend/packages/core/src/AppLayout/search.tsx, frontend/packages/core/src/Resolver/index.tsx, frontend/packages/core/src/Resolver/input.tsx, frontend/packages/core/src/index.tsx, frontend/packages/core/src/landing.tsx, frontend/packages/core/src/navigation.tsx, frontend/packages/core/src/tests/navigation.test.tsx, frontend/packages/wizard/package.json, frontend/packages/wizard/src/wizard.tsx, frontend/workflows/experimentation/package.json, frontend/workflows/experimentation/src/list-experiments.tsx, frontend/workflows/experimentation/src/tests/list-experiments.test.tsx, frontend/workflows/experimentation/src/tests/view-experiment-run.test.tsx, frontend/workflows/experimentation/src/view-experiment-run.tsx, frontend/workflows/k8s/package.json, frontend/workflows/k8s/src/pods-table.tsx, frontend/workflows/redisexperimentation/package.json, frontend/workflows/redisexperimentation/src/start-experiment.tsx, frontend/workflows/redisexperimentation/src/tests/experiment-details.test.tsx, frontend/workflows/redisexperimentation/src/tests/start-experiment.test.tsx, frontend/workflows/serverexperimentation/package.json, frontend/workflows/serverexperimentation/src/start-experiment.tsx, frontend/workflows/serverexperimentation/src/tests/experiment-details.test.tsx, frontend/workflows/serverexperimentation/src/tests/start-experiment.test.tsx, frontend/yarn.lock, tools/scaffolding/templates/gateway/frontend/package.json
Add custom react-router hooks to:
-  preserve utm search params
- provide an easier interface to track origins when routing between pages
- provide an easier interface to specify search params (see [this](https://github.com/ReactTraining/react-router/issues/7743) for context)
manual and unit
=> frontend: add custom react-router hooks

frontend/workflows/projectSelector/src/helpers.tsx, frontend/workflows/projectSelector/src/project-group.tsx, frontend/workflows/projectSelector/src/project-selector.tsx, frontend/workflows/projectSelector/src/selector-reducer.tsx
PR adds
* helpers to collect the exclusive upstreams/downstreams of a project in the "remove_projects" state
* removes the exclusive upstreams/downstreams of the removed project(s)
Tested locally with real API data
=> project selector: remove exclusive upstreams/downstreams

frontend/packages/core/src/Input/text-field.tsx
Fix issue where autocomplete would clear input text if it didn't match an available option.
manual
=> frontend: fix autocomplete when chosen value isn't an option

frontend/workflows/projectSelector/src/index.tsx, frontend/workflows/projectSelector/src/project-selector.tsx, frontend/workflows/projectSelector/tsconfig.json
This adds support for the project selector to share its state with cards.
manual
=> frontend: add support for propagating service state to project selector

frontend/packages/core/src/card.tsx, frontend/packages/core/src/index.tsx, frontend/packages/core/src/stories/typography.stories.tsx, frontend/packages/core/src/typography.tsx
Add `CardHeader` component and use Typography component throughout card
manual
=> frontend: use typography in cards and add card header

frontend/workflows/projectSelector/src/dash-hooks.tsx, frontend/workflows/projectSelector/src/dash.tsx, frontend/workflows/projectSelector/src/index.tsx, frontend/workflows/projectSelector/src/project-selector.tsx, frontend/workflows/projectSelector/src/types.tsx
Instead of directly exposing the selector's context and all of its internal implementation details, we add a new dash context that will be used to track the selected projects and eventually events for the timeline view.
Integration with private card.
=> dash: use a dash context updated by selector

tools/frontend-e2e.sh
See if it fixes flakiness on main. Hypothesis is that cache is separate on main and PRs which could cause main to run over a little bit.
CI
=> e2e test: add 15s to startup wait

backend/service/github/github.go, backend/service/github/github_test.go
Add additional information to `GetCommit` response object for author and commit message.
unit
=> backend: add additional information to github commit response

frontend/workflows/projectSelector/src/helpers.tsx, frontend/workflows/projectSelector/src/project-group.tsx, frontend/workflows/projectSelector/src/project-selector.tsx, frontend/workflows/projectSelector/src/selector-reducer.tsx
PR adds support for hiding exclusive upstreams/downstreams of a user-owned/custom project when the latter are unchecked.
PR flow derives the hidden status based on the checked value (ie `true`/`false`) of the user-owned/custom project. In this way, we don't need to handle the flow in the `actions` as a the hidden status of an upstream/downstream is influenced by various user actions (the toggle, the only button, the checkbox, if a new project is added, etc).
locally with real API data
~1. how do we want to handle the switch status b/c we preserve the checked status of hidden projects. we can simply filter by "if checked but not hidden". the `deriveSwitchStatus` helper is used in other parts tho so we'll need to create a helper for the non-switch status use cases.~ **in latest commit, we …
=> project-selector: hide exclusive upstreams/downstreams

backend/service/github/github.go, backend/service/github/github_test.go
It is useful to have some of the other fields that are returned by the go githubv3 API such as avatarURL and ID
Fixes #
=> backend: github service: add User object to response

frontend/workflows/projectSelector/src/selector-reducer.tsx
https://github.com/lyft/clutch/pull/1588 introduced a state toggle bug. In that PR, we made a change to pass filtered state data to components & updated the `toggle_entire_group` action to only update the checked status of rendered projects. However, the `deriveSwitchStatus` func received the original state data, and so it was checking the checked status of the all the projects instead of the the projects that were rendered. And as such, after users use the toggle for the first time, the toggle state gets stuck.
This PR updates the `toggle_entire_group` action to pass the filtered state data to the `deriveSwitchStatus` func
locally with real api data
=> project-selector: fix toggle state bug

.github/workflows/stale.yaml
Looks like the bump from v3 -> v4 had some changes that weren't accounted for in the changelog. I'm adding this additional config option to prevent stalebot from doing anything with issues like we had it before.
=> ci: update stale action config to stop issue handling

frontend/workflows/projectSelector/src/dash-hooks.tsx
Was missing return type resulting in `any` for consumers of hook.
=> dash: add return type to useDashState hook

tools/scaffolding/templates/gateway/Makefile
Run `backend-tidy` before other frontend make steps as we rely on the clutch go module being present to access our tooling scripts. For example `install-yarn.sh.
Manual
=> scaffolding: fix ordering for make all target

tools/scaffolding/templates/frontend/package.json
Enforce workflows are generated with a proper yarn version. This is a short term fix as we should ideally use the existing yarn binary within Clutch.
manual
=> tools: enforce a global yarn version when generating workflow

tools/scaffolding/scaffolder.go
Scaffolding `os.Rename` would fail when it contained a leading `~` for the users home directory.
e.g. `2021/07/23 16:32:09 rename /tmp/clutch-scaffolding-474555198 ~/go/src/github.com/dhochman/clutch-custom-gateway/frontend/workflows/amiibo: invalid argument`
=> scaffolding: fix copy when ~ is in path

backend/mock/service/githubmock/githubmock.go, backend/service/github/github.go, backend/service/github/github_test.go
We need to get a list of commits via the comparison API.
unit
Fixes #
=> backend: github service: add commitRange() from comparison API

frontend/workflows/projectSelector/src/dash.tsx
Removes duplicate state updates for dash cards that rely on the selected hook.
Currently, the [`updateSelected`](https://github.com/lyft/clutch/blob/main/frontend/workflows/projectSelector/src/project-selector.tsx#L153) is called anytime there is a state change which currently happens on load, on hydrate start, and on hydrate end.
manual
=> frontend: only update selected projects in dash hook if changes

frontend/workflows/projectSelector/src/card.tsx, frontend/workflows/projectSelector/src/dash.tsx
Fixes width of Dash content layout. Previously it would overflow given the 100% width.
manual
=> frontend: fix width layout of dash content

frontend/packages/core/src/Feedback/index.tsx, frontend/packages/core/src/Feedback/stories/tooltip.stories.tsx, frontend/packages/core/src/Feedback/tooltip.tsx, frontend/packages/core/src/index.tsx, frontend/packages/core/src/typography.tsx, frontend/workflows/projectSelector/src/project-selector.tsx
PR
* adds tooltip to core design system
* adds tooltip stories
* adds tooltip to project selector component 
* makes small change to typography component to accept a color prop
locally and storybook
=> frontend: add tooltip to core design & project selector

frontend/workflows/projectSelector/src/dash-hooks.tsx, frontend/workflows/projectSelector/src/helpers.tsx, frontend/workflows/projectSelector/src/project-group.tsx, frontend/workflows/projectSelector/src/project-selector.tsx, frontend/workflows/projectSelector/src/selector-reducer.tsx, frontend/workflows/projectSelector/tsconfig.json
Enable strict typescript rules for project selector and make appropriate fixes.
manual
=> frontend: move project selector to strict typescript

frontend/packages/core/src/link.tsx
When Links overflow they should be hidden.
manual
=> frontend: hide overflow of Links

frontend/workflows/projectSelector/src/card.tsx
Card implementations will be using the [data-layout](https://clutch.sh/docs/about/architecture/#data-layout), which contains the loading state of an API call, so this PR adds an `isLoading` prop and loading component.
=> dash card: add loading prop

frontend/workflows/projectSelector/src/dash-hooks.tsx
Throw an error if the value is not valid for the given context. 
This will eliminate the need for the caller to continually check for and handle a null context value every time they access the context, which is a wholly invalid state anyways and can't be rectified.
=> dash: throw error from useDashState if context invalid

frontend/packages/core/src/Table/table.tsx
Fix `The pseudo class ":nth-child" is potentially unsafe when doing server-side rendering. Try changing it to ":nth-of-type". ` warning.
manual
=> frontend: remove warning in table css

frontend/packages/core/src/button.tsx
Add `onClick` prop to icon button
manual
=> frontend: add onClick prop to icon button

frontend/packages/core/src/button.tsx, frontend/packages/core/src/tests/__snapshots__/button.test.tsx.snap
Add support for button variants in icon button.
manual
=> frontend: support icon button variants

frontend/packages/core/src/card.tsx, frontend/workflows/projectSelector/src/card.tsx
Previously, the loading component was conditionally rendered in between the card header & children and so it pushed down the child component every time there was loading state.
Before:
PR moves the loading component to the card header so that it doesn't push down the child component
After:
locally with internal cards
=> dash: move loading prop to card header

frontend/packages/core/src/Table/table.tsx
Noticed that the table row gray color is different between the 2 internal cards. The difference between the 2 cards is that one uses the `responsive` prop.
This can also be reproduced locally in storybook by adding the `responsive` prop here https://github.com/lyft/clutch/blob/main/frontend/packages/core/src/Table/stories/table.stories.tsx#L22.
In reviewing the styling for the TableRow, the background should be same regardless of whether the responsive prop is used https://github.com/lyft/clutch/blob/main/frontend/packages/core/src/Table/table.tsx#L51-L64. However, in locally setting the `nth` row to different colors, it seems that using an rgb value with opacity is causing this color difference b/w prop usage and changing it to HEX fixes the color difference issue (got the HEX value from …
=> core table row: use hex instead of rgb

frontend/packages/core/src/Network/tests/index.test.ts
Fixes uncaught exception warning in network unit test as well as window setup and teardown between describe blocks.
CI
=> frontend: fix uncaught exception warning in network test

frontend/packages/core/package.json, frontend/packages/core/src/card.tsx, frontend/workflows/projectSelector/src/card.tsx
PR also makes the CardContent padding configurable via the Material UI spacing system https://material-ui.com/system/spacing/#api
PR also wraps the Dash card children in the CardContent component to fix issues where the card children have their own border styling. Example below: the Table component's [Paper ](https://github.com/lyft/clutch/blob/d3632a1426c51211f66b690e871a485e09a6f0c0/frontend/packages/core/src/Table/table.tsx#L21)has border styling and so it looks like the card children area isn't aligned with the card header. (Also, the CardContent component will be useful if we want to add card actions to it, ie "expand to see more").
locally
0px padding on the CardContent
32px padding (the value we currently use) on the Landing cards which use the CardContent as well
=> core: add configurable padding to CardContent

frontend/workflows/dynamodb/src/update-capacity.tsx
This PR fixes a bug when modifying tables with no global secondary indexes. Previously, it was trying to perform mapping on non-existent lists and throwing errors as a result.
This PR also adds a header to the workflow.
Manual local changes
=> dynamodb: fix empty list mapping

frontend/packages/core/src/Table/table.tsx, frontend/workflows/projectSelector/src/card.tsx, frontend/workflows/projectSelector/src/dash.tsx
Currently, the cards remain side by side until the screen size reaches the `xs` breakpoint. Since card info can be dense (i.e. many columns) we want the cards to take the screen's full width at an earlier breakpoint.
* PR updates the small breakpoint value and adds the medium and large breakpoint so that the cards remain side by side until the screen size becomes less than 1280px. https://material-ui.com/customization/breakpoints/
* Tables are used in the internal cards and realized that it has a default breakpoint at which to compress the table rows. Since cards take up full width now, PR changes the default to `small` so that the table rows take up the full space available and also adds a `compressBreakpoint` prop so that user can change the default value.
locally
=> dash cards: update/add breakpoints

backend/service/aws/dynamodb.go, backend/service/aws/dynamodb_test.go
This PR revises how the BillingMode field for tables is marshaled into proto format. 
Manual testing locally + unit tests
=> dynamodb: fix BillingMode to proto method

frontend/workflows/ec2/src/resize-asg.tsx, frontend/workflows/k8s/src/resize-hpa.tsx
If the min asg/hpa size is already zero we should continue to allow it
manual
=> frontend: remove zero restriction for resize workflows

frontend/workflows/ec2/src/resize-asg.tsx, frontend/workflows/k8s/src/resize-hpa.tsx
Building off https://github.com/lyft/clutch/pull/1754 - now that we allow 0 as a min size for asg/hpa we still want to prevent users from scaling down to 0 completely
manual
=> frontend: fix max size validation in resize workflows

frontend/packages/core/src/Table/metadata-table.tsx
If a metadata table row has validation errors it should not update the source field.
manual
=> frontend: metadata table should not update values if errors are present

.gitignore, backend/.air.toml, backend/gateway/config.go, backend/gateway/gateway.go, backend/gateway/gateway_test.go, backend/go.mod, backend/go.sum, tools/scaffolding/templates/gateway/.gitignore, tools/scaffolding/templates/gateway/backend/.air.toml
Add support for dotenv files to the backend. This will always allow local env variable to take precedence (either through the command line or `.env.local`). In development, `.env.development` will be loaded, if present.
manual
=> backend: add support for dotenv

.github/workflows/docker-dev.yml, .github/workflows/docker.yml, Dockerfile, tools/preflight-checks.sh
https://github.com/lyft/clutch/pull/1764 introduced a preflight check script, and the `dockerfile` was not tested to include this.
Docker was failing to build previously as the yarn version in the node image is only `1.22.5`
> yarn version must be >= 1.22.11, current version 1.22.5
* bump dockerfile images to the latest patch
* fix CI so it builds dockerfile if its modified in a PR
* have the `preflight-checks.sh` script only enforce major and minor versions of a dep I dont think we need to require that a dep be up to a specific patch at the moment. Unless there is some important fix that im not aware of.
ci
=> ci: fix dockerbuild

docs/blog/2021-02-01-frontend-asset-passthrough.md, docs/blog/2021-04-05-great-design-is-transparent.md, docs/blog/2021-05-18-chaos-experimentation.md
Minor cleanup of blogs.
* Removes unused imports
* Uses `Image` over `img`
manual
=> docs: cleanup blog docs

frontend/workflows/projectSelector/src/dash-hooks.tsx, frontend/workflows/projectSelector/src/dash.tsx, frontend/workflows/projectSelector/src/index.tsx, frontend/workflows/projectSelector/src/types.tsx
I have attempted to implement functionality for a timeline state.
2 hooks are added: 
`useTimelineState` for reading the timeline data
`useTimelineUpdater` for writing to the timeline data
PLT-1011
Fixes #
=> frontend: projectSelector/Dash: custom hooks for reading and writing to timeline

frontend/packages/core/src/popper.tsx
This is useful to be more like the material-ui popper
Fixes #
=> add null type to PopperProps

frontend/packages/core/src/popper.tsx
My previous PR https://github.com/lyft/clutch/pull/1839/files added just the null type, but didn't add the case of where null can be passed into `MutableRefObject` . So this one fixes that.
Fixes #
=> add MutableRefObject<null> type to Popper prop anchorRef

frontend/packages/tools/package.json, frontend/yarn.lock
This reverts commit bf808e1cc206bb5cc4c33146c467fe5762d750bd.
esbuild is causing breaking changes in the builds, reverting for now
Manually rolled back and the builds are succeeding.
=> Revert "housekeeping: Update dependency esbuild to ^0.13.0 (#1809)"

frontend/packages/tools/package.json, frontend/yarn.lock
Some variability is happening with esbuild, locking to 0.12.16 for now as 0.12.17 introduces the breaking change.
=> frontend: Locking esbuild to 0.12.16

frontend/packages/core/src/Input/text-field.tsx
There are times where I felt auto complete was not firing fast enough to provide a good user experience. Reducing this value by half seems like a good place to start.
n/a
=> frontend: reduce autocomplete debouce to 250ms

frontend/packages/core/src/chip.tsx
Add support to fill chips.
manual
=> frontend: add fill support to chips

frontend/packages/core/src/button.tsx, frontend/packages/core/src/stories/button.stories.tsx
PR adds the new color palette `tertiary` that Design added to the core design system (will also be used in the Wizard feedback component). Figma link in slack thread.
Storybook
=> core: add new color palette to button

backend/mock/service/k8smock/k8smock.go, backend/module/k8s/node.go, backend/service/k8s/k8s.go, backend/service/k8s/node.go, backend/service/k8s/node_test.go
Follow up to https://github.com/lyft/clutch/pull/1906
Implement api's for DescribeNode & UpdateNode. Currently supports updating NodeSpec.Unschedulable field only (cordon node).
Updating schedulablity on a node that is already in the desired schedulabiltiy state (i.e. cordoning a node that is already cordoned) should succeed as this is the desired result for the end user.
Tested via curl against a remote kube cluster:
DescribeNode:
```
$ curl --location --request POST 'http://localhost:8080/v1/k8s/describeNode' \
--header 'Content-Type: application/json' \
--data-raw '{
"clientset": "testcontext",
"cluster": "test",
"name": "test-node-name"
}'
{"node":{"name":"test-node-name","cluster":"test","unschedulable":false}}%
```
UpdateNode:
```
$ curl --location --request POST …
```
=> k8s: implement backend api's for node

frontend/packages/core/src/landing.tsx
SVG for welcome monster wasn't aligned with the text, so this adjusts that.
Manual
=> frontend: Adjust spacing for welcome image

frontend/packages/core/src/Input/index.tsx, frontend/packages/core/src/Input/select.tsx, frontend/packages/core/src/Input/stories/select.stories.tsx
For anytime NPS component, needed to extend the select component to more clearly separate workflows. Added a grouping option.
Manual
=> frontend: extending select to add grouping option

backend/service/aws/dynamodb.go, backend/service/aws/dynamodb_test.go
This PR fixes unintended behavior in the DynamoDB service's logic for enforcing AWS capacity provisioning limits. When scaling up a table that is already provisioned above the max capacity (40000 by default), requests are always erroneously blocked because the requested capacity exceeds the limit.
The fix is to ignore that max limit for tables that are already provisioned above the maximum, and only enforce the scale-factor limit instead (200% of current capacity by default) unless the ignore flag is passed.
Unit tests
=> dynamodb: fix scaling limits

frontend/workflows/projectSelector/src/project-selector.tsx
Issue with deprecated projects is causing alarms with attempting to load from the stored state. To get around this we are temporarily bypassing the loading of the stored state and instead will just start fresh.
Manual
=> dash: removing usage of local storage temporarily

frontend/packages/core/src/NPS/header.tsx
If a workflow route does not have a display name it would be blank, in this case we will default to the workflows display name.
Manual
=> frontend: nps - defaulting displayName

frontend/packages/app/src/clutch.config.js, frontend/packages/core/src/Contexts/tests/testContext.tsx, frontend/packages/wizard/src/index.tsx, frontend/packages/wizard/src/wizard.tsx, frontend/workflows/dynamodb/src/index.tsx, frontend/workflows/dynamodb/src/update-capacity.tsx, frontend/workflows/ec2/src/index.tsx, frontend/workflows/ec2/src/reboot-instance.tsx, frontend/workflows/ec2/src/resize-asg.tsx, frontend/workflows/ec2/src/terminate-instance.tsx, frontend/workflows/ec2/src/tests/__snapshots__/resize-asg.test.tsx.snap, frontend/workflows/ec2/src/tests/__snapshots__/terminate-instance.test.tsx.snap, frontend/workflows/envoy/src/index.tsx, frontend/workflows/envoy/src/remote-triage/index.tsx, frontend/workflows/envoy/src/tests/__snapshots__/remote-triage.test.tsx.snap, frontend/workflows/k8s/src/cordon-node.tsx, frontend/workflows/k8s/src/delete-pod.tsx, frontend/workflows/k8s/src/index.tsx, frontend/workflows/k8s/src/resize-hpa.tsx, frontend/workflows/k8s/src/tests/__snapshots__/delete-pod.test.tsx.snap, frontend/workflows/k8s/src/tests/__snapshots__/resize-hpa.test.tsx.snap, frontend/workflows/kinesis/src/index.tsx, frontend/workflows/kinesis/src/update-shard-count.tsx
Follow up to: https://github.com/lyft/clutch/pull/1989#issuecomment-1023369994. We decided to globally enable the NPS Wizard placement as opposed to having it enabled per workflow given that users will most likely either want to enable it 100% or not at all. To enable it, users will need to turn the feature flag on.
Will follow up with docs for clutch.sh
manually tested all workflows
PR undoes the changes in
1) https://github.com/lyft/clutch/pull/1903
2) https://github.com/lyft/clutch/pull/1915
https://github.com/lyft/clutch/issues/1797
=> feedback: globally enable NPS wizard

frontend/.gitignore, frontend/packages/app/cypress.json
There appears to be a bug in Cypress where failing tests hang when attempting to screenshot the client. Even on the latest version (^9.4.1) this appears to be the case.
See https://github.com/cypress-io/cypress/issues/5016 for more context.
local
=> frontend: enable video for cypress runs

frontend/packages/core/src/AppLayout/search.tsx, frontend/packages/core/src/Input/text-field.tsx
When using `small` the size doesn't fill up containers, so we can change it to `fullWidth` to get the behavior we want.
Note this is only for autocomplete. Without this, if you added autocomplete to a text field that previously did not have autocomplete, the size might change.
local
Fixes #
=> FE: Input: Change Input Textfield to be fullWidth from small

frontend/packages/core/src/AppProvider/index.tsx
Moving error boundary inside Route element instead of outside, similar to https://github.com/lyft/clutch/pull/1981/files#diff-4327e2aff12665e532737317ff7aeb684fe579812690ed68f83a175fb989e768
local - same behavior as current functionality
Fixes #
=> move error boundary

backend/service/k8s/pods.go
We were setting `GracePeriodSeconds` to zero by default, because of this we were "force" deleting pods which removes the pod from etcd state which can result in rogue resources. As there is zero guarantee that the resource will be deleted, the kubectl docs call this out [here](https://github.com/kubernetes/kubernetes/blob/438c3a51e6ee98fe3f318de1a2dddeafc0a0ec98/staging/src/k8s.io/kubectl/pkg/cmd/delete/delete.go#L60-L68). By removing this override we will respect the default grace period.
unit
=> k8s: do not force delete pods

backend/resolver/aws/aws.go, backend/service/aws/aws.go, backend/service/aws/aws_test.go
If the user supplies a value that doesn't exist in the accounts map, there would be a panic.
This PR adds a safety check to prevent that.
local
Fixes #
=> BE: aws: add safety check when accessing accounts map

.github/workflows/scaffolding.yml, docs/development/feature.md, tools/scaffolding/templates/gateway/Makefile
Fix gateway scaffolding to run yarn install even when lockfile not present.
manual
=> tools: fix yarn install when lockfile not present

frontend/packages/core/src/AppProvider/index.tsx
Remove default 404 component for landing as some workflows intentionally set this.
manual
=> frontend: remove default landing 404 for workflows

frontend/packages/core/src/NPS/feedback.tsx, frontend/packages/core/src/NPS/tests/feedback.test.tsx
We received feedback that 180 characters was not sufficient, so it has been bumped to 280. I thought about making it 500 or 360 but wanted to keep it as short as possible.
edit: Thanks to dschaller's suggestion of tweet length of 280
unit
Fixes #
=> change feedback max length to 280 from 180

frontend/packages/core/src/typography.tsx
Fix propagation of color override to typography component.
manual
=> frontend: fix typography color override

frontend/packages/core/src/Feedback/toast.tsx
- onExiting for snackbar was deprecated, so I've removed it and only utilize onClose
- Modified onClose to call onDismiss instead of setOpen
When the toast was closing with the duration and the implementing component had an onClose handler to clear an error, it was not being called because `setOpen(false)` was being used instead of `onDismiss`
manual
=> frontend: Toast - adjusting onDismiss

backend/service/shortlink/shortlink_test.go
Fixing weak assertion for json string compare, https://github.com/golang/protobuf/issues/1082 as this is discouraged. Switching to `assert.JSONEq()` which unmarshals into interfaces and then compares.
=> shortlink: fix test json assert

frontend/workflows/envoy/package.json, frontend/workflows/envoy/src/remote-triage/dashboard.tsx, frontend/yarn.lock
The goal here is to replace the nivo pie chart with a recharts pie chart.
before
after
staging
Fixes #
=> Replace nivo with recharts for pie chart in envoy triage

.github/renovate.json
Updated renovate configuration:
- Turning off lockFileMaintenance for the moment, the large amount of updates at one point is rough to test and causes too many breaking changes, better to have these split separately. Can be re-evaluated.
- Added a rule for npm/node to not update until packages have been out for 2 weeks as well as reducing frequency of updates to bi-weekly instead of weekly
- Added eslint pattern rule which should group all eslint dependencies together and try to run the lint fix to hopefully reduce work
- Added a pattern to group jest/enzyme packages under a unittest heading
- Removing eslint and jest from ignoreDeps
=> housekeeping: Updating renovate configuration

docs/_website/src/components/FrontendWorkflow/index.tsx, tools/scaffolding/templates/frontend/src/index.tsx
- Documentation requires a displayName for each route, so adding it to the scaffolding template
- Modified the FrontendWorkflow component to not add the `fw-workflow-list` without any workflows
manual
=> frontend: Handling displayName in workflow scaffolding and docs creation

backend/go.mod
We already require 1.17 to build, bumping the go directive will also make use of two new mod features [graph-pruning](https://go.dev/ref/mod#graph-pruning) & [lazy-loading](https://go.dev/ref/mod#lazy-loading). In 1.17 there is an additional `require` block that is used to specify all package transitive dependencies, as noted [here](https://go.dev/ref/mod#go-directive).
n/a
Fixes https://github.com/lyft/clutch/issues/2094
=> backend: go mod directive to 1.17

frontend/packages/core/src/Feedback/note.tsx, frontend/packages/core/src/Feedback/stories/note-panel.stories.tsx
It is useful to be able to add a link to a note, as well as a location field.
local
storybook
Fixes #
=> FE: core: add support for a link and location to Notes

frontend/packages/core/src/Input/text-field.tsx
I noticed that if onChange is null or undefined that can cause an error here because there is an assumption that it is not.
local
Fixes #
=> FE: Text-field: prevent null onChange from breaking things

frontend/packages/core/src/button.tsx
- PR [6/x] for ShortLinks
- No reliance on other PRs
- Modifies the Clipboard button to have an optional tooltip wrapped around it for ease of understanding
manual
=> feature: ShortLinks - Tooltip on Clipboard

frontend/packages/core/src/Charts/helpers.tsx, frontend/packages/core/src/Charts/linearTimeline.tsx, frontend/packages/core/src/stories/timeseries.stories.tsx
The goal of the charting library is that defaults should lead to an appearance similar to Grafana. This is the 1st of many that will change the appearance.
Also added more time formatting funcs for users into the stories.
before:
after:
local
Fixes #
=> FE: charting: change dashed grid lines to solid ones

backend/service/github/github.go
We are not able to enable Taskqueue topic management in Clutch because of the time used to clone Runtime repo. This new option can speedup git clone from 3min to 15sec as tested locally.
local
Fixes #
=> github: add SingleBranch option in git clone

backend/service/github/github.go, backend/service/github/github_test.go
When using an application for authentication (vs a personal access token), the token will expire and needs to be refreshed. Prior to this change we were storing the token once on boot and never refreshing it.
Unit.
=> github: App auth token refresh

backend/service/github/github.go, backend/service/github/github_test.go
Commits would fail in the absence of a global git config due to missing author information. Instead we embed the author information directly, using authn claims to populate user information.
=> github: add author information to branch creation

frontend/workflows/projectCatalog/src/details/quick-links.tsx, frontend/workflows/projectCatalog/src/details/quickLinks.tsx
Adds support for images to the quick links.
Fixes #
=> FE: Project Catalog: Quicklinks with images

frontend/workflows/projectCatalog/src/details/info/chipsRow.tsx
- Adds a chevron icon to indicate a chip has a link and is clickable
manual
=> ProjectCatalog: Adding chevron identifying a chip with a link

frontend/workflows/projectCatalog/src/catalog/catalog-reducer.tsx, frontend/workflows/projectCatalog/src/catalog/index.tsx
Move error to text field helper text when project catalog search fails
manual
=> frontend: move error to text field in project catalog search

frontend/workflows/projectCatalog/src/details/info/languageRow.tsx, frontend/workflows/projectCatalog/src/helpers/language-icon.tsx
Add alt text to the language icons since they're not the easiest thing to decipher. Also make "Language" plural when two or more languages are listed on the details card.
=> catalog: add language title and plural

frontend/packages/core/src/Input/text-field.tsx
disable the end adornment for text fields when no value is present in the field
manual
=> frontend: disable end adornment when no value in text field

frontend/workflows/projectCatalog/src/catalog/index.tsx, frontend/workflows/projectCatalog/src/catalog/project-card.tsx, frontend/workflows/projectCatalog/src/catalog/storage.tsx
Add ability to reset default state of project catalog index. This continues to allow users to remove all projects (even the ones they own). If all projects have been removed users will see a placeholder (see below). On initial load (e.g. no existing state) we will fetch all the projects a users owns.
manual
=> frontend: allow users to reset project catalog index state

tools/scaffolding/templates/frontend/package.json, tools/scaffolding/templates/gateway/frontend/package.json
add resolution block for react types as some of our deps don't pin this transitive dep
```
=> Found "@types/react@18.0.3"
info Has been hoisted to "@types/react"
info Reasons this module exists
- Hoisted from "@clutch-sh#tools#@types#enzyme#@types#react"
- Hoisted from "@clutch-sh#wizard#@material-ui#core#@types#react-transition-group#@types#react"
- Hoisted from "@clutch-sh#wizard#@clutch-sh#core#material-table#@material-ui#pickers#@types#styled-jsx#@types#react"
- Hoisted from "@clutch-sh#wizard#@clutch-sh#core#material-table#react-beautiful-dnd#react-redux#@types#react-redux#@types#react"
- Hoisted from "@clutch-sh#wizard#@clutch-sh#core#material-table#react-beautiful-dnd#react-redux#@types#react-redux#@types#hoist-non-react-statics#@types#react"
```
See …
=> tools: add resolution for @types/react to scaffolding

backend/mock/service/awsmock/awsmock.go, backend/service/aws/aws.go, backend/service/aws/aws_test.go
Adds direct client access for AWS account/region clients, which may be needed if someone wants to do implement some custom logic with AWS clients that does not makes sense to put in the upstream client.
Unit
=> aws: add direct client access

backend/.golangci.yml, backend/middleware/accesslog/accesslog_test.go, backend/mock/service/k8smock/k8smock.go, backend/mock/service/topologymock/topologymock.go, backend/module/chaos/experimentation/xds/poller_test.go, backend/module/chaos/serverexperimentation/xds/rtds_faults_generator.go, backend/module/feedback/feedback_test.go, backend/service/auditsink/slack/slack_helper_test.go, backend/service/auditsink/slack/slack_test.go, backend/service/k8s/configmap_test.go, backend/service/k8s/cronjob_test.go, backend/service/k8s/deployment_test.go, backend/service/k8s/event_test.go, backend/service/k8s/hpa_test.go, backend/service/k8s/job_test.go, backend/service/k8s/namespace_test.go, backend/service/k8s/pods_test.go, backend/service/k8s/service_test.go, backend/service/k8s/statefulset_test.go
`goimports` is not a strict superset of `gofmt`
as gofmt additionally performs simplification,
so Lyft's (internal) golangci-lint baseline has both linters enabled.
You can see the additional changes from adding `gofmt`
made automatically via `make backend-lint-fix` here.
None
`make backend-lint; echo $?`
Fixes #
=> backend: align with Lyft golangci-lint baseline

frontend/workflows/projectSelector/src/project-selector.tsx, frontend/workflows/projectSelector/src/selector-reducer.tsx
- Found issue when a partial failure is returned and the dispatches are not playing nice when called one after another.
- Instead of calling two separate reducer actions, combined the logic into just `HYDRATE_END` which fixes the issues with the state
manual
Fixes #
Future PR will include unit tests to specifically cover these scenarios
=> frontend: ProjectSelector state bug

frontend/workflows/k8s/src/delete-pod.tsx, frontend/workflows/k8s/src/index.tsx, frontend/workflows/k8s/src/tests/__snapshots__/delete-pod.test.tsx.snap
It would be nice to support notes in different locations for the delete pod flow. This PR adds support for prop-drilling the notes from the config down to the delete pod workflow. Note that the delete pod workflow does not work in local dev because of the way k8s clusters are set up.
There are generally 2 ways that users get to the delete pod workflow - 1. is through the k8s dashboard, and 2. is through the normal sidebar. The link from the k8s dashboard will jump to the second step in the wizard. The notes can potentially show up on the first step and second steps of the wizard, depending on their `location` field. Thus, no matter which way the users are using the delete pod workflow, they will see the notes.
Fixes #
=> FE: add support for location notes in delete pod

frontend/workflows/projectCatalog/src/details/index.tsx, frontend/workflows/projectCatalog/src/details/quick-links.tsx
In the case where there are more than 5 links, there is an overflow popout now. There is also a button that will allow for configuration.
local
Fixes #
=> FE: proj catalog: add button for configuration and overflow for qlinks

frontend/workflows/projectSelector/src/project-group.tsx, frontend/workflows/projectSelector/src/project-links.tsx
Add the option for quicklinks to the project selector, such as links to logs, grafana, etc.
Note that there is a very slight issue with some of our source images - the k8s one has a slightly excessive border around it which leads to it looking slightly misaligned. However, I don't think anyone will really notice. There are also differences between the figma and reality because in figma there is differing padding due to the sizing of the icons.
I also thought about making the whole box clickable instead of the image and text but I wasn't sure if that would be confusing.
Note I messed with the padding a fair amount and tried to end up with something that looks good. If you look closely at the inspection it looks like some values are 1 or 2 pixels off but I think they look fine. The top …
=> FE: Project Selector: Add Quick Links

frontend/packages/core/src/tab.tsx
It is convenient to allow for a callback function to communicate back the tab index to a parent.
Fixes #
=> FE: allow for callback to set value in Tabs component

frontend/workflows/projectCatalog/src/config/index.tsx, frontend/workflows/projectCatalog/src/index.tsx
- Making `onError` optional since it is currently set during `cloneElement`
- Making `defaultRoute` optional
- Adjusted onError handler and will check if the user has already defined one and call that one before setting the error
manual
=> frontend: ProjectCatalog Config params patch

frontend/workflows/projectCatalog/src/details/index.tsx, frontend/workflows/projectCatalog/src/details/quick-links.tsx
Since settings button isn't working yet we can gate it using a feature flag. We also use flex to put the icons at the same height.
before:
after:
edit: might not need the feature flag because https://github.com/lyft/clutch/pull/2219 will probably be merged in soon
Also fixed the text to be `noWrap` to prevent wrapping of long links, and set spacing to 1 for that grid in the corner.
Fixes #
=> FE: fix alignment of icons and add feature flag for settings button

frontend/packages/tools/workflow-registrar.js
Add support for package scopes to the workflow registrar. This allows for packages with conflicting names (@a/bar and @b/bar) to both be registered via the Clutch config utilizing the package scope for uniqueness.
manual
=> frontend: add package scope support to workflow registrar

frontend/packages/core/src/tests/tab.test.tsx
Another test, this one for the Tabs component. This part of an wider effort to add more FE tests to Clutch.
Fixes #
=> FE: add a test to Tabs component

frontend/packages/core/src/typography.tsx
add `noWrap` props from material ui typography component to Clutch typography component.
manual
=> frontend: add noWrap prop to typography component

frontend/workflows/projectSelector/src/project-selector.tsx, frontend/workflows/projectSelector/src/selector-reducer.tsx, frontend/workflows/projectSelector/src/types.tsx
Ran into an error when an error is returned via onError it wasn't being cleared. So if you successfully make a change afterwards you would get the same initial error. This PR modifies the logic so after calling `onError` it will immediately dispatch a change to clear the error from the state.
manual
To test, search for a deprecated project (which will generate a toast), let it clear. Then look up anything else. You'll get the same initial error as the first one.
=> frontend: ShortLinks Patch for ProjectSelector

backend/mock/service/k8smock/k8smock.go, backend/service/k8s/clientset.go, backend/service/k8s/clientset_test.go, backend/service/k8s/k8s.go, backend/service/k8s/k8s_test.go
Add direct client access for K8s clientsets, which may be needed if you wanted to implement custom logic with the K8s client in a users private gateway.
Unit
=> k8s: add direct clientset access

backend/mock/service/k8smock/k8smock.go, backend/service/k8s/clientset.go, backend/service/k8s/clientset_test.go, backend/service/k8s/k8s.go, backend/service/k8s/k8s_test.go
In https://github.com/lyft/clutch/pull/2232 i made changes to allow for direct cientset access. However upon looking back the implementation could of been simpler without needing to change the `ClientsetManager` interface at all. This refactor uses the existing `GetK8sClientset` func with defaults. I also updated the the k8s interface to include a context for this new function as its now required.
Unit.
=> k8s: refactor direct clientset access

tools/compile-protos.sh
In the case where in a user has a fresh clone of clutch and in their directory hierarchy they have a package.json (higher than clutch), yarn chooses to use that directory as its installation point.
In doing so, the path to pbjs that we expect isn't right, because the pbjs we installed ended up in a different directory.
If we first call yarn init, we generate a package.json in the expected path, ensuring that yarn installs to the correct directory.
Manually invoked `make api` in this repo as a standalone and as a gateway. Between invocations I cleared the build/bin directory.
=> tools: fix yarn initalization in compile-protos

tools/preflight-checks.sh
This updates the pre-flight script to look for the local yarn binary that's installed into the local bin directory instead of globally. As part of this modification the script needs to read in a local directory override since it can be run from any gateway and needs to check that gateway for the yarn binary.
manual
=> tools: update pre-flight check script for local yarn binary

frontend/workflows/projectCatalog/src/details/index.tsx
The final design is like the second pic but with 8px padding added to the top
Another potential option is to use `justify-content` to center the grid items rather than having things left aligned like they are now. Note that the project catalog search page has things left aligned, not centered, so I guess it is good to be consistent.
Before:
After [FINAL DESIGN]:
[old design] After (before shifting things over for Josh's comment):
justify content strategy (could also center the top grid row as well, you can see the lower one is centered but it doesn't line up with the header anymore):
Fixes #
=> FE: project catalog: adjust spacing

frontend/packages/core/src/Input/toggle-button-group.tsx
Removed some unnecessary padding
Fixes #
=> FE: remove built in padding around toggle group

frontend/packages/core/src/AppProvider/index.tsx
- From the eslint upgrade a usage a `useMemo` was not updated to recreate on state changes, this caused issues when attempting to generate a short link as it would utilize an empty state.
manual
=> frontend: Fix for short link generation

backend/go.mod, backend/go.sum, backend/module/chaos/experimentation/xds/poller.go, backend/module/chaos/experimentation/xds/poller_test.go, backend/module/chaos/experimentation/xds/xds.go
[There were some breaking changes to the API, this should fix them. It also blocks a host of other grpc upgrades.
Unit
=> housekeeping: envoyproxy/go-control-plane to hash 7857518

backend/mock/service/awsmock/awsmock.go
Adding schema info in mock describe table call. By default this would have been nil values, and it's more helpful with some test data. Also updated some of the variable setting into inline instantiation for easier readability and since the variables weren't being modified in a significant way.
=> [DS-9347] Adding schema info in mock describe table call

backend/service/envoyadmin/parse.go, backend/service/envoyadmin/parse_test.go
Fix a possible nil pointer error when envoy admin returns no CLI options.
included - unit
=> backend: fix nil pointer in envoy admin parser

backend/service/aws/aws.go, backend/service/aws/aws_test.go
AWS has too many services and it is impossible for clutch to support all
of them. If someone wants to write a private extension for a given
service, today there is no way to get the config/credentials to
construct a client. This patch exposes a new method to get regional
config so that clients to an unsupported service can be created.
All unit tests performed. No impact to any additional interfaces
=> aws: expose access to aws.Config from DirectClient

frontend/packages/core/src/popper.tsx
We have a use case for wanting to disable a popper menu item if a condition isn't meant so PR adds `disabled` to the set of props that are picked from `ListItemProps`.
=> Frontend: Add disabled prop to PopperItemProps

frontend/packages/core/src/Input/radio.tsx, frontend/packages/core/src/chip.tsx
- fixed broken radio buttons. its prop `checked` was changed to `$checked` for the styled component wrapping it. however, the underlying MUI component still expects a `checked` prop to function
=> Fix broken radio buttons

frontend/package.json
PR adds `material-table` to the package.json in the dev dependencies. This is needed for an internal gateway we're spinning up. 
We're not sure why this is needed for the new gateway and not our other internal implementation but this change unblocks the failing build of the new gateway.
shout out to @jdslaugh for realizing this was what was needed for the new gateway.
Fixes #
=> Frontend: add new package to dev deps

frontend/packages/core/src/AppProvider/index.tsx, frontend/packages/core/src/AppProvider/workflow.tsx
- For custom gateways, need a way to override the landing page if so desired. This PR adds a check in a workflow loop that already exists to see if there is a workflow with no path (ie a landing), if so it will set a boolean variable to not render the current landing page and allow the workflow route to take over.
manual
=> frontend: Override for landing page

frontend/packages/core/src/AppLayout/header.tsx, frontend/packages/core/src/AppLayout/index.tsx, frontend/packages/core/src/AppProvider/index.tsx, frontend/packages/core/src/AppProvider/workflow.tsx
This PR adds the ability to specify a custom title and logo for the application through the new appConfiguration object or remove them altogether.
```
ReactDOM.render(
<ClutchApp
availableWorkflows={registeredWorkflows}
configuration={
process.env.NODE_ENV === "development" ? devConfig : prodConfig
}
appConfiguration={{ title: "Custom Title ", logo: null}}
/>,
document.getElementById("root")
);
```
```
ReactDOM.render(
<ClutchApp
availableWorkflows={registeredWorkflows}
configuration={
process.env.NODE_ENV === "development" ? devConfig : prodConfig
}
appConfiguration={{ title: "CustomTitle", logo: <GemIcon size="medium" /> }}
/>,
document.getElementById("root")
);
```
```
ReactDOM.render(
<ClutchApp
availableWorkflows={registeredWorkflows}
configuration={
process.env.NODE_ENV === …
```
=> frontend: Overrides for title and logo

frontend/packages/wizard/src/step.tsx
allows wizard step errors to be undefined. we already handle this case [here](https://github.com/lyft/clutch/compare/wizardStepErr?expand=1#diff-405c79e6b5521a66df72764a7fbf8f954c792fa17793e69242fafc1c4ca7bbcdL19)
Manual
=> frontend: allow wizard step errors to be undefined

frontend/packages/core/src/Input/text-field.tsx
fix text field to only show a helper text icon prefix if `helpText` has been set. At the moment this shows an icon with no text.
manual
=> frontend: text field - only show error icon when help text set

frontend/packages/core/src/Input/select.tsx
- Fixing bug with Select defaultOption
Context:
When using the grouped feature the defaultIdx was not taking into account the flatOptions length and instead was using just the normal options length. When grouping this would be noticeably shorter and would lead to the incorrect defaultOption being selected.
manual
=> frontend: Fixing Select defaultOption bug

frontend/packages/core/src/Feedback/toast.tsx
- With the upgrade to MUIv5 the Toast component was no longer working and instead throwing an error `Cannot read property scrollTop of null`
- Fix was to wrap the children in a div to correctly forward the ref, taken from https://mui.com/material-ui/migration/troubleshooting/#cannot-read-property-scrolltop-of-null
NOTE: Tried to use React.forwardRef but was unable to get it to work correctly, wrapping the alert component mitigates the issue without any other changes
manual
=> frontend: Toast Bug Fix

frontend/workflows/dynamodb/src/index.tsx, frontend/workflows/dynamodb/src/update-capacity.tsx
This PR adds support for displaying resolver notes from the DynamoDB Update Capacity workflow configuration file. 
Example note: 
Generated from example `clutch.config.js`:
```
"@clutch-sh/dynamodb": {
updateCapacity: {
componentProps: {
resolverType: "clutch.aws.dynamodb.v1.Table",
notes: [
{
severity: "info",
text: `
This workflow immediately provisions an additional boost of read and write capacity for a DynamoDB table and/or global secondary index.
Capacities set by this workflow are **TEMPORARY**, subject to the table's autoscaling rules.
View workflow docs at:
`,
link: "https://insert-workflow-documentation-link-here",
location: "resolver",
},
],
enableOverride: true,
},
},
},
```
Tested locally with custom gateway config notes.
Fixes #
=> dynamodb: add support for config notes

frontend/workflows/projectCatalog/src/config/index.tsx
- When utilizing project catalogs configuration settings it was pushing new history onto the stack which was problematic with how many entries it was utilizing. Setting replace will replace the current entry allowing the back button to work correctly
manual
=> frontend: Catalog - Adding replace to navigate

backend/service/github/github.go, backend/service/github/github_test.go
Fixes possible panic if `resp` is nil from the RoundTrip call when trying to evaluate the response headers from a GitHub GraphQL query to gauge the remaining GitHub rate limit.
unit
=> backend: only emit github ratelimit gauge on valid response

frontend/packages/core/src/Table/metadata-table.tsx
Removes width restriction on disabled text fields for metadata table
**Before**
**Now**
manual
=> frontend: remove width limit on metadata table disbaled textfield

frontend/packages/core/src/tab.tsx
centers tab layout for both text and icons
**before**
**now**
manual
=> frontend: center tab layout

frontend/packages/core/src/NPS/header.tsx
Modifies the NPS header component, which already reads in the workflows, to check for component props on each visible route and add any custom nps additions found under its route. 
NOTE: This is only visible to routes where hideNav: false as it is hidden from the workflow context otherwise
Example:
```
"@clutch-sh/project-catalog": {
catalog: {
trending: true,
componentProps: {
additionalNPS: [
{ label: "New Config", value: "/config/new config" },
],
},
},
},
```
manual
=> frontend: NPS - Add ability to specify custom sub routes

backend/service/audit/audit.go, backend/service/audit/audit_test.go
We were not filtering before because the filter configuration was not saved on the struct.
=> audit: save filter configuration on service

backend/service/audit/audit.go, backend/service/audit/storage/sql/sql.go, backend/service/audit/storage/sql/sql_test.go
Use a dedicated connection for the audit sink advisory lock. Previously we were using the db session pool for all advisory lock requests, the issue with this is that in order for a session level advisory lock to be unlock, the unlock request must come from the same session. This [post](https://engineering.qubecinema.com/2019/08/26/unlocking-advisory-locks.html) summarizes the issue we are running into nicely.
In this pr I also moved the `readAndFanout()` before calling `ReleaseLock()`, this was the original intent but this was not setup correctly.
unit
=> audit sink sql: use dedicated connection for advisory locks

frontend/packages/core/src/Table/metadata-table.tsx, frontend/workflows/k8s/src/resize-hpa.tsx
For the K8s Resize HPA flow, a label is added above the text fields on the Mix/Max Size to clarify what they are. To allow this customization, PR adds a new prop to the metadata-table component for providing these labels.
Local
**Example of a workflow where the new prop isn't set**
Fixes #
=> K8s Resize HPA: add label for text fields on mix/max size row

backend/service/audit/storage/sql/sql.go
In the last update to this code, the closed connection is kept around and is no longer viable. For now just keep the connection.
=> audit: keep connection held for now

backend/service/audit/storage/sql/sql.go
It seems like its best to close the connection completely and re-create for each sink loop. This actually works out better in the event the connection is severed for whatever reason this will attempt to connect on the next invocation.
=> audit sink sql: close advisory conn

frontend/packages/core/src/Input/select.tsx
fixes positioning of select expand/collapse icon. Currently by having it centered there is a chance the icon can overlap with the text. This does also adjust some of the existing places where the icon is more indented at the moment from the end of a field.
**Current Behavior**
Resolver
**Proposed Changes**
Resolver
manual
=> frontend: fix select icon position

docs/_website/package.json, docs/_website/yarn.lock
includes unmet peer dependencies from `@docusaurus/core` and `@docusaurus/preset-classic`
```
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "@docusaurus/core > react-loadable-ssr-addon-v5-slorber@1.0.1" has unmet peer dependency "react-loadable@*".
warning "@docusaurus/preset-classic > @docusaurus/theme-search-algolia > @docsearch/react > @algolia/autocomplete-preset-algolia@1.7.2" has unmet peer dependency "@algolia/client-search@>= 4.9.1 < 6".
```
CI
=> housekeeping: docs include required peer deps

frontend/workflows/kinesis/package.json, frontend/workflows/kinesis/src/update-shard-count.tsx
Right now, users could potentially be confused as to why the same shard count values are showing up multiple times in the select. This PR makes it so that only unique values are shown.
Fixes #
=> FE: Kinesis: make shard count unique

tools/scaffolding/templates/frontend/package.json
`make scaffold-workflow` was throwing an error during compilation. Rooted it out to the `@mui` packages being updated past what they're locked to in core. Locking the versions in the resolutions fixes the issue
```
$ /private/var/folders/94/f35bk_5d3fb_5knz5ytdb2h00000gn/T/clutch-scaffolding-1026524175/node_modules/.bin/tsc
node_modules/@clutch-sh/core/dist/Input/date-time.d.ts(3,51): error TS2314: Generic type 'DateTimePickerProps' requires 1 type argument(s).
node_modules/@mui/lab/Timeline/Timeline.d.ts(48,77): error TS2344: Type '"hidden" | "color" | "style" | "position" | "translate" | "slot" | "title" | "children" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | ... 247 more ... | "onResizeCapture"' does not satisfy the constraint …
```
=> frontend: Scaffolding - Fixing Workflow

frontend/packages/core/src/Table/metadata-table.tsx, frontend/packages/core/src/Table/stories/metadata-table.stories.tsx
Its nice to be able to have a tooltip for a disabled text field.
Fixes #
=> FE: Metadata Table: add tool tip prop for disabled text field

docs/development/feature.md, examples/amiibo/frontend/workflows/amiibo/package.json
Noticed the documentation was still referencing `1.0.0-beta` which was material ui 4, now that we've upgraded to material-ui 5 this should reflect `2.0.0-beta`.
=> housekeeping: Documentation Update

frontend/packages/core/src/Input/toggle-button-group.tsx
After meeting as a group, we decided to update the ToggleButtonGroup component styles from the base MaterialUI component, to a custom design that goes in line with the current UI.
Before:
After:
manual
=> Frontend: ToggleButtonGroup styles update

frontend/packages/core/src/card.tsx
Card components in the landing page adjusted their height according to the card's description length. That caused disparity in the cards sizes. This update sets the Card height to a fixed 214px.
Before:
After:
manual
=> Frontend: Add set height for Card component

frontend/packages/core/src/button.tsx, frontend/packages/core/src/stories/button.stories.tsx, frontend/packages/core/src/tests/__snapshots__/button.test.tsx.snap, frontend/packages/core/src/tests/button.test.tsx
MUI supports multiple button sizes (https://mui.com/material-ui/react-button/#sizes) which we did not currently support. Adding support for them here as well as rotating the tests to use React Testing Library.
This will also be utilized as part of the NPS Banner component.
manual
=> frontend: Button Sizing Extension

frontend/packages/core/src/Input/toggle-button-group.tsx
The hover state for the ToggleButtonGroup when selected had a background change that made reading the text in the button difficult. The behaviour was updated to go in line with the current design system. 
Before:
After:
Manual
=> Frontend: Set a style for the ToggleButtonGroup hover when selected

backend/go.mod, backend/go.sum
This PR sets the Go version to 1.19 in go.mod and runs `go mod tidy` to update go.sum too.
We already set the Docker tag and CI to 1.19 (https://github.com/lyft/clutch/pull/2463, https://github.com/lyft/clutch/pull/2426).
Fixes #
=> housekeeping: set Go version to 1.19

frontend/packages/core/src/confirmation.tsx
The padding above the confirmation component's icon was reduced to optimise space usage.
Before:
After:
Manual
=> Frontend: reduced top padding in Confirmation

frontend/package.json
Saw this message when running storybook:
```
attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry
```
So adding the flag to disable it. 
Logging the output of what they collect shows it's nothing sensitive (below) but just to be safe for everyone.
```
[telemetry]
{
"eventType": "start",
"payload": {},
"metadata": {
"generatedAt": 1671146210968,
"builder": {
"name": "webpack4"
},
"hasCustomBabel": false,
"hasCustomWebpack": false,
"hasStaticDirs": false,
"hasStorybookEslint": false,
"refCount": 0,
"metaFramework": …
```
=> housekeeping: Disable Storybook Telemetry

frontend/packages/core/src/AppLayout/stories/header.stories.tsx, frontend/packages/core/src/AppLayout/stories/logo.stories.tsx, frontend/packages/core/src/AppLayout/stories/notifications.stories.tsx, frontend/packages/core/src/AppLayout/stories/searchfield.stories.tsx, frontend/packages/core/src/AppLayout/stories/user-information.stories.tsx, frontend/packages/core/src/Assets/stories/icons.stories.tsx, frontend/packages/core/src/Input/stories/checkbox-panel.stories.tsx, frontend/packages/core/src/stories/card.stories.tsx, frontend/packages/core/src/stories/clipboard-button.stories.tsx, frontend/packages/core/src/stories/confirmation.stories.tsx, frontend/packages/core/src/stories/landing-card.stories.tsx, frontend/packages/core/src/stories/landing.stories.tsx, frontend/packages/core/src/stories/link.stories.tsx, frontend/packages/core/src/stories/not-found.stories.tsx, frontend/packages/core/src/stories/paper.stories.tsx, frontend/packages/core/src/stories/text.stories.tsx, frontend/packages/core/src/stories/timeago.stories.tsx, frontend/packages/core/src/stories/typography.stories.tsx
There is a number of stories with no siblings in Storybook, this adds unnecessary nesting. Stories matching this pattern were hoisted to simplify the navigation.
Before:
After:
manual
=> frontend: hoist single storybook stories up a level

frontend/packages/core/src/Assets/global.ts, frontend/packages/core/src/Feedback/stories/note.stories.tsx
The Note component is subdivided by severity in Storybook, adding items to the stories navigation panel. By using controls the stories were unified to a single entry with the same severities options.
Before:
After:
Manual
=> frontend: hoist note stories

frontend/packages/core/src/stories/button-group.stories.tsx, frontend/packages/core/src/stories/button.stories.tsx, frontend/packages/core/src/stories/icon-button.stories.tsx
The stories for the Button component have redundant entries for props variations. Those entries were hoisted or simplified by using controls.
Before:
After:
manual
=> frontend: hoist button related stories

frontend/packages/core/src/Assets/global.ts, frontend/packages/core/src/Feedback/alert.tsx, frontend/packages/core/src/Feedback/stories/alert.stories.tsx
The Alert component is subdivided by severity and title in Storybook, adding items to the stories navigation panel. By using controls the stories were unified to a single entry with the same title/severities options.
Before:
After:
Manual
=> frontend: hoist alert stories

frontend/packages/core/src/stories/accordion-group.stories.tsx, frontend/packages/core/src/stories/accordion.stories.tsx, frontend/packages/core/src/stories/panel.stories.tsx
The accordion stories are subdivided by states of the components. Controls were used to reduce the number of stories.
Before:
After:
manual
=> frontend: hoist accordion stories

frontend/packages/core/src/Input/text-field.tsx, frontend/packages/core/src/Table/metadata-table.tsx
The numeric input fields, both disabled and enabled truncated their contents with no indication that additional text could be hidden after the cut. This could lead to a wrong reading of the stored value.
A prop `truncateWithEllipsis` was added to the TextField component to add an ellipsis (`...`) whenever the content of the input overflows. The prop is leveraged by MetadataTable by passing a flag `truncateWithEllipsis` in the body of `RowData`.
Max Size without the flag enabled, Desired Size with the flag enabled
Manual
=> frontend: add ellipsis prop to text fields

frontend/workflows/k8s/src/resize-hpa.tsx
In the case where the new min or new max replicas are different than the old min or max by more than 50%, display a warning note indicating as such.
Tested on staging (see private PR for screenshot)
Fixes #
=> FE: Resize HPA: add a warning on confirmation if new min or max replicas are different by more than 50%

frontend/packages/core/src/Input/select.tsx, frontend/packages/core/src/Input/stories/select.stories.tsx, frontend/packages/core/src/Input/tests/select.test.tsx, frontend/packages/core/src/Resolver/hydrator.tsx
Updating storybook for select, came from changes in https://github.com/lyft/clutch/pull/2493. This modifies the documentation section of storybook to be auto-generated based on the inputs for Select, allowing it to be interacted with at a deeper level without a need for multiple stories. 
manual
=> frontend: Storybook - Updating Select Documentation

frontend/packages/core/src/Input/select.tsx, frontend/packages/core/src/Input/stories/select.stories.tsx, frontend/packages/core/src/Input/tests/select.test.tsx
Modifies Select component to support multiple values. MUI Select uses an array type as the value (https://mui.com/material-ui/react-select/#multiple-select) when multiple is true. This PR changes the internal representation of selected values to an array, even when multiple is False, to support type consistency for the component.
Manual.
=> frontend: Select - support multiple

backend/module/authn/authn_test.go
currently this asserts `err` is an error and prints the text `"error: description"` when this fails. The test should be asserting that the error's message is `"error: description"` instead.
CI
=> backend: fix authn error test assertions

frontend/packages/core/src/Input/tests/date-time.test.tsx, frontend/packages/core/src/Input/tests/select.test.tsx
As part of the migration of unit tests to React Testing Library, the input/ component tests for Select and DateTimePicker were updated.
manual
=> frontend: migrate input tests to rtl

frontend/workflows/ec2/src/reboot-instance.tsx, frontend/workflows/ec2/src/resize-asg.tsx, frontend/workflows/ec2/src/terminate-instance.tsx, frontend/workflows/ec2/src/tests/__snapshots__/resize-asg.test.tsx.snap, frontend/workflows/ec2/src/tests/__snapshots__/terminate-instance.test.tsx.snap, frontend/workflows/k8s/src/cordon-node.tsx, frontend/workflows/k8s/src/delete-pod.tsx, frontend/workflows/k8s/src/tests/__snapshots__/delete-pod.test.tsx.snap, frontend/workflows/kinesis/src/update-shard-count.tsx, frontend/workflows/sourcecontrol/src/create-repository.tsx
A user felt that the word Result was more suited than Confirmation, because at that point things were already confirmed.
Fixes #
=> FE: Change wording from Confirm to Result

frontend/workflows/audit/src/logs/event-row.tsx, frontend/workflows/audit/src/logs/index.tsx
Fixes the audit logs workflow view to trigger an event request when the quick time range is selected.
manual
=> frontend: fix audit workflow quick time selection

frontend/workflows/audit/src/logs/event-row.tsx, frontend/workflows/audit/src/logs/index.tsx
Fixes two issues with the audit workflow:
- allows users to resubmit queries even after selecting and submitting a time range (the only limitation is users cannot query within a second)
- If the server sends back a response with the next page token empty it's stored in state and when a subsequent query is submitted we attempt to reset the page token but this doesn't happen before `fetch` is invoked which triggers the quick return since it believes there is no next page token to fetch. This is fixed by explicitly calling fetch with a zero page token.
manual
=> frontend: audit workflow fix state bug

frontend/packages/core/src/NPS/banner.tsx, frontend/packages/core/src/button.tsx
Design system changed padding for the NPS Banner button as well as button sizing for xsmall. This PR adjusts both to use the new values.
Manual & storybook
=> frontend: NPS Banner Styling Patch

frontend/packages/core/src/NPS/feedback.tsx, frontend/packages/core/src/NPS/tests/emojiRatings.test.tsx, frontend/packages/core/src/NPS/tests/feedback.test.tsx, frontend/packages/core/src/NPS/tests/header.test.tsx, frontend/packages/core/src/NPS/tests/wizard.test.tsx, frontend/packages/core/src/NPS/wizard.tsx
Migrated tests away from enzyme for the NPS related components (NPSWizard, NPSFeedback, NPSHeader and EmojiRatings).
manual
=> frontend: frontend convert tests nps

frontend/packages/core/src/AppLayout/drawer.tsx, frontend/packages/core/src/AppLayout/search.tsx, frontend/packages/core/src/AppLayout/utils.tsx, frontend/packages/core/src/AppProvider/index.tsx, frontend/packages/core/src/AppProvider/workflow.tsx, frontend/packages/core/src/NPS/header.tsx
Noticed we were having some issues if `hideNav: true` was set in our configuration then it would not show up in the NPS Header, however this was a necessary step to remove the item from the drawers and eventually hide them.
So this PR does a few things:
- Adds a new filterHiddenRoutes to our utils file in AppLayout, this function has the same functionality as the old one in AppProvider
- Removed the filtering in AppProvider and left the landing page check
- Modified the Search Component to use the new filterHiddenRoutes function
- Modified the Drawers Component to use the new filterHiddenRoutes function
- Modified the NPS Header Component to add to the dropdown if either `hideNav: false` or `additionalNPS` is set
manual
=> frontend: Modifying filtered workflows to be handled at the component level

frontend/packages/core/src/Feedback/error/index.tsx, frontend/packages/core/src/Feedback/error/stories/error.stories.tsx
In order to allow additional content to complement an error message, this prop allows to pass children to the Error component.
manual
=> frontend: add children prop to error component

frontend/workflows/envoy/src/remote-triage/index.tsx
Right now the label implies that you can put in a host name, but that might be confusing.
Fixes #
=> Remove host name from label since only address is supported

frontend/packages/core/src/Charts/tests/timeseries.test.tsx
As part of the ongoing migration away from enzyme and into RTL, this PR updates the tests for the TimeseriesChart component.
As an alternative to checking for components and their prop values, I'm relying in querySelectors to target classes assigned by recharts and attributes in the generated elements.
manual
=> frontend: migrate charts tests to rtl

frontend/packages/core/src/AppProvider/index.tsx, frontend/packages/core/src/NPS/header.tsx
Was found that the NPS header was not closing when clicking outside of the container after submission. This was due to the new NPS Feedback Banner open behavior which was being retriggered and keeping it open. Also decided to put in a timeout to auto-close the feedback submission.
manual
=> frontend: NPS Header fixing close behavior

frontend/workflows/projectSelector/src/project-links.tsx
We noticed that for the QuickLinks the single links were showing up as a different color than the multi-group links. This modifies both to use an h6 typography variant which fixes the color issue and keeps them aligned with each other.
manual
=> frontend: ProjectSelector - Adjusting Single Quick Link color

frontend/packages/core/src/Table/table.tsx
The TableRow component currently can't receive additional props, which can be useful when trying to apply styles at this component's level in a table, such as a grayed out look for a disabled state. This PR adds such behavior.
manual
=> frontend: allow table row to receive extra props

.github/workflows/ci.yml
Renovate recently upgraded and locked node behind a min version of 18.x. Since we're still running 16.x, installing renovate to a specific version.
Commit where renovate was upgraded: https://github.com/renovatebot/renovate/commit/2102b706073676ae949692a6595cc590770b7803
Failures from trying to install current renovate:
https://github.com/lyft/clutch/actions/runs/4481493781/jobs/7883978530
Successful run with change:
https://github.com/lyft/clutch/actions/runs/4484340241/jobs/7884734580?pr=2621
manual
=> housekeeping: Locking renovate version to 34.x.x

frontend/packages/app/src/clutch.config.js, frontend/workflows/k8s/src/index.tsx, frontend/workflows/k8s/src/scale-resources.tsx, frontend/workflows/k8s/src/tests/__snapshots__/scale-resources.test.tsx.snap, frontend/workflows/k8s/src/tests/scale-resources.test.tsx
Adding a workflow to scale CPU and memory requests and limits in Kubernetes. 
Follow to:
https://github.com/lyft/clutch/pull/2589
https://github.com/lyft/clutch/pull/2604
* Scaled each type of resource on my cluster
* Tried with different containers on the same deployment
* Tested validation by putting in bogus inputs
* Included Jest Snapshot
=> frontend: K8s scale resources workflow

frontend/packages/core/src/AppLayout/drawer.tsx, frontend/packages/core/src/AppLayout/utils.tsx, frontend/packages/core/src/AppProvider/index.tsx, frontend/packages/core/src/AppProvider/registrar.tsx, frontend/packages/core/src/AppProvider/workflow.tsx
Adds Icon support for Drawers. This will default to using the given path which can be locally hosted or an external URL. If not present will default to the normal avatar with the first letter.
Configured by modifying the `clutch-config.js` and adding a property `icon: { path: string }`
```
"@clutch-sh/ec2": {
icon: {
path: "/example.jpg", OR "http://fake-url.com/image.png"
},
terminateInstance: {
...
},
},
```
manual
=> frontend: Adding Icon Support for Drawers

.github/renovate.json
Realized that postUpgradeTasks only work for self-hosted solutions of renovate, since we're using a hosted version this will never work. So removing to reduce the unnecessary error messages. 
https://docs.renovatebot.com/self-hosted-configuration/#allowedpostupgradecommands
https://github.com/lyft/clutch/pull/2676#issuecomment-1577428689
=> housekeeping: Updating renovate config to remove postUpgradeTask

backend/service/auditsink/slack/slack.go
Custom slack audit message templates might have text that is conditionally rendered if the info in available in the API request/response, which creates leading/trailing whitespace in the messages when the info isn't present. PR trims out the whitespace.
Fixes #
=> slack sink: trim leading/trailing whitespace in custom slack audit messages

frontend/packages/core/src/AppLayout/drawer.tsx
Some small modifications for displaying icons on drawers.
- Removed hover color if its an icon type as this was causing some outline weirdness
- Modified to use a direct style from MuiAvatar as the current one was forcing the icon into a square
manual
=> frontend: Drawer Icons Patch

backend/service/topology/querybuilder.go, backend/service/topology/querybuilder_test.go
The topology search API was not sorting as expected when one specifies a specific sort option. The issue was essentially the same as this [one](https://github.com/Masterminds/squirrel/issues/249). I later learned that postgres does not support parameterized `ORDER BY` values, and the recommended way to do that in a query is to create a sql function with the usage of `format` to populate your `ORDER BY` value. We don't need to do that here, but that was the most recommended for pure sql.
Local / Unit.
Ascending
```
➜  ~ curl --location 'http://localhost:8080/v1/topology/search' \
--header 'Content-Type: application/json' \
--data '{
"limit": 2,
"page_token": "0",
"sort": {
"direction": "ASCENDING",
"field":"column.id"
},
"filter": {
"search": {
"field":"column.id",
"text": "clutch"
}, …
```
=> topology: fix search api sort

frontend/packages/core/src/Input/text-field.tsx, frontend/workflows/projectSelector/src/project-selector.tsx
Makes modifications to autocomplete onReturn flow as well as the ProjectSelector usage of it to fix autocomplete issues.
- modifies the onReturn caller to be a debounced version so it doesn't call it multiple times from pressing enter or selecting from a dropdown
- Will fire an onChange event for onReturn so that when selecting an item from the dropdown it doesn't submit with what is currently typed in
- Adds form handling for the ProjectSelector to correctly grab the field and adds an onReturn so that it can fire when selecting something from the dropdown
manual
=> frontend: Autocomplete Adjustments

frontend/packages/core/src/AppLayout/search.tsx
Currently if the search field matches the workflow directly it just clears out and does nothing. This modifies it to automatically redirect if its a direct match, then clear it.
manual
=> frontend: Fixing Search Issue

frontend/packages/core/src/Input/form.tsx
Error present in console about usage of `first-child` versus `first-of-type`
manual
=> frontend: Fixing first-child error

frontend/packages/app/cypress/integration/navigation_spec.js, frontend/packages/core/src/AppLayout/drawer.tsx, frontend/packages/core/src/AppLayout/utils.tsx, frontend/packages/core/src/card.tsx, frontend/packages/core/src/landing.tsx
- Modifies landing cards to use icons that Drawer groups use.
- Also modifies drawers with a single child to just redirect immediately versus opening a popup
manual
=> frontend: Landing Icons and Single Drawer Item Patch

backend/service/k8s/deployment.go, backend/service/k8s/deployment_test.go
Backend update probes with validation attributes
Adding update method to update liveness and readiness probes.
https://github.com/lyft/clutch/pull/2702
No frontend changes
```
curl -X POST http://localhost:8080/v1/k8s/updateDeployment
-H 'Content-Type: application/json' 
--data 
'{"clientset": "clientset", 
"cluster": "mycluster",
"namespace": "default", 
"name": "two-container-app", 
"fields": 
{ 
"containerProbes": 
[
{"containerName": "container2", 
"readinessProbe": 
{"initialDelaySeconds": "6", "periodSeconds": "4" }
}]}}'
```
=> Backend update probes

backend/mock/service/awsmock/awsmock.go, backend/module/dynamodb/aws_test.go
This PR adds `account` field to the mock for AWS dynamodb service functions, following the changes for other AWS mocked resources in #1873. Noticed this was missing from dynamodb mocks when trying to display account info during local testing of frontend changes.
Tested by manually modifying files in the submodule used for local Clutch development; adding the `account` field to the mock fixed the errors I was running into
Fixes #
=> [backend] add account field to aws mock for ddb table

frontend/packages/core/src/AppLayout/stories/drawer.stories.tsx, frontend/packages/core/src/Table/stories/table.stories.tsx, frontend/packages/core/src/stories/stepper.stories.tsx, frontend/packages/core/src/stories/tabs.stories.tsx
Adding fill to array, build storybook is making the array empty
=> frontend: fix drawer

frontend/packages/core/src/Input/select.tsx, frontend/packages/core/src/chip.tsx, frontend/workflows/redisexperimentation/src/tests/__snapshots__/experiment-details.test.tsx.snap, frontend/workflows/redisexperimentation/src/tests/__snapshots__/start-experiment.test.tsx.snap, frontend/workflows/serverexperimentation/src/tests/__snapshots__/experiment-details.test.tsx.snap, frontend/workflows/serverexperimentation/src/tests/__snapshots__/start-experiment.test.tsx.snap
- Adds the ability to support Chips as a display type for MultiSelect.
- Exports the onClick and clickable props for Chips
- Reduces the height of Selects to `25vh` from `50vh` as I felt it was just a bit too large
manual
=> frontend: Adding Chip Support for MultiSelect

docs/_website/docusaurus.config.js
Issues with algolia search, found that if we set `contextualSearch` to false it actually fixes it.
local
https://github.com/facebook/docusaurus/issues/3805
https://github.com/facebook/docusaurus/issues/5084
=> housekeeping: Adjust algolia search params

backend/service/k8s/event.go
It was decided that we will let the FE do its sorting however it wants and not have the backend worry about it.
context https://lyft.slack.com/archives/C05FPGRQLSY/p1690400933790829
Fixes #
=> remove sorting and let fe do it

backend/.golangci.yml
Our lint CI has been timing out consistently at the current setting so updating to 10m, which we also set internally.
Fixes #
=> golangcli: increase timeout

frontend/packages/core/src/AppLayout/header.tsx, frontend/packages/core/src/AppLayout/index.tsx, frontend/packages/core/src/AppLayout/user.tsx, frontend/packages/core/src/AppProvider/index.tsx, frontend/packages/core/src/Contexts/index.tsx, frontend/packages/core/src/Contexts/preferences-context.tsx, frontend/packages/core/src/index.tsx
- Modifies the header to take customizable settings for what to display/hide.
- Can now pass in a header with a `type="HEADER"` as a child to `<ClutchApp />` and it will take over as the main header, this allows for customizing the header entirely
- Can pass children to the newly passed in Header (if you just reuse the exported one from Clutch) that will place them inside the header component
- The userInfo component now also takes children so small options or buttons can be expanded for use on the dropdown
manual
=> frontend: Adding User Preferences Context and Customizable Header

frontend/packages/core/src/AppLayout/user.tsx
Issue found with the new changes to the UserInfo component. Was defaulting children to `null` which when being cast to an array was treating it as a single entry. Instead defaulting to an empty array to fix the issue.
manual
=> frontend: Fixing Default for UserInfo component

frontend/packages/core/src/Feedback/alert.tsx
Enables the icon prop in the Alert component. This allows for overriding the icon used from the defaults based on severity.
manual
=> frontend: Alert Component Adding Icon Prop

docs/_website/docusaurus.config.js, docs/_website/src/theme/Footer/index.tsx, docs/community.md
Remove Twitter references to the now deactivated _clutchdotsh_ account
Attaching some screenshots
Fixes #
N/A
N/A
=> Remove clutchdotsh Twitter references

frontend/packages/core/src/Contexts/preferences-context.tsx
The `timeZone` preference was not being initialized, as default preferences were initialized as`{}`. This caused some `undefined` issues when trying to access it, this PR initializes the preferences object with the `timeFormat` set at `UTC`
manual
=> frontend: initialize timeFormat preference

backend/service/k8s/cronjob.go, backend/service/k8s/cronjob_test.go
Support upgrade CronJob api version
According to kube's deprecation [guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125), CronJob api on batch/v1beta1 should be deprecated on v1.25 in favor of batch/v1 which was introduced in v1.21. Let's add its support and eventually remove the legacy api as well.
See unit tests
No deadline on this right now, but eventually would be nice to go back and clean out the legacy references.
=> Support upgrade CronJob api version

docs/community.md
Remove Calendly from Clutch.sh
Calendly option removed from _Community_ page on Clutch.sh
Before:
After:
* Click on _Community_ option on the top left header
* Confirm that the "_Schedule time during our office hours with Calendly_" option is no longer visible
=> docs: Remove calendly from community

frontend/packages/core/src/dialog.tsx, frontend/packages/core/src/icon.tsx, frontend/packages/core/src/popper.tsx, frontend/packages/core/src/text.tsx, frontend/workflows/envoy/src/remote-triage/clusters.tsx, frontend/workflows/envoy/src/remote-triage/index.tsx
This PR updates the following components to use the current theme colors, additionally, updates matching colors across the whole app to mantain consistency. 
_before/after screenshots_
_Note_
This PR mainly aims to update ungrouped components within frontend/packages/core/src/, while updating all instances of widespread colors as to avoid possible mismatches from working them on a directory basis. Odd instances of hardcoded colors elsewhere will be addressed in future PRs.
manual, unit testing
=> frontend: leverage theme palette for misc components

frontend/packages/core/src/AppLayout/drawer.tsx, frontend/packages/core/src/AppProvider/themes.tsx, frontend/packages/core/src/Theme/colors.tsx, frontend/packages/core/src/Theme/palette.tsx, frontend/packages/core/src/Theme/theme.tsx, frontend/packages/core/src/Theme/types.tsx, frontend/packages/core/src/landing.tsx, frontend/packages/core/src/not-found.tsx, frontend/workflows/projectSelector/src/project-links.tsx
This PR adds a brand color that matches the color used in the Clutch logo, and updates the Not Found component to use this color from the current theme. 
Replaced string theme variation values (light, dark) with a shared variable.
Fixed a miss-written theme usage in the project links component.
No noticeable change was made:
before/after
manual, unit testing
=> fontend: leverage theme palette for misc components

tools/scaffolding/templates/frontend/package.json
- fixes #2874 
- Was found that when running the scaffold build that there was a node version issue, this was due to the peer-dependency of react-hook-form being installed by `@hookform/resolvers` in core. The version being installed was requiring a node version of 18 while the package.json engine requires 16.
manual
=> frontend: Adjusting resolution of react-hook-form

frontend/packages/core/src/tab.tsx
Active state of the tab component was the same as the hover state, now is darker.
=> frontend: Updating bg color on tab component for active state

frontend/workflows/projectCatalog/src/catalog/project-card.tsx
Project card close button was hite hich didn't make much contrast with the background so it was changed to black.
Before:
After:
=> frontend: fix component theming issues

frontend/packages/core/src/AppProvider/themes.tsx, frontend/packages/core/src/Feedback/error/details.tsx, frontend/packages/core/src/Input/select.tsx, frontend/packages/core/src/Theme/theme.tsx, frontend/packages/core/src/tests/__snapshots__/landing.test.tsx.snap
Palette usage instances were pointing to the secondary palette instead of the error one.
before:
after:
before:
after:
Also noticed there are some redundant usages of style providers around the app, so removed those.
manual, unit tests
=> frontend: point to error palette

frontend/packages/core/src/quick-links.tsx
Prevent malformed link groups to show up in QuickLinksCard component by filtering out the invalid ones.
Manual
N/A
=> frontend: Filter out invalid link groups

backend/module/proxy/proxy.go
PR updates the proxy module stats to include the request path. This is helpful when a `service` has several `allowed requests` and you want to know which paths returned a success/error response.
manual
Fixes #
=> proxy module: update stats

frontend/packages/core/src/tab.tsx
Readability of tabs when hovered was reduced with the updated shade, this pr adjusts it by making the using a lighter color shade for the background.
before:
after:
manual, unit tests
=> frontend: adjust tab hover color

frontend/packages/core/src/Charts/pie.tsx
Updates the default colors used in the Pie chart to reference the design guide.
manual
=> frontend: Updating Default Chart Colors based on guide

docs/development/feature.md, examples/amiibo/frontend/workflows/amiibo/package.json, frontend/lerna.json, frontend/packages/app/package.json, frontend/packages/core/package.json, frontend/packages/data-layout/package.json, frontend/packages/wizard/package.json, frontend/workflows/audit/package.json, frontend/workflows/dynamodb/package.json, frontend/workflows/ec2/package.json, frontend/workflows/envoy/package.json, frontend/workflows/experimentation/package.json, frontend/workflows/k8s/package.json, frontend/workflows/kinesis/package.json, frontend/workflows/projectCatalog/package.json, frontend/workflows/projectSelector/package.json, frontend/workflows/redisexperimentation/package.json, frontend/workflows/serverexperimentation/package.json, frontend/workflows/sourcecontrol/package.json, tools/scaffolding/templates/frontend/package.json, tools/scaffolding/templates/gateway/frontend/package.json, tools/scaffolding/templates/gateway/frontend/workflows/echo/package.json
Given the update from https://github.com/lyft/clutch/pull/2851 and since it is a major update to clutch, this PR updates the current version of clutch-sh/core (2.0.0-beta) to 3.0.0-beta to better represent the changes.
Additionally updates the dependency versions in packages within the current repo.
manual
=> frontend: bump clutch core version

frontend/workflows/dynamodb/package.json, frontend/workflows/projectCatalog/package.json, frontend/workflows/projectSelector/package.json, frontend/workflows/redisexperimentation/package.json, frontend/workflows/serverexperimentation/package.json
- Doesn't really make any sense for these workflows to hold the `private: true` variable when they're all part of an OSS repository. Removing them to fix issues found with versioning.
- Also adding the `publishBeta` script where it was missing, to allow for successful publishing.
=> frontend: Removing private variable on OSS workflows and add publishBeta script

frontend/packages/core/src/paper.tsx, frontend/packages/wizard/src/wizard.tsx, frontend/workflows/ec2/src/tests/__snapshots__/reboot-instance.test.tsx.snap, frontend/workflows/ec2/src/tests/__snapshots__/resize-asg.test.tsx.snap, frontend/workflows/ec2/src/tests/__snapshots__/terminate-instance.test.tsx.snap, frontend/workflows/envoy/src/tests/__snapshots__/remote-triage.test.tsx.snap, frontend/workflows/k8s/src/tests/__snapshots__/delete-pod.test.tsx.snap, frontend/workflows/k8s/src/tests/__snapshots__/resize-hpa.test.tsx.snap, frontend/workflows/k8s/src/tests/__snapshots__/scale-resources.test.tsx.snap
Was having issues styling the wizard and realized something I had previously missed in the documentation. Namely https://emotion.sh/docs/styled#styling-any-component `styled can style any component as long as it accepts a className prop.`. Adding this in alleviates the issues with styling the Container for the Wizard.
At the same time, the MuiContainer was ignoring the `maxWidth: unset` so I did some digging and it seems it must be done via the `maxWidth={false}`. So adding that in so it correctly unsets the width versus just ignoring it entirely.
manual
=> frontend: Adjusting Wizard to allow for styling

frontend/packages/core/src/stepper.tsx, frontend/workflows/ec2/src/tests/__snapshots__/reboot-instance.test.tsx.snap, frontend/workflows/ec2/src/tests/__snapshots__/resize-asg.test.tsx.snap, frontend/workflows/ec2/src/tests/__snapshots__/terminate-instance.test.tsx.snap, frontend/workflows/envoy/src/tests/__snapshots__/remote-triage.test.tsx.snap, frontend/workflows/k8s/src/tests/__snapshots__/delete-pod.test.tsx.snap, frontend/workflows/k8s/src/tests/__snapshots__/resize-hpa.test.tsx.snap, frontend/workflows/k8s/src/tests/__snapshots__/scale-resources.test.tsx.snap
Active and Completed steps were missed in previous iterations of vertical stepper integration. This caused some weird CSS, so adjusting that now.
manual
=> frontend: Adjusting Colors for Vertical Stepper Active/Completion

frontend/packages/core/src/quick-links.tsx, frontend/packages/core/src/stories/quick-links.stories.tsx
This PR adds updates to the QuickLinks component:
- Reduce padding for dropdown elements
before:
after:
- Prepend an icon if passed in the `link` object
manual
=> frontend: add support for icons in quick links

frontend/packages/core/src/Input/select.tsx, frontend/packages/core/src/Input/tests/select.test.tsx
Scope: Adding a noDefault flag to the Select component to avoid triggering the onChange method on component did update for when we don't want the first option in the list to be set as default.
=> frontend: Add noDefault flag to Select component

frontend/packages/core/src/quick-links.tsx, frontend/packages/core/src/stories/quick-links.stories.tsx
Badges in the QuickLinks component use the standard variant  which looks too big without text in it.
This PR conditionally renders either a `dot` variant if there is no badge content or the `standard` one if there is.
before:
after:
manual
=> frontend: use dot badge if no content

frontend/packages/core/src/AppLayout/user.tsx, frontend/packages/wizard/src/wizard.tsx
- Fixes an issue where long user names would break out of container
- Extends properties of the Wizard component to allow for showing/hiding the NPS feedback, the start over button and copy text and saving the search params on back
manual
=> frontend: Extending Wizard props and fixing issue with user info not breaking

frontend/package.json, frontend/workflows/projectCatalog/src/details/info/chipsRow.tsx
Currently all chips with a URL were being treated as external, adjusted this logic and allowed it to be customized.
manual
=> frontend: Adjusting ProjectCatalog chipsRow to allow a target and auto-set based on location

frontend/packages/core/src/quick-links.tsx
Console log was throwing errors about missing a key for the wrapper, adjusting this.
manual
=> frontend: Adjusting QuickLinks wrapper to utilize a key to stop errors

frontend/packages/core/src/AppProvider/registrar.tsx
Found that if a user were to directly navigate to a route that is gated by a feature flag, there was a race condition on the first load. This was due to the loadWorkflows function expecting a promise but everything was just synchronous so it wasn't waiting correctly. This returns a promise and waits appropriately.
manual
=> frontend: Fixing feature flags and workflow routes

frontend/packages/core/src/Feedback/tooltip.tsx, frontend/packages/core/src/quick-links.tsx
- There was some overlap when hovering over a quick link which had a sub-group with a popper where the tooltip would not go away. Switched the tooltip to be controlled and will manually hide it when the popper is open. Doesn't affect the handling for normal quick links
- Also added a maxLinks prop to the QuickLinks handler so we're not limited to 5 showing and its customizable
manual
=> frontend: Quick Links - Adjusting tooltip handling and max number of links allowed

frontend/packages/core/src/index.tsx, frontend/packages/core/src/quick-links.tsx, frontend/workflows/projectCatalog/src/catalog/index.tsx, frontend/workflows/projectCatalog/src/catalog/storage.tsx, frontend/workflows/projectCatalog/src/config/index.tsx, frontend/workflows/projectCatalog/src/details/helpers.tsx, frontend/workflows/projectCatalog/src/details/index.tsx, frontend/workflows/projectCatalog/src/details/info/messengerRow.tsx, frontend/workflows/projectCatalog/src/index.tsx
- Adjusts the projectCatalog to accept an additional componentProp in its configuration of `allowDisabled`. This will be propagated to the API requests and allow the system to accept and return disabled projects so that they can be navigated to.
- Modifies the settings button to accept additional links and renders a popper to show them
- Adjusts the breadcrumbs to reference the project now
manual
=> frontend: Project Catalog - Allowing disabled projects to be found and returned

.github/workflows/frontend.yml, tools/scaffolding/templates/gateway/frontend/.yarnrc.yml
Previous fix didn't address issue. 
- Scaffolding is currently broken due to publish not having taken effect yet so it can't install the packages. Tested everything else locally and seems to be working correctly. Did add the `.yarnrc.yml` over to keep similar configuration settings as the base repo.
- Publishing is done slightly different than Yarn v1 so adjusting as we go since it wasn't easy to test this beforehand.
manual
=> housekeeping: Attempting to fix publishing and scaffolding

tools/scaffolding/templates/gateway/Makefile
Yarn will fail `yarn install` if it would update/create a lock file in CI. Adjusting to pass no-immutable for the makefile, which makes sense if there isn't a lock file already anyhow.
=> housekeeping: Adding no-immutable flag for scaffolding since it's failing in CI

frontend/packages/core/src/Input/date-time.tsx, frontend/packages/core/src/Input/tests/date-time.test.tsx
Scope: Update onChange trigger validation to allow trigger when the value of the DateTimePicker is empty
=> DateTimePicker - trigger onChange method when value is empty

frontend/packages/core/src/Input/checkbox.tsx
When adding an indeterminate state to the checkbox, it would default to the MUI styles which looked off. Now the indeterminate state looks in line with the rest of the states.
Also, the combination of disabled + checked shows the checkmark in white, this is especially useful to indicate that either the selected item was successfully affected by a user-driven action, or that an item was successfully preselected from a form.
I tested the component by using it in an internal UI.
=> component: Add indeterminate state icon and show checkmark for the combination of disabled + checked

backend/go.mod, backend/go.sum, backend/mock/service/awsmock/awsmock.go, backend/service/aws/aws.go, backend/service/aws/iface.go, backend/service/aws/s3control.go, backend/service/aws/s3control_test.go
This PR adds functionality for calling S3GetAccessPointPolicy to support [clutch-private#2500](https://github.com/lyft/clutch-private/pull/2500)
=> DS-10153: Add Functionality to aws client for calling S3GetAccessPointPolicy

backend/mock/service/githubmock/githubmock.go, backend/service/github/github.go, backend/service/github/github_test.go, backend/service/github/graphql.go
Currently the GitHub client has the ability to get a file at a specific path but if we need to fetch the contents of a directory we were out of luck, this addresses that and allows us to navigate around based on paths.
```
HTTP/1.1 200 OK
Content-Type: application/json
Grpc-Metadata-Content-Type: application/grpc
Grpc-Metadata-Trailer: Grpc-Status
Grpc-Metadata-Trailer: Grpc-Message
Grpc-Metadata-Trailer: Grpc-Status-Details-Bin
Date: Wed, 15 May 2024 20:11:29 GMT
Content-Length: 653
{
"path": "frontend",
"lastModifiedTime": "2024-05-15 18:34:45 +0000 UTC",
"lastModifiedSha": "3bc4eb7da42ee2adc089bc9db2441233503b9c9e",
"entries": [
{ "name": ".gitignore", "type": "blob" },
{ "name": ".nvmrc", "type": "blob" },
{ "name": ".storybook", "type": "tree" },
{ "name": ".yarnrc.yml", "type": …
```
=> backend: Extending GitHub service to have the ability to get files based on a path

backend/mock/service/awsmock/awsmock.go, backend/service/aws/aws.go, backend/service/aws/iam.go, backend/service/aws/iam_test.go, backend/service/aws/iface.go, backend/service/aws/s3.go, backend/service/aws/s3_test.go, backend/service/aws/s3control.go, backend/service/aws/s3control_test.go
This PR adds functionality for calling S3DescribeBucket, and S3GetAccessPoint to support topology cache for Buckets, and Access Points.
It also updates s3 client interface to include ListBuckets, ListAccessPoints and ListRoles.
=> aws: Add S3DescribeBucket, and S3GetAccessPoint

backend/resolver/aws/aws.go, backend/resolver/aws/iam.go, backend/resolver/aws/s3.go, backend/service/aws/cache.go
This CR add topology cache for the following aws resources
- S3 Bucket 
- S3 Access Point
- IAM Role
This cache is implemented to support autocomplete of aws resources for s3 access workflow
Backend changes
https://github.com/lyft/clutch/pull/3023
Proto changes
https://github.com/lyft/clutch/pull/3022
=> aws: topology cache for aws s3 and iam resources

backend/service/aws/cache.go
This PRs handles Moved Permanently error while calling HEAD Bucket
- List Buckets API returns all buckets in an account regardless of region client used for request. However, the subsequent Head bucket request works for buckets in the same account and returns 301 Moved Permanently error for buckets in different regions.
- This PR ensures we are not logging an error when bucket is in a different region. 
Tested changes locally
=> aws: Handle Moved Permanently error while calling HEAD Bucket

.github/hooks/pre-commit, frontend/package.json, frontend/yarn.lock
Was noticed that when the pre-commit was run with a deleted file it would fail in the linting phase. Since it had been setup to fetch the names only it was unaware of which files were still present. Adding the filter option to filter out deleted files.
manual
=> housekeeping: Updating pre-commit to ignore deleted files

frontend/packages/core/src/Input/date-time.tsx
Typescript fix so that the date time picker from MUI has the correct typing for minDate and maxDate
=> frontend: date time picker range TypeScript fix

frontend/packages/core/src/AppLayout/search.tsx, frontend/packages/core/src/AppLayout/stories/searchfield.stories.tsx, frontend/packages/core/src/Input/stories/date-time.stories.tsx, frontend/packages/core/src/horizontal-rule.tsx, frontend/packages/core/src/stepper.tsx
**Search Icon Button:** in both light and dark mode the background where this component is used is dark, so there is no need to use the contrastColor value here:
**Horizontal Rule:** Opacity was too low:
**Stepper:** Inactive options opacity was too low:
=> frontend: Adjust current palette for accessibility / look for components where the switch between light/dark/else affects readability

frontend/packages/core/src/AppLayout/header.tsx, frontend/packages/core/src/AppLayout/theme-switcher.tsx, frontend/packages/core/src/AppProvider/index.tsx, frontend/packages/core/src/AppProvider/themes.tsx, frontend/packages/core/src/Contexts/preferences-context.tsx
Added theme option to user preferences:
=> frontend: Implement a theme switcher input to select from multiple themes

frontend/packages/core/src/Table/table.tsx
Props and components were added to the table component to enable sort behavior
https://github.com/lyft/clutch/assets/25833665/7090f92b-333c-4b7e-8877-f9f23c26b926
=> frontend: Add sort logic to table component

frontend/packages/core/src/Network/errors.ts, frontend/packages/core/src/Network/index.ts, frontend/packages/core/src/Network/tests/index.test.ts, frontend/packages/core/src/index.tsx
API calls done via the proxy API always return 200 unless there's a 5XX error. There's a `httpStatus` property that's returned inside the `data` property on Axios calls which contains the actual HTTP status.
The new `proxyClient` now will be able to handle those errors correctly.
Unit testing and tested on internal UI.
=> network: Create `proxyClient` to handle errors on API calls done via the proxy API

backend/internal/test/integration/chaos/do_integration_test.sh
The chaos integration test has been failing with `KeyError: 'ContainerConfig'`
Came across https://askubuntu.com/questions/1508129/docker-compose-giving-containerconfig-errors-after-update-today; tldr `docker-compose` is the V1 syntax which has been deprecated in V2. The V2 syntax is `docker compose`.
https://docs.docker.com/compose/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2
CI run
=> chaos integration test: update docker compose command

frontend/packages/core/src/Table/accordion-table.tsx, frontend/packages/core/src/Table/components/TableCell.tsx, frontend/packages/core/src/Table/components/TableHeader.tsx, frontend/packages/core/src/Table/index.tsx, frontend/packages/core/src/Table/stories/table.stories.tsx, frontend/packages/core/src/Table/table.tsx, frontend/packages/core/src/Table/types.tsx
Similar to sorting, the user can send attributes (_options?: JSX.Element_) in the columns list to the **Table** component to specify if they want to display options (e.g. filters) while also providing the _component_ that needs to be rendered.
An example could be something like the following:
**Filtering logic and UI is 100% responsibility of the father component, table header only renders the component provided**
=> frontend: Add options to the table header component

frontend/packages/core/src/Table/components/TableCell.tsx, frontend/packages/core/src/Table/stories/table.stories.tsx, frontend/packages/core/src/Table/table.tsx, frontend/packages/core/src/Table/types.tsx, frontend/packages/core/src/utils/getDisplayName.ts, frontend/packages/core/src/utils/index.ts
Scope: Add style prop to _TableRow_ so that styling can be dynamic for _TableCell_ components in body
Table with default column width
Table with set column width
=> frontend: Add style prop to table component

frontend/packages/wizard/src/wizard.tsx, frontend/workflows/ec2/src/tests/__snapshots__/reboot-instance.test.tsx.snap, frontend/workflows/ec2/src/tests/__snapshots__/resize-asg.test.tsx.snap, frontend/workflows/ec2/src/tests/__snapshots__/terminate-instance.test.tsx.snap, frontend/workflows/envoy/src/tests/__snapshots__/remote-triage.test.tsx.snap, frontend/workflows/k8s/src/tests/__snapshots__/delete-pod.test.tsx.snap, frontend/workflows/k8s/src/tests/__snapshots__/resize-hpa.test.tsx.snap, frontend/workflows/k8s/src/tests/__snapshots__/scale-resources.test.tsx.snap
- Match StepperContainer and StepContainer heights.
**Before**
**After**
Manual
=> frontend: fix step container height to match stepper container

backend/service/github/github.go, backend/service/github/github_test.go, backend/service/github/graphql.go
Minor adjustments:
- Updated `Entry` struct to have a SHA field
- Updated CreateBranch functionality to add files in worktree to the commit. Currently only existing files were being added when creating the commit
- Returning the SHA from GetCommit since if you search via a tag or a branch you would not have that information available
manual
=> backend: Updating Github Service

api/sourcegraph/v1/sourcegraph.proto, backend/api/sourcegraph/v1/sourcegraph.pb.go, backend/api/sourcegraph/v1/sourcegraph.pb.validate.go, backend/service/sourcegraph/sourcegraph.go, frontend/api/src/index.d.ts, frontend/api/src/index.js
- Add method to Sourcegraph service to get count from the results of a query
manual
=> backend: Add get query count to sourcegraph

frontend/packages/core/src/AppProvider/index.tsx, frontend/packages/core/src/AppProvider/workflow.tsx, frontend/packages/core/src/Breadcrumbs/index.tsx, frontend/packages/core/src/WorkflowLayout/index.tsx
- Modified spacing from Breadcrumbs and WorkflowLayout to provide better whitespace defaults
Manual
=> frontend: Adjust workflow layout whitespace

backend/service/k8s/pods.go
A k8s sidecar is an init container that starts before the main app container and **continues to run**. This is unlike a regular init container which always runs to completion before the app container starts.
**Reading**
* https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/753-sidecar-containers/README.md
* https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
* https://github.com/kubernetes/kubernetes/blob/66e34012255abf1bbd0956a712817dad77c69c41/pkg/printers/internalversion/printers.go#L905-L908
**PR changes**
we need to account for the difference between an init sidecar container and a regular init container.
* to identify which is an init sidecar container, we check for where restart policy is not nil and set to restartalways
* to identify if the init …
=> k8s: update pod status logic to support native sidecars

frontend/packages/core/src/Theme/theme.tsx, frontend/packages/core/src/WorkflowLayout/index.tsx, frontend/workflows/audit/src/logs/event-row.tsx, frontend/workflows/envoy/src/remote-triage/dashboard.tsx, frontend/workflows/envoy/src/remote-triage/server-info.tsx, frontend/workflows/k8s/src/k8s-dash-header.tsx, frontend/workflows/k8s/src/k8s-dash-search.tsx, frontend/workflows/k8s/src/k8s-dashboard.tsx, frontend/workflows/kinesis/src/update-shard-count.tsx, frontend/workflows/projectCatalog/src/catalog/index.tsx, frontend/workflows/projectCatalog/src/details/components/card.tsx, frontend/workflows/projectCatalog/src/details/components/link-settings.tsx, frontend/workflows/projectCatalog/src/details/info/index.tsx, frontend/workflows/projectSelector/src/project-group.tsx, frontend/workflows/projectSelector/src/project-links.tsx, frontend/workflows/projectSelector/src/project-selector.tsx
- Override `theme.spacing` to allow the new spacing units as strings
=> frontend: Refactor theme spacing to allow units as strings

frontend/packages/core/src/AppProvider/index.tsx, frontend/packages/core/src/AppProvider/workflow.tsx, frontend/packages/core/src/WorkflowLayout/index.tsx, frontend/packages/core/src/utils/generateBreadcrumbsEntries.tsx
- Sets current path breadcrumb entry as plain text
- Grabs better entry labels from workflow config
- Fixes issue with fragmented workflow groups where not all routes were present
Manual
=> frontend: Improve breadcrumbs UX

frontend/packages/core/src/AppProvider/index.tsx
-  Sets workflow layout title as either route or workflow display names
Manual
=> frontend: Set workflow layout title as either route or workflow display names

frontend/packages/core/src/AppProvider/index.tsx, frontend/packages/core/src/WorkflowLayout/context.tsx, frontend/packages/core/src/WorkflowLayout/index.tsx, frontend/packages/core/src/index.tsx, frontend/workflows/audit/src/index.tsx, frontend/workflows/audit/src/logs/index.tsx, frontend/workflows/projectCatalog/src/details/components/layout.tsx, frontend/workflows/projectCatalog/src/index.tsx, frontend/workflows/redisexperimentation/src/index.tsx
- Added a Context for the Workflow Layout component to support dynamic content
- Removed the breadcrumbsOnly prop
- Refactored workflows that previously had header content
Manual
=> frontend: Add context for workflow layout to support dynamic content

frontend/workflows/audit/src/logs/index.tsx, frontend/workflows/projectCatalog/src/details/components/layout.tsx
- Modified the dependencies list in useEffect to properly update the header content
- Fixed variable naming when using workflowLayoutContext
Manual
=> frontend: Fix issues with dependencies when updating workflow layout context

frontend/packages/core/src/AppLayout/index.tsx, frontend/packages/core/src/Network/tests/index.test.ts
Fullscreen workflows don't fully extend vertically. This PR leverages the existing flag to extend it to the ContentGrid component and conditionally set its height.
=> frontend: use fullscreen flag for layout height

backend/mock/service/githubmock/githubmock.go, backend/service/github/github.go, backend/service/github/helpers.go
- Created GetFileContents method in GitHub service
This method behaves similarly to `getFile` but is able to retry the request if the file is larger than 1MB. See [Get repository content](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content).
Manual and mocks
=> backend: Create GetFileContents method in GitHub service

backend/gateway/mux/mux.go
Updated the `ServeHTTP` function in the `assetHandler` to add caching headers for `.ico`, `.svg`, and `.webp` files, serving these files with a `Cache-Control` header set to cache for one day.
This change bypasses the authentication middleware for favicon and icon assets in the root directory. The bypass is limited to image assets in the root path to maintain security.
Key changes:
- Added early path check for image file extensions (.ico, .svg, .webp)
- Added security check to only serve files from root directory
- Set Cache-Control header to cache assets for 24 hours
- Serve files directly without going through auth middleware
=> frontend: bypass auth middleware for favicon and icon assets in root

frontend/workflows/k8s/src/cordon-node.tsx, frontend/workflows/k8s/src/delete-pod.tsx, frontend/workflows/k8s/src/resize-hpa.tsx
Delete Pod
Cordon/Uncordon node
Resize HPA
=> [frontend] Adding confirmation modal to destructive actions in k8s workflow
