docs/development/guide.md
examples/amiibo/README.md

Fix feature-development broken links.

docs: update some broken links

---

.github/dependabot.yml

Created a basic `dependabot.yml` configuration for frontend and backend code. #25 
After merging, dependabot should create a new PR rather quickly wanting to upgrade lodash.

Create dependabot.yml #25

---

docs/development/feature.md

Pass 3rd argument that's missing after the recent changes to gateway's API.

Pass 3rd argument

---

examples/amiibo/backend/main.go

Updating based on change included in #73

examples: update amiibo gateway parameters

---

tools/scaffolding/templates/gateway/frontend/workflows/echo/src/echo.jsx
tools/scaffolding/templates/gateway/frontend/workflows/echo/src/index.jsx

Fixing up the gateway echo workflow example.
Manual

scaffolding: update gateway echo workflow

---

frontend/packages/core/src/Input/checkbox.tsx
frontend/packages/data-layout/src/layout.tsx

Fix types in checkbox and data-layout to allow them to work together.

checkbox: fix types to persist checkbox values in data-layout

---

frontend/packages/core/src/Input/checkbox.tsx

Simplify the Checkbox interface. This includes:
- allowing consumers to specify the default state of options
- invoking a callback function with all the options in aggregate instead of individual. This simplifies the need of consumers to manage state of the values.

checkbox: simplify interface for input and callback

---

.github/workflows/scaffolding.yml
tools/scaffolding/scaffolder.go

Allows the scaffolding job to work on forks, and fix the PR flow.
CI.
Bug reported here: https://github.com/lyft/clutch/pull/137#issuecomment-665380667

ci: fix scaffolding job on forks

---

.github/CODEOWNERS
docs/community.md

Add documentation on maintaining Clutch and a CODEOWNERS file.

ci: add codeowners

---

frontend/package.json
frontend/yarn.lock

Remove npx wrapper until github.com/npm/npx/pull/70 lands.

ci: remove npx from package linting

---

.github/CODEOWNERS

Hopefully this allows us to enable round robin reviews.

housekeeping: use team for codeowners

---

.github/renovate.json
examples/kubernetes/README.md
examples/kubernetes/clutch.yaml

Kubernetes deployment example to get clutch up and running quickly with no additional configuration. At the very least all of the support kubernetes clutch operations should work.
Development this example locally on a k8s v1.16.6 cluster.
Fixes #
#145

example: kubernetes deployment

---

Makefile
tools/compile-protos.sh
tools/scaffolding/templates/gateway/api/echo/v1/echo.proto

Exercise imported APIs from core to be sure they work.
CI & local.

scaffolding: more fixes for API vendoring

---

frontend/packages/tools/package.json
frontend/yarn.lock

housekeeping: remove eslint flowtype package

---

docs/development/frontend.md

docs: fix typo in frontend development

---

backend/service/audit/sql.go

Might yield better error messages in the event of cancellation.
N/A (build)

audit: use context for database access

---

frontend/packages/core/package.json
frontend/packages/core/src/Resolver/hydrator.tsx
frontend/packages/core/src/Resolver/index.tsx
frontend/packages/core/src/Resolver/input.tsx
frontend/packages/core/src/Table/metadata-table.tsx
frontend/yarn.lock

Upgrade react-hook-form to [v6](https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md)

housekeeping: react-hook-form@6

---

frontend/packages/core/package.json
frontend/workflows/experimentation/package.json
frontend/yarn.lock
tools/scaffolding/templates/gateway/frontend/package.json

Upgrade react-router* to from alpha to beta

housekeeping: upgrade react-router & react-router-dom

---

frontend/package.json
frontend/yarn.lock

housekeeping: update lerna

---

frontend/package.json

Adds a convenience script to operate on core packages.
```bash
> yarn package core lint
yarn run v1.22.4
$ func() { yarn workspace @clutch-sh/"$@"; }; func core lint
$ eslint --ext .js,.jsx,.ts,.tsx .
✨  Done in 8.98s.
```

housekeeping: add package command for easy maintenance

---

frontend/api/src/index.d.ts
frontend/api/src/index.js
tools/compile-protos.sh

housekeeping: protoc to v3.12.4

---

.github/renovate.json

Whoops, misread the docs the first time around.
https://docs.renovatebot.com/configuration-options/#schedule
Read the docs.
Fixes #277

ci: fix renovate config

---

frontend/workflows/k8s/package.json
frontend/workflows/k8s/src/delete-pod.tsx
frontend/workflows/k8s/src/index.tsx
frontend/workflows/k8s/src/resize-hpa.tsx
frontend/workflows/k8s/tsconfig.json

Covert k8s workflows to typescript

k8s: convert to typescript

---

.github/workflows/api.yml

Since we pin deps for proto generation in backend, need to run API jobs to ensure no changes required as part of upgrade.
N/A

ci: run api jobs on changes to go modules

---

.gitignore
Makefile
backend/.air.toml
tools/air.sh

Introduce backend live reloading with [air](https://github.com/cosmtrek/air), simply `make backend-watch` to start developing.

tooling: live reload backend with air

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature_request.md

Automatic labeling is not working. Other repos use a list.
Not possible.

ci: try comma separated issue labels in template config

---

.github/workflows/scaffolding.yml
tools/scaffolding/templates/frontend/package.json

Fixes
```
./node_modules/jspdf/dist/jspdf.umd.min.js
Critical dependency: the request of a dependency is an expression
```
Root cause: https://github.com/mbrn/material-table/pull/2311
Local

scaffolding: pin material table to fix dep issue

---

frontend/packages/core/package.json
frontend/yarn.lock
tools/scaffolding/templates/frontend/package.json

Pin material-table for https://github.com/mbrn/material-table/issues/2326

core: fix dependency pin of material-table

---

backend/gateway/mux/mux.go
frontend/packages/core/src/network.ts

Revert "auth: reload client on authentication errors"

---

frontend/packages/core/src/button.tsx
frontend/packages/core/src/index.tsx

This change adds a clipboard button component.
When clicked a clipboard button will copy text to the clipboard and briefly change its icon to a checkbox to provide feedback to the user.
Manual testing on a private workflow.

frontend: add ClipboardButton component

---

examples/amiibo/frontend/workflows/amiibo/src/hello-world.tsx

The [Feature Development tutorial](https://clutch.sh/docs/development/feature) code for `hello-world.tsx` and the [completed example](https://github.com/lyft/clutch/blob/main/examples/amiibo/frontend/workflows/amiibo/src/hello-world.tsx) have some import differences.
Using the [completed example](https://github.com/lyft/clutch/blob/main/examples/amiibo/frontend/workflows/amiibo/src/hello-world.tsx) will result in import errors.
I went through the Feature Development tutorial, and the code snippet for `hello-world.tsx` successfully renders the Amiibo components.
I copied the [completed example](https://github.com/lyft/clutch/blob/main/examples/amiibo/frontend/workflows/amiibo/src/hello-world.tsx) and got import errors when using `@clutch/` vs `@clutch-sh/`.
Additionally, the [completed …

[clutch/examples] Update/remove imports in hello-world file

---

frontend/packages/core/package.json
frontend/packages/core/src/AppLayout/drawer.tsx
frontend/packages/core/src/AppLayout/search.tsx
frontend/packages/core/src/Table/tree-table.tsx
frontend/packages/core/src/error.tsx
frontend/packages/core/src/panel.tsx
frontend/packages/core/src/tests/__snapshots__/not-found.test.tsx.snap
frontend/packages/tools/jest.setup.js
frontend/packages/wizard/package.json
frontend/workflows/ec2/package.json
frontend/workflows/envoy/package.json
frontend/workflows/experimentation/package.json
frontend/workflows/kinesis/package.json
frontend/workflows/sourcecontrol/package.json
frontend/yarn.lock
tools/scaffolding/templates/gateway/frontend/workflows/echo/package.json

Upgrade @material-ui/core to 4.11.0 for new components (Accordion)

housekeeping: upgrade @material-ui/core

---

tools/frontend-gateway-linker.sh

This line was accidentally removed as part of https://github.com/lyft/clutch/pull/429.

tools: fix frontend linker script

---

frontend/packages/tools/.eslintrc.js

Include nested config files in `import/no-extraneous-dependencies` dev dependencies.
manual

tools: update eslint rules

---

frontend/packages/core/src/Input/select.tsx

select: enforce margin on top and bottom

---

frontend/packages/core/src/Table/metadata-table.tsx

Fixed UX issues:
- proper alignment of text field with other cells
- ensure that key cells don't resize when value cells need to grow (during error handling)
Added support for return key submission from editable row.
manual
Fixes #
#364

metadata table: editable field UX fixes and return key support

---

frontend/workflows/experimentation/src/list-experiments.tsx

Do not attempt to fetch experiments if:
* getExperiments call failed
* getExperiments called returned 0 experiments
Verified locally that the list of experiments works if GetExperiments returns no experiments or more than 0 experiments.

experimentation: fix get experiments being called infinite number of times

---

frontend/packages/core/src/Input/text-field.tsx
frontend/packages/core/src/Resolver/input.tsx

Add placeholders to resolver fields
Manual
Fixes #456

resolver: display placeholders

---

backend/gateway/core.go
backend/service/topology/topology.go
backend/service/topology/topology_test.go

Simple service scaffolding for the topology service.
unit
Scaffolding for the topology API, progress is being track here #30.

core: topology scaffolding

---

frontend/packages/core/src/Table/metadata-table.tsx

The current code would unintentionally attempt to convert React components to strings.
manual

metadata table: fix component rendering

---

docs/_website/package.json
docs/_website/yarn.lock

housekeeping: update @docusaurus packages to 2.0.0-alpha.65

---

frontend/workflows/experimentation/src/index.tsx

Following the convention established by other routes capitalize all words in the title of the route.
N/A

experimentation: capitalize word in a title

---

frontend/netlify.toml

Add custom netlify config for storybook builds.
This should only build storybook when there are changes to relevant files. If I'm reading the docs correctly this command will execute from the base directory set in our configuration. **Note**: this will also change the behavior on master to only build production when changes are detected. This is intentional as we do not need to rebuild production every time.
Additionally this adds a few headers to prevent iframing and xss attacks.
I will open a similar PR to the docs netlify configuration for optimizing that build as it currently runs even when there aren't any changes.

ci: add netlify config for storybook

---

backend/service/chaos/experimentation/experimentstore/expriment_run_details.go

Correctly handle a case when a given date - end time in the example below - is equal to null. For cases like this, display `unknown` instead of defaulting to 0 epoch time.
| ----- | ----- |
|<img width="643" alt="Screen Shot 2020-10-07 at 7 27 20 PM" src="https://user-images.githubusercontent.com/4410346/95408067-89ec0480-08d3-11eb-9303-9820bf321d43.png">|<img width="573" alt="Screen Shot 2020-10-07 at 7 28 48 PM" src="https://user-images.githubusercontent.com/4410346/95408074-8d7f8b80-08d3-11eb-824d-5ceef6e476f4.png">|
See screenshots above

experimentation: fix handling of null date case

---

frontend/packages/core/src/link.tsx
frontend/packages/core/src/stories/link.stories.tsx

Add a Link component with default styling and proper relationship attributes.
manual via story

frontend: add link component

---

frontend/packages/core/src/Feedback/stories/hint.stories.tsx

storybook: add hint story

---

frontend/packages/core/src/AppLayout/search.tsx
frontend/packages/core/src/tests/__snapshots__/not-found.test.tsx.snap
frontend/yarn.lock

Update Clutch frontend dependencies.
This fixes a vulnerability in:
- minimist < 0.2.1
- object-path
- node-forge < 0.10.0
manually tested that the app can build and load.

housekeeping: update indirect dependencies

---

backend/service/topology/cache.go

When addressing previous feedback on ticker usage in https://github.com/lyft/clutch/pull/556#discussion_r508556187 and https://github.com/lyft/clutch/pull/564#discussion_r508568545, I wanted to come back and also refactor this last ticker to address the issues raised in the other comments.
Unit / local.

topology: refactor cache ticker

---

frontend/packages/core/.eslintrc.js
frontend/packages/core/src/button.tsx
frontend/packages/core/src/stories/button-group.stories.tsx
frontend/packages/core/src/stories/buttongroup.stories.tsx

PR adds the ButtonGroup story
Locally

storybook: add ButtonGroup

---

frontend/packages/core/src/not-found.tsx
frontend/packages/core/src/stories/not-found.stories.tsx
frontend/packages/core/src/tests/__snapshots__/not-found.test.tsx.snap

Add story for NotFound component and update styles.
Manual with story and dev build for not found page in app.

storybook: add NotFound story

---

backend/service/audit/setup.go

Records the sink name when an error occurs writing to the sink.

audit: record sink name and event with error

---

frontend/packages/app/src/clutch.config.js
frontend/workflows/ec2/src/index.tsx
frontend/workflows/ec2/src/reboot-instance.tsx

Workflow to reboot ec2 instances.
Local /  against real aws instance.
Whiled ssh'ed into this instance I reboot from clutch, observe the disconnected session as the reboot request went through.
```
➜ ~ ssh i-00000000000
[mcutalo@ip-00-00-00-00 ~]$ uptime
22:31:58 up  3:22,  1 user,  load average: 0.36, 0.37, 0.33
[mcutalo@ip-00-00-00-00 ~]$ Connection to i-00000000000 closed by remote host.
Connection to i-00000000000 closed.
```

aws: reboot ec2 instance workflow

---

frontend/packages/core/src/Feedback/stories/warning.stories.tsx
frontend/packages/core/src/stories/error.stories.tsx

These are no longer needed now that #607 has landed.

frontend: remove unused eslint comments from stories

---

backend/module/chaos/serverexperimentation/rtds/rtds.go
backend/module/chaos/serverexperimentation/rtds/rtds_test.go

This scopes the RTDS stats to the xDS version used in order to make it
easier to monitor the individual resources. Also adds a stat for errors
received from xDS clients.
An integration test is added to verify that we're emitting the
appropriate stats for V2 and V3. This test also serves to verify that
we're properly exposing the two protocols.

rtds: scope stats to xds version

---

frontend/packages/core/src/stories/confirmation.stories.tsx

PR adds the Confirmation story.
Locally

storybook: add confirmation story

---

frontend/packages/core/src/button.tsx
frontend/packages/core/src/stories/button-group.stories.tsx
frontend/packages/core/src/stories/button.stories.tsx
frontend/packages/core/src/stories/clipboard-button.stories.tsx

PR adds the ClipboardButton story.
Locally

storybook: add ClipboardButton story

---

frontend/packages/core/src/AppProvider/themes.tsx

Disables the ripple animation seen below
https://material-ui.com/getting-started/faq/#how-can-i-disable-the-ripple-effect-globally

ui v2: disable ripple effect

---

frontend/.storybook/preview-head.html
frontend/packages/app/public/index.html
tools/scaffolding/templates/gateway/frontend/public/index.html

Adds Roboto to HTML for the main application and storybook.
Uses `<link>` directives from https://fonts.google.com/specimen/Roboto?query=roboto&sidebar.open=true&selection.family=Roboto:wght@300;400;500;700

ui v2: add roboto font

---

frontend/packages/core/src/card.tsx
frontend/packages/core/src/landing.tsx
frontend/packages/core/src/stories/card.stories.tsx
frontend/packages/core/src/stories/landing.stories.tsx
frontend/packages/core/src/tests/__snapshots__/landing.test.tsx.snap
frontend/packages/core/src/tests/landing.test.tsx
frontend/packages/tools/package.json
frontend/yarn.lock

Add Landing & Card stories.
manual with stories

storybook: add landing and card stories

---

frontend/workflows/experimentation/src/list-view.tsx
frontend/workflows/experimentation/src/tests/__snapshots__/list-experiments.test.tsx.snap
frontend/workflows/experimentation/src/tests/__snapshots__/view-experiment-run.test.tsx.snap
frontend/workflows/experimentation/src/tests/list-experiments.test.tsx
frontend/workflows/experimentation/src/tests/view-experiment-run.test.tsx
frontend/workflows/serverexperimentation/src/tests/__snapshots__/start-experiment.test.tsx.snap
frontend/workflows/serverexperimentation/src/tests/start-experiment.test.tsx

Add basic tests to frontend components.
N/A

experimentation: add tests to frontend components

---

frontend/api/package.json
frontend/packages/app/package.json
frontend/packages/core/package.json
frontend/packages/core/src/AppProvider/themes.tsx
frontend/packages/data-layout/package.json
frontend/packages/wizard/package.json
frontend/workflows/ec2/package.json
frontend/workflows/envoy/package.json
frontend/workflows/experimentation/package.json
frontend/workflows/k8s/package.json
frontend/workflows/kinesis/package.json
frontend/workflows/serverexperimentation/package.json
frontend/workflows/sourcecontrol/package.json
frontend/yarn.lock
tools/scaffolding/templates/frontend/package.json
tools/scaffolding/templates/gateway/frontend/package.json
tools/scaffolding/templates/gateway/frontend/workflows/echo/package.json

UI V2: consume new packages

---

frontend/packages/core/src/Input/stories/text-field.stories.tsx
frontend/packages/core/src/Input/text-field.tsx
frontend/packages/core/src/Resolver/hydrator.tsx
frontend/packages/core/src/Resolver/input.tsx
frontend/packages/core/src/Table/metadata-table.tsx
frontend/packages/core/src/index.tsx

Fix lint against UI V2
manually ran lint

ui v2: fix lint

---

frontend/packages/core/package.json
frontend/packages/core/src/AppLayout/header.tsx
frontend/packages/core/src/AppLayout/search.tsx
frontend/packages/core/src/AppLayout/stories/searchfield.stories.tsx

Adds the new search bar design for the header and a SearchField story
(does not reflect recent commits, will add a new gif in a bit)
Ran `make frontend-lint` and `make frontend-test` - no errors

UIV2: header search bar

---

frontend/packages/core/src/Input/select.tsx

Style the popover with the dropdown menu.
Storybook.

ui v2: select menu styles

---

frontend/packages/core/src/AppLayout/search.tsx

Fix lint errors on UIV2 master

---

frontend/packages/app/src/index.css
frontend/packages/core/src/card.tsx
frontend/packages/core/src/landing.tsx
frontend/packages/core/src/stories/card.stories.tsx
frontend/packages/core/src/stories/landing-card.stories.tsx

Implement landing page cards.
Storybook.

ui v2: card & landing card

---

examples/postgres-config/clutch-config.yaml

Looked like a bad merge, cleaning up.

examples: cleanup

---

backend/gateway/core.go
backend/mock/gateway.go
backend/mock/service/topologymock/topologymock.go
backend/module/topology/topology.go
backend/module/topology/topology_test.go
backend/service/topology/topology.go

Basic boilerplate module code with stubs for existing API's defied by the topology service.
Unit / Mock / Local.

topology: module setup

---

frontend/packages/app/src/clutch.config.js
frontend/packages/core/src/Feedback/note.tsx
frontend/packages/core/src/Resolver/input.tsx
frontend/packages/core/src/accordion.tsx
frontend/packages/wizard/src/step.tsx
frontend/workflows/k8s/src/delete-pod.tsx
frontend/workflows/kinesis/package.json
frontend/workflows/kinesis/src/update-shard-count.tsx

Restyle Kinesis workflow
Some of the CSS and styling are in the workflow itself. It would be great to extract these out at a future point.
Manual

ui v2: restyle kinesis workflow

---

frontend/packages/core/src/paper.tsx
frontend/packages/core/src/stories/paper.stories.tsx

Add paper component.
Storybook

 ui v2: paper component

---

frontend/packages/core/src/stepper.tsx

Fix background color of stepper
**current**
**after PR**
manual

ui v2: transparent stepper background

---

frontend/packages/core/src/dialog.tsx

Fix dialog open state based on prop changes.
manually

ui v2: update dialog open state on prop change

---

frontend/packages/core/src/Table/expandable-table.tsx
frontend/packages/core/src/Table/index.tsx
frontend/packages/core/src/index.tsx
frontend/workflows/envoy/src/listeners.tsx

Fixing some exports and interface change updates.
Built and ran lint locally

ui v2: fix lint and build

---

frontend/packages/app/src/index.css

Currently the height is fixed based on initial content render. This change sets a min height for the background but allows it to grow with the content if needed.
manual

ui v2: fix app background height

---

frontend/packages/core/src/AppProvider/themes.tsx
frontend/packages/core/src/index.tsx
frontend/packages/core/src/link.tsx
frontend/packages/core/src/stories/link.stories.tsx
frontend/workflows/experimentation/src/view-experiment-run.tsx

Restyle Link component.
⚠️  we don't have designs for this yet but I went off the general color scheme and font
storybook

ui v2: restyle link

---

frontend/packages/core/src/Input/form.tsx
frontend/packages/core/src/Input/stories/form.stories.tsx
frontend/packages/core/src/index.tsx

ui v2: form component

---

frontend/workflows/experimentation/package.json
frontend/workflows/experimentation/src/core/page-layout.tsx
frontend/workflows/experimentation/src/list-experiments.tsx
frontend/workflows/experimentation/src/tests/__snapshots__/list-experiments.test.tsx.snap
frontend/workflows/experimentation/src/tests/__snapshots__/view-experiment-run.test.tsx.snap
frontend/workflows/experimentation/src/view-experiment-run.tsx
frontend/workflows/serverexperimentation/package.json
frontend/workflows/serverexperimentation/src/form-fields.tsx
frontend/workflows/serverexperimentation/src/start-experiment.tsx
frontend/workflows/serverexperimentation/src/tests/__snapshots__/start-experiment.test.tsx.snap

Restyle experimentation workflows
manual

ui v2: update experimentation workflows

---

frontend/packages/core/src/AppLayout/tests/__snapshots__/layout.test.tsx.snap
frontend/workflows/ec2/src/tests/__snapshots__/resize-asg.test.tsx.snap
frontend/workflows/ec2/src/tests/__snapshots__/terminate-instance.test.tsx.snap
frontend/workflows/envoy/src/tests/__snapshots__/remote-triage.test.tsx.snap
frontend/workflows/k8s/src/tests/__snapshots__/resize-hpa.test.tsx.snap

update snapshots for component changes
manual

ui v2: update snapshots

---

frontend/packages/core/src/Feedback/stories/note-panel.stories.tsx

Fix import of Link in note panel story
manual

ui v2: fix Link import in story

---

frontend/packages/core/src/Feedback/alert.tsx
frontend/packages/core/src/Feedback/stories/alert.stories.tsx

Add alert component.
Once this lands we can remove/update the notes and error components.

ui v2: add alert component

---

frontend/packages/app/cypress/integration/navigation_spec.js

Fix e2e tests based on drawer changes
manually ran

ui v2: fix e2e tests

---

frontend/packages/core/src/loading.tsx

Minimal update to loading component for color and width.
We can revisit this in the future since we don't have finalized designs for loading states.
manual

ui v2: restyle loading component

---

frontend/packages/core/src/AppProvider/themes.tsx
frontend/packages/core/src/accordion.tsx
frontend/packages/wizard/src/step.tsx

Minor accordion fixes so they behave nicely in the `<Step>`.
Local

ui v2: accordion fixes

---

frontend/workflows/ec2/src/resize-asg.tsx
frontend/workflows/ec2/src/terminate-instance.tsx
frontend/workflows/k8s/src/delete-pod.tsx
frontend/workflows/k8s/src/resize-hpa.tsx

Add titles to the metadata tables for ec2 and k8s workflows.
manual

ui v2: add titles to workflows details tables

---

docs/about/lyft-case-study.md

Fixed a typo in the doc.
Fixes #

docs: fix typo in lyft case study

---

frontend/workflows/ec2/src/tests/__snapshots__/resize-asg.test.tsx.snap
frontend/workflows/ec2/src/tests/__snapshots__/terminate-instance.test.tsx.snap
frontend/workflows/k8s/src/tests/__snapshots__/delete-pod.test.tsx.snap
frontend/workflows/k8s/src/tests/__snapshots__/resize-hpa.test.tsx.snap

ui v2: fix unit tests

---

tools/scaffolding/templates/gateway/frontend/src/index.css

update css for gateway scaffolding
manual

ui v2: update css in gateway scaffolding

---

tools/frontend-gateway-linker.sh

Add `@emotion` packages to frontend linker script
manual

ui v2: link emotion packages

---

frontend/packages/core/src/Feedback/error.tsx

uiv2: add margin bottom to compressed error

---

frontend/packages/app/src/clutch.config.js

Remove kinesis from clutch config. Accidentally added as part of redesign to test changes.
manual

frontend: remove kinesis from config

---

frontend/packages/core/package.json
frontend/yarn.lock

housekeeping: update axios to 0.21.1

---

.github/workflows/api.yml
.github/workflows/ci.yml
.github/workflows/frontend.yml
.github/workflows/scaffolding.yml

Upgraded `actions/setup-node@v2-beta` to `actions/setup-node@v2`.
The stable version of `v2` has been released: https://github.com/actions/setup-node/releases/tag/v2.1.4 (`v2.1.4` is currently corresponding to `v2`)
Fixes #

ci: upgrade actions/setup-node v2-beta -> v2

---

.github/workflows/images.yml

Utilize https://github.com/marketplace/actions/image-actions to automatically optimize images on PRs.

ci: automatically compress all images on PRs

---

.github/workflows/scaffolding.yml
tools/scaffolding/templates/gateway/frontend/package.json

Failing on main with
```
The react-scripts package provided by Create React App requires a dependency:
"babel-jest": "^24.9.0"
```
Local

scaffolding: fix react-scripts dependency requirements

---

Makefile

Add a `yarn-install` make target similar to what the gateway scaffolding has.

tools: add yarn-install make target

---

docs/development/backend.md

docs: fix typo in backend development

---

frontend/tsconfig.json

Exclude dist assets from default tsconfig

frontend: exclude dist directories from tsconfig

---

frontend/.storybook/manager-head.html
frontend/netlify/netlify.toml

Update the favicon of our component website
manual

docs: update storybook favicon

---

frontend/packages/core/src/Input/select.tsx

Handle edge case where Select options are undefined.
manual

frontend: handle undefined options in Select component

---

backend/service/topology/cache.go

Fix a bug where we would leak database connections. We explicitly call `conn.Close()` and remove the logic to manually unlock advisory locks as they are automatically released when the connection is severed.
This makes it simpler to reason about and the connection logic more clear.
locally.

topology: simplify leader elect db connection

---

.github/workflows/api.yml
.github/workflows/backend.yml
.github/workflows/scaffolding.yml

ci: use go version 1.16

---

.github/workflows/backend.yml

Test to see if we can build at warp speed :rocket:.
CI

ci: add cache to backend actions

---

backend/service/topology/cache.go

Respect the cache TTL configuration for the topology cache.
local
Fixes #
#1081

topology: respect cache TTL

---

.github/workflows/stale.yaml

Remove the dry-run flag from stalebot.
CI, audit of output.

ci: enable stalebot

---

frontend/workflows/ec2/src/terminate-instance.tsx

And rename tags section.
CI, local.
Missing name

aws: add instance name to details table

---

.dockerignore
.gitignore
frontend/.gitignore

Looked for discrepancies in `.gitignore` and `frontend/.gitignore` and updated `.dockerignore` with findings.
Local Docker build.

tools: update .dockerignore

---

frontend/packages/core/src/text.tsx

Fixes text wrapping prematurely in the Code component.
manual & storybook

frontend: fix text wrap in Code component

---

frontend/packages/core/src/tab.tsx

frontend: fix padding of tabs

---

frontend/packages/core/src/button.tsx
frontend/packages/core/src/index.tsx
frontend/packages/core/src/stories/icon-button.stories.tsx

Adds a new core component, `IconButton`.

frontend: add IconButton component

---

backend/service/k8s/pods_test.go

just a quick fix as per mcutalo's suggestions
Fixes #

fix test values

---

backend/mock/service/authnmock/storage.go
backend/service/authn/oidc.go
backend/service/authn/oidc_test.go

Reverts lyft/clutch#1176, bug fixed by #1182

Revert "Revert "oidc: write clutch issued token to token storage (#1157)""

---

backend/gateway/mux/mux.go
backend/module/authn/authn.go

Found a bug in the code related to the status header. Fixing the functionality but removing the existing use of it since the code was previously correct anyways.
Read the code, preparing for additional test coverage and changes.

authn: fix location-status header override

---

backend/module/chaos/serverexperimentation/xds/xds_integration_test.go

Seems to be flaking quite a bit on main

experimentation: increase integration test timeout

---

backend/.golangci.yml
backend/internal/test/integration/helper/envoytest/envoy.go
backend/service/audit/setup.go
backend/service/chaos/experimentation/experimentstore/storer.go
backend/service/envoyadmin/parse.go

core: require protojson

---

backend/service/chaos/experimentation/experimentstore/storer_test.go

Tests are not fully verifying functionality.
Unit.

chaos: assert mock expects in storer tests

---

frontend/packages/core/src/Input/text-field.tsx
frontend/packages/core/src/Resolver/index.tsx
frontend/packages/core/src/Resolver/input.tsx
frontend/packages/wizard/package.json
frontend/packages/wizard/src/wizard.tsx
frontend/workflows/ec2/src/resize-asg.tsx

Add query param hydration support to workflows that utilize the resolver.
manual

frontend: add query hydration to resolver

---

docs/blog/2021-02-01-frontend-asset-passthrough.md

I changed my github username to @mikecutalo.

blog: update mikes github username

---

frontend/packages/core/src/popper.tsx
frontend/packages/core/src/stories/popper.stories.tsx

Add a Popper component to core

frontend: add popper component

---

frontend/packages/core/src/index.tsx

frontend: export Accordion components from core

---

frontend/packages/core/src/Resolver/hydrator.tsx

Sort resolver select options
manual

frontend: sort Resolver select options

---

frontend/packages/core/src/Resolver/hydrator.tsx

Revert "frontend: sort Resolver select options"

---

backend/.golangci.yml
backend/gateway/config_test.go
backend/module/audit/audit.go
backend/module/chaos/serverexperimentation/xds/xds.go
backend/module/chaos/serverexperimentation/xds/xds_cache_test.go
backend/module/chaos/serverexperimentation/xds/xds_integration_test.go
backend/module/chaos/serverexperimentation/xds/xds_test.go
backend/service/k8s/clientset.go
backend/service/k8s/k8s_test.go

Deprecation swap for ptypes Duration methods.

core: require durationpb

---

frontend/packages/core/package.json
frontend/workflows/kinesis/package.json
frontend/workflows/serverexperimentation/package.json
frontend/workflows/sourcecontrol/package.json
frontend/workflows/sourcecontrol/src/create-repository.tsx
frontend/yarn.lock

Use consistent version of react-hook-form throughout all workflows.
manual

frontend: use consistent version of react-hook-form

---

backend/.golangci.yml
backend/mock/service/auditmock/auditmock.go
backend/mock/service/chaos/experimentation/experimentstoremock/simplestorer.go
backend/module/audit/audit.go
backend/module/chaos/serverexperimentation/xds/xds_cache_test.go
backend/module/chaos/serverexperimentation/xds/xds_integration_test.go
backend/service/audit/storage/sql/sql.go
backend/service/chaos/experimentation/experimentstore/experiment.go
backend/service/chaos/experimentation/experimentstore/experiment_run.go
backend/service/chaos/experimentation/experimentstore/experiment_specification.go
backend/service/chaos/experimentation/experimentstore/experiment_specification_test.go
backend/service/chaos/experimentation/experimentstore/property_date.go

core: require timestamppb

---

api/k8s/v1/k8s.proto
backend/api/k8s/v1/k8s.pb.go
backend/api/k8s/v1/k8s.pb.validate.go
backend/service/k8s/pods.go
backend/service/k8s/pods_test.go
frontend/api/src/index.d.ts
frontend/api/src/index.js

- Adding InitContainer details to the pod message
- Adding additional state details to the container state
These new fields will help us figure out the exact state of the pod at any given time.
- local
- unit

k8s: update pod proto to extract more status info

---

docs/_website/src/theme/BlogPostItem/index.tsx

Try to catch up the swizzled component with some changes to docusaurus.
Deploy preview card validation.

docs: fix twitter cards for blog posts

---

docs/_website/docusaurus.config.js
docs/_website/src/pages/index.tsx

Some other SEO fixes.
CI deploy.

docs: fix default meta tags

---

frontend/packages/core/src/index.tsx

Export both `Card` and `CardContext`. Also I sorted the exports as a few were out of order.
n/a

frontend: export Card and CardContent

---

frontend/packages/core/src/Input/radio.tsx
frontend/packages/core/src/Input/stories/radio.stories.tsx

frontend: add name, value, and onChange props to Radio

---

frontend/packages/app/config-overrides.js

Run esbuild against all source files instead of just the application ones.
Manual and CI

frontend: run esbuild on all source

---

frontend/packages/core/src/Table/index.tsx
frontend/packages/core/src/Table/stories/table.stories.tsx
frontend/packages/core/src/Table/table.tsx
frontend/packages/core/src/index.tsx
frontend/packages/core/src/popper.tsx

Add support for table row actions

frontend: support table row actions

---

backend/service/k8s/cache.go

Previously if a failure to look up a resource occurred, the error would be caught but the corresponding code would still execute. If we catch an error dont execute the corresponding code.
Also I added a bit more information to the error log so we know what cluster its coming from.
```
ERROR: Unable to list deployments to populate Kubernetes cache
...
panic: interface conversion: runtime.Object is nil, not *v1.DeploymentList
goroutine 304 [running]:
github.com/lyft/clutch/backend/service/k8s.(*svc).cacheFullRelist(0xc0000717c0, 0x4737b18, 0xc000071b40, 0xc00164ccf0, 0x13, 0xc0013204e0, 0xc001320558, 0xc0013205d0, 0x68c61714000)
/code/clutch-private/clutch/backend/service/k8s/cache.go:138 +0x10bb
created by github.com/lyft/clutch/backend/service/k8s.(*svc).startInformers …
```

k8s cache: fix panic during relist

---

.github/CODEOWNERS

Updating GitHub owners permissions for new [maintainers team](https://github.com/orgs/lyft/teams/clutch-maintainer/).

ci: update github owners for new maintainers team

---

backend/service/chaos/experimentation/terminator/terminator.go

Ran into some issues when trying to enable `Terminator`. This PR fixes discovered issue.
Actually running automated experiment termination and monitoring it working.

experimentation: fix terminator's initialization

---

backend/service/chaos/experimentation/terminator/terminator.go

Return error in case monitor initialization fails.
None

experimentation: handle terminator initialization error

---

frontend/packages/core/src/Network/index.ts

Previously, we used to handle unauthenticated users from the middleware and redirect them to the `/v1/authn/login` url which in turn returns 200. This request was handled by the axios client success interceptor and error was thrown to handle cors policy. Since now we have removed that frontend redirection from the UI. we don't have redirection when apis are called through axios clients.
```
const axiosClient = axios.create({
// n.b. the client will treat any response code >= 400 as an error and apply the error interceptor.
validateStatus: status => {
return status < 400;
},
});
axiosClient.interceptors.response.use(resp => resp, errorInterceptor);
```
Reference: https://github.com/lyft/clutch/pull/325

frontend: fix auth redirect for axios client

---

frontend/packages/core/src/index.tsx
frontend/packages/core/src/popper.tsx

Export the popper and popper item components 
CI

frontend: export popper

---

frontend/packages/core/src/index.tsx

frontend: export chip component

---

frontend/packages/core/src/chip.tsx

Update Chip font size and padding.
manual

frontend: update chip font styling

---

.github/CODEOWNERS

Fix the team name for * owners https://github.com/orgs/lyft/teams/clutch-maintainer

ci: fix owner team name

---

frontend/workflows/experimentation/src/list-view.tsx

Contain manage experiments list
manual

frontend: contain experimentation table list

---

frontend/packages/core/src/Table/stories/metadata-table.stories.tsx

WizardContext has [a prop](https://github.com/lyft/clutch/blob/main/frontend/packages/core/src/Contexts/wizard-context.tsx#L9) that's missing from the Metadata Table story
manual

frontend: fix metadata table story

---

.github/workflows/backend.yml

Run integration tests in parallel to unit tests (as a separate CI job)
N/A

ci: run integration tests in parallel to unit tests

---

docs/development/frontend.md
docs/sidebars.json

Add storybook to the development category under a frontend category
manual
Fixes #1066
Link to changes: https://608b004d0e09660008364b0b--clutch-preview.netlify.app/docs/development/frontend

docs: add storybook to dev FE sidebar

---

frontend/.storybook/main.js
frontend/package.json
frontend/yarn.lock

Developers can now check if their new components and/or changes are accessible.
manual

frontend: add a11y plugin to storybook

---

backend/service/bot/bot_helper.go
backend/service/bot/bot_helper_test.go

PR exports a helper func to use in the internal implementation.

bot: export helper func

---

.vscode/extensions.json

adds recommended vscode extensions:
- proto3
- eslint
- golang

tools: add recommended vscode extensions

---

frontend/packages/tools/jest.config.js
frontend/packages/tools/jest.setup.js
frontend/packages/tools/package.json

Run lint against tools package
manual & CI

frontend: lint tools package

---

api/config/service/auditsink/slack/v1/slack.proto
backend/api/config/service/auditsink/slack/v1/slack.pb.go

slackconfig: remove todo and add link to sink docs

---

docs/development/feature-flags.md
docs/sidebars.json

Add documentation on feature flags.
manual

docs: add feature flag documentation

---

docs/_website/generator/generate.go
docs/_website/package.json
docs/_website/tsconfig.json
docs/_website/watcher.ts

Add hot reloading to docs.
manual
Fixes #22

docs: support hot reloading

---

backend/gateway/core.go
backend/mock/gateway.go
backend/mock/service/projectmock/projectmock.go
backend/module/project/project.go
backend/module/project/project_test.go
backend/service/project/project.go
backend/service/project/project_test.go

`GetProjects` API implementation.
Unit / Local.
```shell
curl --location --request POST 'http://localhost:8080/v1/project/getProjects' \
--header 'Content-Type: application/json' \
--data-raw '{
"names": [
"foo",
"bar"
]
}'
{
"projects": [
{
"name": "foo",
"tier": "1",
"owners": [
"foo@foo.com"
],
"languages": [
"go"
],
},
{
"name": "bar",
"tier": "3",
"owners": [
"bar@bar.com"
],
"languages": [
"bash",
"python"
],
"data": {
"description": "bar project",
}
}
]
}
```

project: GetProjects API

---

frontend/workflows/projectSelector/src/hello-world.tsx

Make groups collapsible.
Manual

project selector: collapsible groups

---

frontend/workflows/projectSelector/src/hello-world.tsx

Most thing aside from container padding and outer sidebar styles.
Side note: File is becoming kind of a mess. After we finish styling for today we can start breaking it apart and reorganizing it.
Manual

project selector: style project group header and projects

---

frontend/packages/core/src/Input/checkbox.tsx
frontend/workflows/projectSelector/src/hello-world.tsx
frontend/workflows/projectSelector/src/project-group.tsx

Incorporated changes from the latest Figma.
Manual.

project selector: incorporate figma changes

---

tools/frontend-e2e.sh

Fixes e2e startup timeouts for both frontend and backend.
manual

ci: fix e2e startup timeouts

---

docs/_website/package.json
docs/_website/src/components/Share/index.tsx
docs/_website/src/components/Share/styles.css
docs/_website/src/theme/BlogPostItem/index.tsx
docs/_website/yarn.lock

Add share links to blog posts.
manual

docs: add share links to blog posts

---

frontend/packages/core/src/index.tsx
frontend/workflows/projectSelector/src/hello-world.tsx
frontend/workflows/projectSelector/src/selector-reducer.tsx

PR adds support for
* calling the API for user-owned projects & custom projects
* processing the API response results and adding it to the State
* an error state/reducer (simple setup for now) for when the API returns an error. if there's an error, it'll be rendered in the project selector
Mentioned the TODOs in the PR to address in follow up PRs.
Locally
To test yourself, can run the real local backend or the mock api (search for the "comments" project for the scenario of calling api for a custom project)

project selector: project api integration

---

docs/_website/src/components/Share/index.tsx

Add Google Analytics to share links.
manual

docs: track shares via GA

---

frontend/workflows/projectSelector/src/hello-world.tsx

Always make an API with all the custom projects in the group.Projects state

project selector: update API call

---

frontend/packages/wizard/src/wizard.tsx

Remove unused prop from wizard navigation state that made it in as part of #1502

frontend: cleanup unused state prop

---

frontend/workflows/k8s/src/pods-table.tsx

Add origin to delete action from k8s dashboard
manual

frontend: add origin to k8s pods delete action

---

frontend/packages/core/src/Input/checkbox.tsx
frontend/workflows/projectSelector/package.json
frontend/workflows/projectSelector/src/hello-world.tsx
frontend/workflows/projectSelector/src/project-group.tsx

Fixes lint errors (`make frontend-lint-fix`). Will handle the `Dependency cycle detected import/no-cycle` in a separate PR (due to cyclical importing of the interfaces we've defined); will create a types file.

project selector: lint fixes

---

frontend/packages/app/src/clutch.config.js
frontend/workflows/projectSelector/src/index.tsx
frontend/workflows/projectSelector/src/project-selector.tsx

project-selector: rename workflow

---

frontend/packages/core/src/Input/checkbox.tsx

Fixes 
```
/home/runner/work/clutch/clutch/frontend/packages/core/src/Input/checkbox.tsx
Error:   81:3  error  Expected a default case  default-case
```
Tested locally in storybook

project selector: fix TS lint switch error

---

frontend/workflows/k8s/src/pods-table.tsx

Use new navigation hook origin shorthand in K8s pods actions.
manual

frontend: use origin shorthand in k8s action

---

docs/blog/2021-05-18-chaos-experimentation.md

Added blogpost for Chaos Experimentation Framwork

docs: Blogpost on Chaos Experimentation Framework

---

frontend/workflows/projectSelector/src/project-group.tsx

PR alphabetizes list of rendered projects in the list
locally

project selector: alphabetize list of rendered projects in the list

---

frontend/workflows/projectSelector/src/dash.tsx

Flex grow the main container so cards don't have to use absolute positioning.
Manual

dash: fix main area container

---

backend/service/github/github.go
backend/service/github/github_test.go

It is useful to have the parent SHA 
Fixes #

add parent to commit response

---

tools/scaffolding/templates/gateway/frontend/package.json

Add the @clutch-sh/tools package to the generated gateway since it's leveraged by the frontend.
manual

tools: add frontend tools package to gateway scaffolding

---

docs/advanced/security-auditing.md
docs/development/feature.md

Update feature dev docs to account for custom gateway and fix go package name in proto definition.
manual

docs: update go import to account for custom gateway

---

frontend/packages/core/src/AppLayout/header.tsx

Per the designer, the top bar should be fixed.
Before
After
Will follow up with independent scrolling for main content area and sidebar.

layout: fixed app bar

---

frontend/workflows/projectSelector/src/project-selector.tsx

Fixes bug where projectData would not be available the first time a project was selected.
Manual.

dash: check for projectData before calling update hook

---

frontend/workflows/projectSelector/src/index.tsx

Export `DashState` so it can be utilized in private cards.

dash: export DashState type

---

frontend/packages/core/src/dialog.tsx

Make the Dialog component responsive.
manual

frontend: responsive dialog

---

examples/amiibo/frontend/workflows/amiibo/src/hello-world.tsx
frontend/packages/core/src/Table/accordion-table.tsx
frontend/packages/core/src/Table/stories/table.stories.tsx
frontend/packages/core/src/Table/table.tsx
frontend/workflows/envoy/src/remote-triage/clusters.tsx
frontend/workflows/envoy/src/remote-triage/listeners.tsx
frontend/workflows/k8s/src/crons-table.tsx
frontend/workflows/k8s/src/deployments-table.tsx
frontend/workflows/k8s/src/pods-table.tsx
frontend/workflows/k8s/src/stateful-sets-table.tsx

Revamp the Table component to be responsive and use grid layout.
manual

frontend: revamp table to be responsive

---

frontend/packages/core/src/stories/typography.stories.tsx
frontend/packages/core/src/typography.tsx

Fix Typography story allowing all props to be propagated. Also, change type of the field to be a color picker.
manual

frontend: fix typography story

---

backend/mock/service/githubmock/githubmock.go
backend/service/github/github.go
backend/service/github/github_test.go

Use the header response to keep track of the github rate limit
make backend-test
Fixes #

backend: github: keep track of rate limit

---

.github/workflows/api.yml
.github/workflows/backend.yml
.github/workflows/frontend.yml
.github/workflows/scaffolding.yml
tools/frontend-e2e.sh

Update all actions that use the go runtime to 1.17.0
CI

CI: update actions to go 1.17.0

---

frontend/workflows/projectSelector/src/dash.tsx

dash: always fill height

---

frontend/.gitignore

Add comment to gitignore file to denote files generated by Clutch.

housekeeping: add comment to gitignore file

---

frontend/workflows/projectSelector/src/dash.tsx

Fix overflow behavior of card container, before it would scroll the entire page including the selector.
*AFTER*
Manual

dash: fix card container overflow behavior

---

frontend/packages/core/src/card.tsx
frontend/workflows/projectSelector/src/card.tsx
frontend/workflows/projectSelector/src/dash.tsx

PR adds a new actions prop to the core card header which gets used in the dash card framework for opening/closing a card.

card framework: add actions to card header

---

backend/go.mod
backend/go.sum

bump google.golang.org/grpc
CI

housekeeping: update google.golang.org/grpc to v1.40.0

---

.github/CODEOWNERS

We've renamed our team :)
Fixes #

Re-naming team to lyne-clients

---

frontend/workflows/projectSelector/src/selector-reducer.tsx

Dash: fix lookup of projects that do not exist in response.
manual

frontend: ignore non-existent projects in dash

---

docs/README.md

https://docusaurus.io/docs
The current link gives a 404
Fixes #

fix docusaurus link

---

frontend/packages/core/src/card.tsx

fix key warning in card header
manual

frontend: fix key warning in card header

---

Dockerfile

housekeeping: docker node to 16.x

---

frontend/packages/core/src/index.tsx

Export the `Code` component from core.
CI

frontend: export Code component from core

---

backend/retry/options.go
backend/retry/retry.go
backend/retry/retry_test.go

backend: add retry library
Added test cases
Fixes #790

backend: add retry library

---

frontend/packages/app/src/clutch.config.js
frontend/workflows/k8s/src/cordon-node.tsx
frontend/workflows/k8s/src/index.tsx

Add workflow for cordon/uncordon node. Follow up to #1906, #1907 , & #1909.
Workflow demo:
https://user-images.githubusercontent.com/2972218/144673825-b2b4f246-6d9a-4f16-91d7-bf34fa2e8c67.mov

k8s: cordon/uncordon node workflow

---

backend/service/k8s/cache.go

Implement caching for Node type in order to enable autocomplete.

k8s: autocomplete for nodes

---

frontend/packages/core/src/Resolver/index.tsx

It is useful to have notes so that during the resolver we can give more info to the users of the workflow
Fixes #

FE: add `NotePanel` to resolver along with notes in props

---

frontend/packages/core/src/Feedback/alert.tsx

Proxy severity to alert component to render correct icon.
manual

frontend: proxy severity to alert component

---

docs/advanced/workflow-feedback-framework.md
docs/sidebars.json

PR adds documentation on the workflow feedback features and how to configure it.
https://deploy-preview-1997--clutch-preview.netlify.app/docs/advanced/workflow-feedback-framework
https://github.com/lyft/clutch/issues/1797
Example:

docs: Add docs on workflow feedback collection

---

frontend/packages/core/src/Input/select.tsx
frontend/packages/core/src/NPS/feedback.tsx
frontend/packages/core/src/NPS/header.tsx

- Fixed combinations of workflows
- Adjusting spacing around label
- Adjusted select styling to max out to 50% of viewport

frontend: NPS Sizing Adjustments

---

.github/renovate.json

Ignoring esbuild dependency until we can adjust the build system to handle the new updates.

housekeeping: ignore esbuild dependency

---

.github/CODEOWNERS

Update CODEOWNERS from lyne to loop

---

frontend/workflows/projectSelector/src/dash.tsx
frontend/workflows/projectSelector/src/index.tsx
frontend/workflows/projectSelector/src/types.tsx

- Related to https://github.com/lyft/clutch/pull/2011
- Forgot to export DashError type
Manual production builds

frontend: ProjectSelector - exporting DashError type

---

docs/development/feature.md

Update the feature development guide to account for the [tally v4 upgrade](https://github.com/lyft/clutch/pull/1983).
manually built a gateway

docs: update feature guide for tally upgrade

---

docs/development/feature.md
tools/scaffolding/templates/gateway/Makefile

Update feature dev docs for changes to table props and include a new step to generate a lockfile before running the frontend dev target.
manually built a gateway

docs: update feature dev docs for frontend changes

---

frontend/packages/core/src/AppProvider/index.tsx

This change fixes the nested routing pattern present in Clutch which causes issues during minor version upgrades to react-router. It's been addressed in https://github.com/lyft/clutch/pull/1981 but fixing it in a smaller PR to narrow scope.
Manual

frontend: update routing to fix nested route bug

---

frontend/packages/core/src/Input/text-field.tsx
frontend/workflows/projectSelector/src/project-selector.tsx

revert PR #2003

---

.github/workflows/scaffolding.yml

Update the scaffolding CI to generate a lockfile for the frontend before starting.
CI

ci: update scaffolding tests to install frontend deps

---

docs/development/feature.md

Update import paths in feature dev doc to specify backend import directory
manual

docs: update feature dev path for service/module imports

---

docs/development/feature.md

Clarify the frontend scaffolding and file names 
N/A

docs: add clarifying details to feature dev steps

---

frontend/packages/core/src/AppProvider/index.tsx

Fixes nested routes in the latest react router version.
manual

frontend: fix nested workflow paths

---

tools/frontend-e2e.sh

see https://github.com/lyft/clutch/pull/1620 for more context.
We are seeing flakiness and this may fix it.
Fixes #

bump startup time to 240s to try to fix flakiness

---

frontend/packages/core/src/AppProvider/index.tsx
frontend/packages/core/src/AppProvider/registrar.tsx

Additional route changes that allow clutch to work with the latest react router.
manually built gateway and copied compiled code into the dist assets used in the gateway.

frontend: more react router path fixes

---

backend/mock/gateway.go
backend/mock/service/shortlinkmock/shortlinkmock.go
backend/module/shortlink/shortlink.go
backend/module/shortlink/shortlink_test.go
backend/service/shortlink/shortlink.go

Just the scaffolding of the new shortlink service, including some new mock bits. A followup pr will include the impls.
local / unit.

shortlink: backend scaffolding

---

LICENSE

- Saw that year and name for Copyright information were missing from our LICENSE file, adding them in

housekeeping: updating license fields

---

frontend/workflows/k8s/src/delete-pod.tsx
frontend/workflows/k8s/src/index.tsx
frontend/workflows/k8s/src/tests/__snapshots__/delete-pod.test.tsx.snap

It is nice to have notes support for delete pod
unit
Fixes #

[feedback] add support for notes to deletepod

---

frontend/packages/app/src/clutch.config.js
frontend/workflows/projectCatalog/package.json
frontend/workflows/projectCatalog/src/catalog-reducer.tsx
frontend/workflows/projectCatalog/src/catalog.tsx
frontend/workflows/projectCatalog/src/index.tsx
frontend/workflows/projectCatalog/src/language-icon.tsx
frontend/workflows/projectCatalog/src/project-card.tsx
frontend/workflows/projectCatalog/src/storage.tsx
frontend/workflows/projectCatalog/src/types.tsx
frontend/yarn.lock

- Adds search page for Project Catalog
- Adds fontawesome icons for branding
- Credit to @dschaller 
manual

feature: Add Project Catalog Search

---

frontend/packages/core/src/Feedback/error/stories/error.stories.tsx

Adjust the path for the Error component in storybook
local
storybook
Fixes # https://github.com/lyft/clutch/issues/2095

storybook: move path for error component

---

frontend/workflows/envoy/src/index.tsx
frontend/workflows/envoy/src/remote-triage/index.tsx
frontend/workflows/envoy/src/tests/__snapshots__/remote-triage.test.tsx.snap

It is useful to allow for query hydration in the envoy triage flow.
local
Fixes #

[feedback] FE: envoy triage: allow for query params

---

frontend/packages/core/src/Charts/helpers.tsx
frontend/workflows/projectSelector/src/dash.tsx

This is part of a wider effort to address the numerous TODOs in the code base
Fixes #

rewrite some smonero TODOs into comments since they are never going to be done (more like TODONTS)

---

frontend/workflows/projectSelector/package.json

Publish project selector package to NPM
N/A

frontend: publish project-selector

---

frontend/workflows/projectCatalog/src/details/index.tsx
frontend/workflows/projectCatalog/src/details/quick-links.tsx

- Fixing build issues for Quick Links
manual

frontend: update project catalog quick links for optional values

---

frontend/packages/core/src/Charts/helpers.tsx
frontend/packages/core/src/Charts/tests/helpers.test.tsx

Pt 2 of many of adding tests to the FE
local
Fixes #

FE: add tests for chart helper funcs

---

frontend/workflows/projectCatalog/src/details/index.tsx

- Hides the quick links if there aren't any
manual

ProjectCatalog: QuickLinks Patch

---

frontend/packages/core/src/Feedback/error/index.tsx

Ran into an issue where status is not defined when testing the catalog. Adding qmarks helps prevent such issues.
Fixes #

frontend: handle undefined error component details

---

frontend/workflows/projectCatalog/src/details/card.tsx
frontend/workflows/projectCatalog/src/details/index.tsx
frontend/workflows/projectCatalog/src/index.tsx

- Option to hide loading indicator
- Hide title row if no title present
- Export CardType
- Hide loading indicator on info card
manual

ProjectCatalog: Loading & Title Patch

---

frontend/packages/core/src/index.tsx
frontend/workflows/projectCatalog/src/details/card.tsx
frontend/workflows/projectCatalog/src/details/helpers.tsx

- Modified title to take a typography variant
- Cleaned up some of the prop passing
- Moved the loadingIndicator onto the body interface instead of the base card
manual

ProjectCatalog: adjusting card and title

---

frontend/workflows/projectCatalog/src/catalog/index.tsx
frontend/workflows/projectCatalog/src/details/header.tsx

Update the font, color, and text of project catalog breadcrumbs
manual

frontend: udpate project catalog breadcrumb styling

---

frontend/workflows/projectCatalog/src/catalog/project-card.tsx

Show icon and change cursor type to pointer on card hover within project catalog
manual

frontend: add icon & show pointer on project catalog card hover

---

frontend/workflows/projectCatalog/src/catalog/index.tsx

Navigate users to the searched project's details page if the project is valid.
manual

frontend: project catalog search will navigate to details on success

---

frontend/workflows/projectCatalog/src/catalog/index.tsx

add subtext to project catalog index page
manual

frontend: add subtext to project catalog index header

---

frontend/workflows/projectCatalog/src/catalog/index.tsx
frontend/workflows/projectCatalog/src/catalog/project-card.tsx

- Remove language icon
- Adjust spacing
- Various minor updates to color and other properties
**Before**
**After**

catalog: update card style on index search page

---

frontend/packages/core/src/Charts/index.tsx
frontend/packages/core/src/index.tsx

Need to export these to use them internally.
no
Fixes #

FE: packages: export charts and chart types

---

frontend/packages/core/src/AppLayout/user.tsx

support overriding the userId from env variables
manual

frontend: allow for user override in dev

---

frontend/workflows/projectCatalog/src/details/header.tsx

- Modified length check and is it showing a '0' on initial load
manual

frontend: Fixing loading issue with catalog header

---

frontend/workflows/projectCatalog/src/catalog/index.tsx

Fix the navigation behavior for project catalog -> project details on successful search. This was broken before as the state was not guaranteed to be updated by the time the filter happened.
manual

frontend: fix project catalog search navigation

---

frontend/workflows/projectCatalog/package.json
frontend/workflows/projectSelector/package.json

Update react-hook-form deps in project catalog and project selector.
Builds off #2039 
CI

housekeeping: update remaining react-hook-form dependencies

---

frontend/packages/core/src/Resolver/input.tsx

Reverts lyft/clutch#2198
realized this doesn't actually work in staging

Revert "FE: allow for autosubmit in autocomplete for resolvers"

---

frontend/packages/core/src/Charts/tests/timeseries.test.tsx

FE still needs more tests, but this is a nice addition.
local
Fixes #

FE: tests: add some rendering tests for timeserieschart

---

frontend/workflows/projectCatalog/src/details/helpers.tsx

Remove unused StyledLink export
CI

frontend: from styled link export from project catalog helpers

---

frontend/workflows/projectCatalog/src/details/header.tsx

Fix key console error for project catalog breadcrumbs
manual

frontend: fix key error in project catalog breadcrumbs

---

Makefile

Ensure yarn is installed before running make frontend preflight checks
N/A

tools: ensure yarn installed before running make frontend

---

docs/advanced/auth.md

Add documentation for `subject_claim_name_override` field.
Fixes #

docs: Update OIDC docs with subject_claim_name_override field

---

tools/scaffolding/templates/gateway/frontend/package.json

- ESLint upgrade (#2113) updated react-scripts, but did not update the scaffolding package to match
- Manual
- Run `make scaffold-gateway` then `cd ../clutch-custom-gateway && make`

housekeeping: scaffold patch

---

frontend/packages/wizard/package.json
frontend/packages/wizard/src/step.tsx
frontend/packages/wizard/src/wizard.tsx

- Breaking apart https://github.com/lyft/clutch/pull/2288
- Contains Wizard changes
manual

muiv5 - Breaking Apart - Wizard Changes

---

frontend/packages/core/src/AppProvider/workflow.tsx

Just adding some comments
no
Fixes #

[DEVCON-473] add some docstrings to the workflow interface

---

frontend/packages/core/src/index.tsx

export styledcomponent

---

backend/mock/service/awsmock/awsmock.go

Adding mock responses for the batch get functionality

[DS-9408] Adding mock responses for batch get

---

frontend/api/package.json
frontend/lerna.json
frontend/packages/app/package.json
frontend/packages/core/package.json
frontend/packages/data-layout/package.json
frontend/packages/tools/package.json
frontend/packages/wizard/package.json
frontend/workflows/dynamodb/package.json
frontend/workflows/ec2/package.json
frontend/workflows/envoy/package.json
frontend/workflows/experimentation/package.json
frontend/workflows/k8s/package.json
frontend/workflows/kinesis/package.json
frontend/workflows/projectCatalog/package.json
frontend/workflows/projectSelector/package.json
frontend/workflows/redisexperimentation/package.json
frontend/workflows/serverexperimentation/package.json
frontend/workflows/sourcecontrol/package.json
tools/publish-frontend.sh
tools/scaffolding/templates/frontend/package.json
tools/scaffolding/templates/gateway/frontend/package.json
tools/scaffolding/templates/gateway/frontend/workflows/echo/package.json

Versioning packages for MUIv5 Release

housekeeping: MUIv5 Versioning

---

frontend/package.json
frontend/workflows/k8s/package.json
frontend/workflows/projectCatalog/package.json
frontend/yarn.lock

- Was seeing a memory leak with react-timeago. This was fixed in ^7.0.0
manual

frontend: react-timeago update

---

frontend/packages/core/src/NPS/header.tsx

- Adjusting usage of get
manual

frontend: NPS - Lodash patch

---

tools/scaffolding/scaffolder.go

give preference to yarn script in scaffolder and fallback to the global yarn installation.
manual

tools: use yarn script in scaffolder

---

frontend/packages/core/src/Input/select.tsx
frontend/packages/core/src/Input/tests/select.test.tsx

This reverts commit edb8a7398437d6ec4c9dece3510d11fdbe949243.
Found another use case where this is broken, reverting for now until we can get it addressed.
manual

Revert "frontend: Select - support multiple (#2528)"

---

frontend/packages/core/src/Table/table.tsx

add a new prop to `Table` for controlling overflow layout.
manual

frontend: add support for table overflow configuration

---

frontend/workflows/audit/package.json

The frontend publish script assumes [all packages have consistent versions](https://github.com/lyft/clutch/blob/main/tools/publish-frontend.sh#LL3-L3C8) so giving the audit workflow the expected versioning for ease of maintenance.
N/A

frontend: consistent versioning for audit workflow

---

frontend/workflows/audit/package.json

Make audit workflow public to publish it
N/A

frontend: make audit workflow public

---

frontend/workflows/audit/src/logs/event-row.tsx

Give user feedback when no events are returned.
Manual

frontend: audit workflow no event feedback

---

frontend/packages/core/src/Input/date-time.tsx
frontend/packages/core/src/Input/stories/form.stories.tsx
frontend/packages/core/src/Input/stories/text-field.stories.tsx
frontend/packages/core/src/Input/text-field.tsx
frontend/packages/core/src/Resolver/input.tsx
frontend/packages/core/src/Table/metadata-table.tsx
frontend/packages/core/src/stories/dialog.stories.tsx
frontend/workflows/k8s/src/resize-hpa.tsx

Adding warning message if the change in min or max values is more than 50% difference between current and new values
https://user-images.githubusercontent.com/1994723/212132285-e7fe2aea-2a39-4538-b593-bdb91771a2f1.mov
Fixes #

frontend: adding warning message if new value is more than 50% different

---

frontend/workflows/envoy/src/tests/__snapshots__/remote-triage.test.tsx.snap
frontend/workflows/envoy/src/tests/remote-triage.test.tsx

Update to the Envoy workflow's snapshot test, using RTL instead of enzyme
manual

frontend: update envoy workflow snapshot

---

frontend/workflows/ec2/src/tests/__snapshots__/reboot-instance.test.tsx.snap
frontend/workflows/ec2/src/tests/__snapshots__/resize-asg.test.tsx.snap
frontend/workflows/ec2/src/tests/__snapshots__/terminate-instance.test.tsx.snap
frontend/workflows/ec2/src/tests/reboot-instance.test.tsx
frontend/workflows/ec2/src/tests/resize-asg.test.tsx
frontend/workflows/ec2/src/tests/terminate-instance.test.tsx

Updated the snapshot tests for the EC2 components ResizeAutoscalingGroup and TerminateInstance. Also noticed RebootInstance had no test, so I added it.
manual

frontend: migrate ec2 tests to rtl

---

frontend/workflows/experimentation/src/tests/__snapshots__/list-experiments.test.tsx.snap
frontend/workflows/experimentation/src/tests/__snapshots__/view-experiment-run.test.tsx.snap
frontend/workflows/experimentation/src/tests/list-experiments.test.tsx
frontend/workflows/experimentation/src/tests/view-experiment-run.test.tsx

Updated the experiments workflow's snapshot tests for ViewExperimentRun and ListExperiments
manual

frontend: update experiments workflows snapshots

---

frontend/workflows/k8s/src/tests/__snapshots__/delete-pod.test.tsx.snap
frontend/workflows/k8s/src/tests/__snapshots__/resize-hpa.test.tsx.snap
frontend/workflows/k8s/src/tests/delete-pod.test.tsx
frontend/workflows/k8s/src/tests/resize-hpa.test.tsx

Updated the snapshot tests for k8s' ResizeHPA and DeletePod components.
manual

frontend: update k8s snapshot tests

---

frontend/workflows/redisexperimentation/src/tests/__snapshots__/experiment-details.test.tsx.snap
frontend/workflows/redisexperimentation/src/tests/__snapshots__/start-experiment.test.tsx.snap
frontend/workflows/redisexperimentation/src/tests/experiment-details.test.tsx
frontend/workflows/redisexperimentation/src/tests/start-experiment.test.tsx

Updated the tests for the redis experimentation workflow, moving them away from enzyme and to RTL. Components: ExperimentDetails and StartExperiment.
manual

frontend: migrate redis experimentation tests to rtl

---

frontend/workflows/serverexperimentation/src/tests/__snapshots__/experiment-details.test.tsx.snap
frontend/workflows/serverexperimentation/src/tests/__snapshots__/start-experiment.test.tsx.snap
frontend/workflows/serverexperimentation/src/tests/experiment-details.test.tsx
frontend/workflows/serverexperimentation/src/tests/start-experiment.test.tsx

Updated the tests for the Server Experimentation workflow, moving them away from enzyme and to RTL. Components: ExperimentDetails and StartExperiment.
manual

frontend: migrate server experimentation tests to rtl

---

backend/resolver/k8s/k8s.go

Adding a resolver for deployments in k8s. This is in order to create a workflow that modifies deployments.
Tested locally by creating a workflow component that looks up deployments. Was able to successfully find deployments in my cluster.

k8s: resolver for deployment

---

frontend/packages/core/src/Input/index.tsx
frontend/packages/core/src/Input/select.tsx
frontend/packages/core/src/Input/stories/multi-select.stories.tsx
frontend/packages/core/src/Input/tests/select.test.tsx

Creates a new select component that supports multiple values.
https://user-images.githubusercontent.com/22361209/223369219-43464568-2f8e-4f00-accf-7e6547d582c8.mov
Added a happy path test.

frontend: Select - support multiple

---

frontend/packages/core/package.json
frontend/packages/core/src/link.tsx
frontend/yarn.lock

Added ability to override target for Link component. Also locking @mui/base to it's version via resolution.
manual

frontend: Patching Link component and locking @mui/base

---

frontend/packages/app/src/clutch.config.js
frontend/workflows/k8s/src/index.tsx
frontend/workflows/k8s/src/update-probe.tsx

Adding frontend feature based on update probes attributes
Last part of update probes feature 
Frontend section 
[Api PR.](https://github.com/lyft/clutch/pull/2687) 
[Backend PR.](https://github.com/lyft/clutch/pull/2703)
Response

frontend: update deployment probes workflow

---

frontend/workflows/projectCatalog/src/details/card.tsx

Extending support for other types of titles vs just strings
manual

frontend: Updating ProjectCatalog Card Title Type

---

frontend/packages/core/src/index.tsx
frontend/packages/core/src/quick-links.tsx
frontend/workflows/projectCatalog/src/details/index.tsx

frontend: Moving Quick Links to Core

---

frontend/packages/core/src/quick-links.tsx

Cant override inline styles so moving them to use styled components.
manual

frontend: Adjusting Styling for Quick Links

---

frontend/packages/core/src/AppLayout/user.tsx

- Add key to map returned elements
manual

frontend: add key to map's returned elements

---

backend/service/k8s/cronjob.go
backend/service/k8s/cronjob_test.go

Revert "Support upgrade CronJob api version"

---

.github/workflows/api.yml
.github/workflows/backend.yml
.github/workflows/frontend.yml
.github/workflows/scaffolding.yml
backend/go.mod
backend/go.sum
docs/_website/generator/go.mod
tools/go.mod
tools/scaffolding/templates/gateway/backend/go.mod.tmpl

Update Go version to 1.21
Ran _make_ and _make dev_ without any errors
Fixes #

Update Go version to 1.21

---

frontend/packages/core/src/AppLayout/drawer.tsx
frontend/packages/core/src/AppLayout/header.tsx
frontend/packages/core/src/AppLayout/notifications.tsx
frontend/packages/core/src/AppLayout/search.tsx
frontend/packages/core/src/AppLayout/shortLinker.tsx
frontend/packages/core/src/AppLayout/stories/header.stories.tsx
frontend/packages/core/src/AppLayout/stories/notifications.stories.tsx
frontend/packages/core/src/AppLayout/stories/searchfield.stories.tsx
frontend/packages/core/src/AppLayout/stories/user-information.stories.tsx
frontend/packages/core/src/AppLayout/tests/__snapshots__/layout.test.tsx.snap
frontend/packages/core/src/AppLayout/tests/layout.test.tsx
frontend/packages/core/src/AppLayout/user.tsx
frontend/packages/core/src/AppProvider/themes.tsx
frontend/packages/core/src/Theme/palette.tsx
frontend/packages/core/src/landing.tsx
frontend/packages/core/src/tests/__snapshots__/landing.test.tsx.snap
frontend/packages/core/src/tests/landing.test.tsx

Replace hardcoded colors with theme palette references for components in AppLayout
Also updated the `landing` component
Testing Performed
manual, unit tests

frontend: leverage theme palette for AppLayout components

---

backend/service/k8s/deployment.go
tools/golangci-lint.sh

Updating to the latest version of golangci-lint, and fix the lints along the way.

golangci-lint update 1.55.2

---

frontend/workflows/projectCatalog/src/catalog/index.tsx
frontend/workflows/projectCatalog/src/details/header.tsx

frontend: update useTheme imports for workflows

frontend: update useTheme imports for workflows

---

frontend/packages/core/src/AppLayout/drawer.tsx
frontend/packages/core/src/Feedback/error/details.tsx
frontend/packages/core/src/Input/radio.tsx
frontend/packages/core/src/Input/select.tsx
frontend/packages/core/src/Input/switchToggle.tsx
frontend/packages/core/src/Input/text-field.tsx
frontend/packages/core/src/Input/toggle-button-group.tsx
frontend/packages/core/src/NPS/header.tsx
frontend/packages/core/src/landing.tsx
frontend/workflows/projectSelector/src/project-group.tsx
frontend/workflows/projectSelector/src/project-links.tsx
frontend/workflows/projectSelector/src/project-selector.tsx

using theme.palette.contrastColor for white and black values

frontend: update black and white colors to use contrast color from theme.palette

---

.github/workflows/scaffolding.yml
tools/scaffolding/templates/gateway/frontend/package.json
tools/scaffolding/templates/gateway/frontend/workflows/echo/package.json

Recent fix took care of resolution of react-hook-form for scaffolding a workflow, it missed fixing the gateway scaffolding however.
manual

housekeeping: Fixing Scaffolding resolutions for Gateway

---

frontend/packages/wizard/src/wizard.tsx

Deconstructing the params like it was doing was causing issues if there wasn't anything passed, adjusted this to be handled better.
manual

frontend: Fixing issue with missing params for Wizard onBack

---

frontend/packages/core/src/Contexts/wizard-context.tsx

Added typing in for the onBack functionality of the Wizard context. Originally thought the parameter typing was only in the Wizard package.
manual

frontend: Fixing wizard onBack typing

---

clutch

housekeeping: Removing committed test file

---

backend/mock/service/awsmock/awsmock.go
backend/service/aws/aws.go
backend/service/aws/iam.go
backend/service/aws/iam_test.go
backend/service/aws/iface.go

This PR adds functionality for calling iam.GetRole to support https://github.com/lyft/clutch-private/pull/2500

aws: Add iam.GetRole

---

frontend/packages/core/src/AppLayout/utils.tsx
frontend/packages/core/src/card.tsx

Noticed that sometimes icons were not showing up for the workflows even if defined. This was caused by only setting the icon possibly once even if there's nothing defined. Adjusted this to fill in the path if the category is the same.
Also fixed some random console errors due to html/css props.
manual

frontend: Workflow Icon Patch

---

frontend/packages/core/src/Input/date-time.tsx
frontend/packages/core/src/Input/stories/date-time.stories.tsx

Adding error state and min and max dates

frontend: DateTime component upgrade

---

frontend/packages/core/src/Table/table.tsx

Adding forwardRef to table component so that things like scroll behavior can be manipulated from parent component

frontend: Add forwardRef to table component

---

frontend/packages/core/src/Table/table.tsx

JSX.Element has been added as a posible type for the column props, if the column is in fact a React Element then it will be render directly without any sort logic.

Add JSX.Element as a column type for Table component

---

frontend/packages/core/src/Table/components/TableHeader.tsx

Fixes the default sort in cases of undefined
manual

frontend: Patch to TableHeader to fix default sort

---

frontend/.prettierignore

Adds a prettier ignore file to try to reduce issues in vscode with formatting on save.

frontend: housekeeping - Updating prettier ignore file

---

frontend/packages/core/src/stepper.tsx
frontend/packages/core/src/stories/stepper.stories.tsx
frontend/packages/wizard/src/state.tsx
frontend/packages/wizard/src/wizard.tsx

Includes changes to the `stepper` and `wizard` components to enhance their functionality and simplify the state management. The most important changes involve adding a new `isComplete` property to the `StepProps` interface, removing the `completed` property from `StepperProps`, and updating the wizard state management to use a new action type.
* Added `isComplete` property to `StepProps` and removed `completed` property from `StepperProps`.
* Updated the `Stepper` component to use the `isComplete` property for determining step completion status.
* Replaced the `ADD_COMPLETED_STEP` action type with `ON_COMPLETE` and removed the `completed` property from the state. 
* Updated the `Wizard` component to use the new `ON_COMPLETE` action type and pass the `isComplete` property to the `Step` …

Test stepper nonlinear

---

frontend/packages/core/src/stepper.tsx

Update styles to match 4 states on non-linear stepper
1- Done
2- Active
3- Inactive 
4- Inactive with hover

add states styles to step component

---

frontend/packages/core/src/Contexts/wizard-context.tsx
frontend/packages/core/src/Table/stories/metadata-table.stories.tsx
frontend/packages/core/src/stepper.tsx
frontend/packages/wizard/src/step.tsx
frontend/packages/wizard/src/wizard.tsx

* add `isComplete` to `WizardStep ` props
* Disable Step button on nonLinear state

Set is completed

---

backend/mock/service/githubmock/githubmock.go
backend/service/github/github.go
backend/service/github/github_test.go
backend/service/github/iface.go

- Add method to GitHub service to get a Pull Request
manual, unit

backend: Update GitHub Service to get a PR

---

backend/service/github/github.go

- Enabled functionality to delete a file while creating a branch in GitHub service
Manual

backend: Support file deletion in GitHub CreateBranch

---

backend/service/github/github.go

- Added support to delete directories while creating a branch, retrying the delete operation if the [error message](https://github.com/go-git/go-billy/blob/master/memfs/storage.go#L161) states that the filePath provided is a directory.
Manual

backend: Add support for deleting dirs in GitHub CreateBranch

---

backend/mock/service/githubmock/githubmock.go
backend/service/github/github.go

- Added CreateCommit method in GitHub service
Manual

backend: Add create commit method for GitHub

---

Makefile
backend/mock/service/githubmock/githubmock.go
backend/service/github/github.go
backend/service/github/iface.go

Extends the Github service to support searching code
manual

backend: Github API - Adding Code Search capabilities

---

.github/workflows/frontend.yml
tools/scaffolding/templates/gateway/Makefile

Missed the updates from changing the makefile. This addresses that.

housekeeping: Fixing makefile from scaffolding update

---

frontend/packages/core/src/AppProvider/index.tsx
frontend/packages/core/src/WorkflowLayout/index.tsx
frontend/packages/core/src/utils/generateBreadcrumbsEntries.tsx
frontend/packages/core/src/utils/index.ts

- Renders breadcrumbs component and generate valid entries inside the workflow layout
Manual

frontend: Generate breadcrumbs inside workflow layout

---

tools/scaffolding/templates/frontend/workflow/internal/src/hello-world.tsx
tools/scaffolding/templates/frontend/workflow/internal/src/index.tsx

- Included layout options and modifications to the starting template to the scaffolding template
Manual

frontend: Include layout options in scaffolding template

---

frontend/packages/wizard/src/wizard.tsx

- Override padding removal on the event of reaching a < 600px breakpoint in the main Wizard container
Manual

frontend: Override padding removal in Wizard container

---

frontend/packages/core/src/AppLayout/index.tsx
frontend/packages/core/src/Types/app.tsx

This pull request includes changes to the `AppLayout` component in the `frontend/packages/core/src/AppLayout/index.tsx` file and the `AppConfiguration` interface in the `frontend/packages/core/src/Types/app.tsx` file. The primary goal of these changes is to introduce the option for a full-screen layout.
Enhancements to layout configuration:
* [`frontend/packages/core/src/AppLayout/index.tsx`](diffhunk://#diff-1465c1bdd75a440d3a5592c719280d01afe84948428c566711068196e9a02decL36-R45): Modified the `AppLayout` component to conditionally render the header and drawer based on the new `useFullScreenLayout` configuration option.
* [`frontend/packages/core/src/Types/app.tsx`](diffhunk://#diff-cf066233a855942622a45960706a4b5e3bb99869f102c3e33c040d7983fa6862R10): Added a new `useFullScreenLayout` …

frontend: Add full screen option to app configuration

---

backend/service/k8s/pods.go

k8s: update getPodStatus logic for crons with native sidecars

---

frontend/packages/core/src/AppLayout/utils.tsx
frontend/packages/core/src/index.tsx

workflow utils export

---

backend/mock/service/githubmock/githubmock.go
backend/service/github/github.go
backend/service/github/iface.go

- Added list check runs method to github service
Manual

backend: Add ListCheckRunsForRef method to GitHub service

---

backend/mock/service/githubmock/githubmock.go
backend/service/github/github.go
backend/service/github/github_test.go
backend/service/github/iface.go

Adding new Github service to fetch the reviews status of a PR

[backend] Add services to fetch commit and review statuses

---

frontend/workflows/ec2/src/resize-asg.tsx
frontend/workflows/ec2/src/terminate-instance.tsx
frontend/workflows/k8s/src/cordon-node.tsx

AWS - Terminate instance
The search of this workflow doesn't work on staging
AWS - Resize Autoscaling Group

Add confirmation modal to workflows

---

README.md
docs/_website/docusaurus.config.js
docs/_website/src/pages/index.tsx
docs/_website/src/pages/styles.module.css
docs/_website/src/theme/types.tsx

Please be advised that this repository is slated to be deprecated and will be marked as archived and read-only. While all existing code will remain accessible, we will no longer accept new pull requests or issues after the archiving date and no new features or updates will be developed.
Website banner:

Archival Announcement
